### ISSUE TITLE
problem on publish binary files over over websocket

### ISSUE THREAD

**Issue by ramajd** [mcollina/mosca#117]
we used eclipse PAHO  JavaScript MQTT client, to connect to Mosca broker with redis back-end, but after publishing binary data ( PNG image ) using mosquitto_pub tool, received data was not in correct format & size, 

but when we connect to other brokers, like [MQTT Dashboard](http://www.mqttdashboard.com/dashboard) everything works well and binary data receives correctly.  

I think that Mosca makes this data corruption, over websocket.

**Comment by NatashaShelley** [comment]
@mcollina, I am just learning all of it. Could you please clarify a couple of things: 
What defines the structure of the JSON object stored in the db:  "value" , "topic" , "options"? Is value an actual payload encoded? Sorry, if my questions are super unprofessional, I just want to understand what is going on. Thanks!

**Comment by mcollina** [comment]
@NatashaShelley don't look at what's in the db. It's for Mosca own usage :).
