### ISSUE TITLE
when client reconnect with cleansession:false,receivced last online message 

### ISSUE THREAD

**Issue by gongrui** [mcollina/mosca#128]
mosca 0.20.3
mqtt 0.3.8

first run subscriber 

subscriber.js

```
var mqtt = require('mqtt');
var client = mqtt.createClient(1883, 'localhost',{clean:false,encoding:'utf8', clientId: 'subscriber '});
client.on('connect', function(){
    client.subscribe('/foo',{qos:1});
});
client.on('message', function(topic, msg){
    console.log('Received Message:', topic, msg);
});
```

and run publish.js

```
var mqtt = require('mqtt');
var client = mqtt.createClient(1883, 'localhost',{encoding:'utf8', clientId: 'publish'});
client.on('connect', function(){
    client.publish('/foo', "123", {qos:1, retain:false});
    client.end();
});
```

the subscriber can receive message;
close the subscriber, run publish send offline message;
run subscriber second time, then subcriber can receive the offline message;

run publish send several online message. 
close the subcriber  again ,run publish send offline message,
this time when run subscriber to get offline message, it will receive the last all online message and offline message both. 

when use Mosquitto 1.2.3 alone, havn't this issue

**Comment by arvindsesha** [comment]
Not sure if this is the right Forum to post this issue, but anyways posting it to find some answers

I have a strange issue with a Mosquitto bridge on my android device connecting to Mosca on cloud.   

The scenario is that I have a MQTT client connected to the Mosquitto bridge on the Android device and another client directly connected to the Mosca broker.   When a message published through the mosca broker, the client directly connected to Mosca receives it only once [which is correct], but the client connected through the mosquitto bridge receives the same msg twice.   The QOS is set to 1 at the bridge configuration and at the clients.

The mosquitto bridge configuration is as below 

connection bridgetocloud
address Mosca-balancer-23232322323..elb.amazonaws.com:1883
topic mqtt/2/events/#  both 1 
bridge_attempt_unsubscribe false
keepalive_interval 30
start_type automatic
restart_timeout 1
try_private true

We also noticed that when the android Mosquitto is bridged with a Mosquitto set up on one of our servers, the msg delivery behaves correctly with only only one msg recieved at the MQTT client.

**Comment by mcollina** [comment]
Bridge mode is not supported #25
