### ISSUE TITLE
OAuth2 support as a plugin/wrapper

### ISSUE THREAD

**Issue by mcollina** [mcollina/mosca#136]
A really nice project will be to augment Mosca to support an OAuth2 authentication and authorization system.

It has already been done with Mosquitto in Python:
http://pzf.fremantle.org/2013/11/using-oauth-20-with-mqtt.html

**Comment by bkrajendra** [comment]
Is there any way to use Laravel Passport oAuth to use along with mosca.
Laravel Passport is PHP implementation of oAuth server. it support almost all standard oAuth implementation including token grant.
