### ISSUE TITLE
Random messages on mosca.

### ISSUE THREAD

**Issue by SudoPlz** [mcollina/mosca#138]
When I leave the server running I get random messages. 

```
Published 8204
Published 0
Published 14
Published 0
Published 14
Published 0
Published 14
Published 64946176
Published 30481168
Published 53064192
Published mosca 0.21.1
Published 2014-05-15T16:50:10.759Z
Published 2 hours
Published 0
Published 8218
Published 0
Published 14
Published 0
Published 14
Published 0
Published 14
Published 64946176
Published 30569912
Published 53064192
Published mosca 0.21.1
```

What are all those? Do they affect net data consumption or performance? Are they nessecary?

**Comment by giig982** [comment]
In Mosca 0.28, if you do not disable explicitly stats as you stated, the server keeps logging them. 
That should not be the default behavior, as stated on lib/server.js documentation.
