### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by mcollina** [mcollina/mosca#15]
It is very important that a persistent storage is added to Mosca, to support QoS 1 & 2 and retained messages.

For single-instance storage, the best candidate seems [LevelDB](https://github.com/rvagg/node-levelup), but we need a multi-db support.
We might choose https://npmjs.org/package/ueberDB or https://github.com/1602/jugglingdb.

**Comment by xianlin** [comment]
May I ask How long are messages stored on the mosca mqtt broker if using default LevelDB. is it determined by the file system size (more storage space, can store more messages)?

**Comment by mcollina** [comment]
Replied in https://github.com/mcollina/mosca/issues/276.
