### ISSUE TITLE
Authorisation using standalone methods in an embedded Mosca.

### ISSUE THREAD

**Issue by tibotiber** [mcollina/mosca#155]
Hi Matteo. Congrats for the great work on Mosca, I love it.

I am using Mosca as an embedded MQTT broker inside a sails.js application. It works great so far. I am now trying to use the authentication and authorisation features. I have seen that we can override the three all-permitting `authenticate`, `authorizePublish` and `authorizeSubscribe` methods to do so. I also saw that Mosca standalone has this fully featured with credentials.json and related CLI commands. I was hoping not to have to override the 3 methods to perform the exact same policies. Is there a way to enable the authorisation of the standalone Mosca inside an embedded Mosca? I'd wish to simply add something like `credentials: {path: 'path/to/credentials.json'}` to `moscaSettings` and get it running while using mosca CLI to add users.

Thanks for your help,
Thibaut.

**Comment by luislobo** [comment]
FYI: the link changed to https://github.com/mcollina/mosca/wiki/Authentication-&-Authorization#using-moscas-standalone-authorizer-with-an-embedded-mosca
