### ISSUE TITLE
Support MQTT topic formatting wildcards

### ISSUE THREAD

**Issue by djensen47** [mcollina/mosca#180]
http://mqtt.org/wiki/doku.php/topic_format

It seems like Mosca/MQTT.js support the "+" wildcard but the "#" wildcard does not seem to work on subscribing to a topic.

**Comment by Limoli** [comment]
I have the same problem with the command from a Paho Client:
`client.unsubscribe("$DATA/#");`

**Comment by mcollina** [comment]
Wildcards are not supported in the MQTT specification for unsubscribes: see http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718072

**Comment by psorowka** [comment]
@mcollina I don't agree to this statement. There is no exclude for wildcards in unsubscribes. The unsubscribe topic filters must match exactly the filters that were supplied when subscribing, including wildcards.

> The payload for the UNSUBSCRIBE Packet contains the list of Topic Filters that the Client wishes to unsubscribe from. The Topic Filters in an UNSUBSCRIBE packet MUST be UTF-8 encoded strings as defined in Section 1.5.3, packed contiguously [MQTT-3.10.3-1].
The Payload of an UNSUBSCRIBE packet MUST contain at least one Topic Filter. An UNSUBSCRIBE packet with no payload is a protocol violation 
> ...
> The Topic Filters (whether they contain wildcards or not) supplied in an UNSUBSCRIBE packet MUST be compared character-by-character with the current set of Topic Filters held by the Server for the Client. If any filter matches exactly then its owning Subscription is deleted, otherwise no additional processing occurs 

So probably that was the problem from @Limoli ? Did you subscribe to `$DATA/1` and `$DATA/2` and tried to unsubscribe to `$DATA/#`? *this* is not supported in MQTT

**Comment by mcollina** [comment]
@psorowka I expressed it badly but that's what I meant. The wildcards are not matched, they are compared char-by-char.
