### ISSUE TITLE
Hosting on services like modulus.io

### ISSUE THREAD

**Issue by glennjones** [mcollina/mosca#191]
I have been playing around with mosca embedded in a little node.js app locally and it works fine, but if I try to then move the app to services like modulus.io I cannot connect to the app. Cloud hosting changes the PORT to 8080, but this should be OK?

Is there any reason why this will not work?

**Comment by rahul132262** [comment]
`
[mqtt2.zip](https://github.com/mcollina/mosca/files/210029/mqtt2.zip)

In this file you see that here a file index.js that is the main mosca implementation file.And another file client.js is i create the client form server for publish some message, and inside demo_client file i subscribe the topic.That is working fine in local machine.

But i upload this code in modulus.io that is not working properly.Even i don't get any message in demo_client file

**Comment by mcollina** [comment]
You are connecting to port 1883 which is for MQTT, not MQTT over Websocket.

```js
var client = mqtt.connect('http://107.21.216.112:1883');
```

this should be

```js
var client = mqtt.connect('http://107.21.216.112:3000');
```

if your server is:

```js
var moscaSettings = {
    port: 1883,
    http: {
        port: 3000,
        bundle: true
    },
    backend: backjack
};
```

If your server is exposed on port 80, you put port 80.

**Comment by rahul132262** [comment]
Thanks for your response.I change this url as your direction.Unfortunately  I don't receive any message in my demo_client.js function.Can you elaborate the code properly

**Comment by mcollina** [comment]
I am sorry, but I have little time. This is the best I cam do, I have never
used modulus.
Il giorno lun 11 apr 2016 alle 07:52 rahul132262 <notifications@github.com>
ha scritto:

**Comment by rahul132262** [comment]
Thnaks.
