### ISSUE TITLE
Websocket not receiving mqtt messages

### ISSUE THREAD

**Issue by monteslu** [mcollina/mosca#201]
Hopefully I'm just doing something wrong, but I'm able to publish messages from websockets/pages, however I can't seem to get them to receive messages.

on the server:

``` javascript
var mosca = require('mosca');
var http = require('http');

var server = new mosca.Server({port: 1883});
var httpServ = http.createServer();

server.attachHttpServer(httpServ);

httpServ.listen(3000);
```

Client web page:

``` html
<html>
  <head>
    <script src="node_modules/mosca/public/mqtt.js"></script>
  </head>
  <body>
    <script>
      var client = mqtt.createClient(3000, 'localhost');

      client.subscribe("mqtt/demo");

      client.on("message", function(topic, payload) {
        console.log([topic, payload].join(": "));
        client.end();
      });

      client.publish("mqtt/demo", "hello from web page");
    </script>
  </body>
</html>
```

a node client trying to publish to the web page(and itself):

``` javascript
var mqtt = require('mqtt')

client = mqtt.createClient(1883, 'localhost');

client.subscribe('mqtt/demo');
client.publish('mqtt/demo', 'Hello from node client');

client.on('message', function (topic, message) {
  console.log(message);
});
```

If I fire up the web page first, it gets its own message.  Then I fire up the node client, and the web page does not receive the message.  If I reload the web page, the node client will receive the web pages's message.

**Comment by LanceCong** [comment]
Excuse me.I try your way but the Client web page not work(TypeError: mqtt.createClient is not a function),and node client work well.Should I change to another browser?recently I using the firefox.

I had try the way in [https://github.com/mcollina/mosca/wiki/MQTT-over-Websockets](url),and it don't work too.Shows the error like:Firefox can't establish a connection to the server at ws://localhost:1883/.
But the node client works well.

I need some help,thanks

**Comment by LanceCong** [comment]
I use the client from [http://mqttfx.jfx4ee.org/](url),And it works well.I counld I connect the mosca server over websocket?

**Comment by LanceCong** [comment]
ok,I finally found that I have to put a http setting into mosca's setting.

**Comment by mcollina** [comment]
Glad to hear that!!
