### ISSUE TITLE
Add subscribe function [ like server.publish(message, function(){...}); ] at Mosca broker to subscribe a client by server 

### ISSUE THREAD

**Issue by ajay67** [mcollina/mosca#209]
A application requirement needs to subscribe a client by Mosca broker at server like publish function (https://github.com/mcollina/mosca/wiki/Mosca-basic-usage#sending-data-from-mosca-to-clients). I feel this needs addition of a prototype addition in server.js alike Server.prototype.publish. I tried to do this as below but unable to understand and handle callback of “ MQTTAscoltatore.prototype.subscribe = function subscribe(topic, callback, done) { … “ . 

    Server.prototype.subscribe = function subscribe(topic, client, callback) {
    console.log("triggered server subscribe");
        var that = this;
        var logger = this.logger;

    if (typeof client === 'function') {
        callback = client;
        client = null;
    } else if (client) {
        logger = client.logger;
    }

    if (!callback) {
        callback = nop;
    }
    /*
    var newPacket = {
        topic: packet.topic,
        payload: packet.payload,
        messageId: this.generateUniqueId(),
        qos: packet.qos,
        retain: packet.retain
    };

    var opts = {
        qos: packet.qos,
        messageId: newPacket.messageId
    };

    if (client) {
        opts.clientId = client.id;
    }
    */

        var handler = function(topic, payload, options) {
                console.log('callback topic= ' + topic + "/" + payload + "/" + options);
        };

    that.ascoltatore.subscribe(
        topic,
        handler,
        function(err) {
                if(err){
                        callback(err);
                        return;
                }
 	//      that.subscribed(topic, client, function() {
                logger.debug({ topic: topic }, "subscribed to topic");
                that.emit("subscribed", topic, client);
                callback(null, true);
	//      });
        }
    );
    };

need help into this.

**Comment by hongtoushizi** [comment]
now ,
     the problem how   to  subscribe a client by Mosca broker at server like publish function   has fixed ??
I   want to use this function   very urgent . 
i now use redis . 
or ,you can tell me  another way to achieve it? very  thanks....

**Comment by hongtoushizi** [comment]
this my new code , Through this ， can  i   subscribe a client by Mosca broker at server like publish function ?
var moscaSettings = {
	type: 'mqtt',
	json: false,
	mqtt: require('mqtt'),
	host: '127.0.0.1',
	port: 1883
};
var server = new mosca.Server(moscaSettings);
server.on('ready', setup);

server.on('clientConnected', function (client) {
	console.log("client------------",client);
	console.log('client connected--------', client.id);
	client.subscribe("testtest");
//	client.handleSubscribe('aaa');
});

// fired when a message is received
server.on('published', function (packet, client) {
	console.log('packet-------',packet);
	console.log('Published----aaaa----', packet.payload);
});
// fired when a client disconnects
server.on('clientDisconnected', function (client) {
	console.log('Client Disconnected:', client.id);
});
// fired when the mqtt server is ready
function setup() {
	console.log('Mosca server is up and running')
}

**Comment by mcollina** [comment]
The good thing abut Open Source is that it is open and you do not pay for it. The bad thing about open source is that it is ready when it is ready. Given my current timeline, this will likely take some months, as I work on this stuff as a side project.

**Comment by hongtoushizi** [comment]
o ,thanks very much. i have achive it  by client.

**Comment by monteslu** [comment]
for posterity:  aedes can do what this issue was asking for:  https://github.com/mcollina/aedes#clientsubscribesubscriptions-callback
