### ISSUE TITLE
Advice for linear topic growth

### ISSUE THREAD

**Issue by jaydeep17** [mcollina/mosca#211]
Hi,

I have topics laid out in the following fashion
```
root1/user1
root1/user2
root1/user3
```

I need to have 10 such roots (i.e. root1 root2 root3 . . .) and under each root there will be user ids.
All the roots contain the same user ids.

For eg:

If root1 has
```
root1/user1
root1/user2
```

then root2 will also have
```
root2/user1
root2/user2
```
 
User ids will be in millions.

Any comments on mosca's performance ?

Or anything I should be worried about, because right now I'm in a situation where I have a chance to change the topic structure.

P.S. I use mosca with mongodb.

Thanks!

**Comment by mcollina** [comment]
I do not see issues in this almost-flat layout. How will the messages be sent? Each user sends them to its own topic? 

However, at that scale things can become tricky really quickly, so do a performance analysis on your setup. Also, take care to tune your mongo and dimension the capped collection.

Let me know if you run into issues, I can help.

**Comment by jaydeep17** [comment]
Actually the setup is that any user can send a message to any other user under any root.

And thanks for the offered help, I'll reopen this issue if i run into any problems.
