### ISSUE TITLE
Publish message into specific client from inside mosca

### ISSUE THREAD

**Issue by dhanifudin** [mcollina/mosca#214]
I need to send message into specific client, not [based on topic] (https://github.com/mcollina/mosca/wiki/Mosca-basic-usage#sending-data-from-mosca-to-clients). Is it possible to do that? how to do it? I see there're property like client.id, so I assume mosca keep this id as reference to send message. 
Thanks

**Comment by mcollina** [comment]
You are right, the broker keeps tracks of the clients in https://github.com/mcollina/mosca/blob/master/lib/server.js#L135. 

However direct publish of client is not a supported feature. You might want to call the internal forward method https://github.com/mcollina/mosca/blob/master/lib/client.js#L199.

**Comment by dhanifudin** [comment]
thanks for fast response and direction, I think the feature is out of concept pubsub paradigm. Maybe for a quick hack, I will publish message into client id as topic.

**Comment by mcollina** [comment]
I think that's the best idea, at least for now. I am doing a big refactoring, I will ping you when I have an API for this.

**Comment by xiulunlin** [comment]
@mcollina I think this API is needed for server to send a message to a specified client.

**Comment by KevinNovak** [comment]
Any updates on this? I'm in a situation where I need to send a state object to a single client when it first connects.

**Comment by flyingstarlai** [comment]
any update? i need this.. thx

**Comment by gamelaster** [comment]
Still not any update? ☹️
