### ISSUE TITLE
Mosca install error

### ISSUE THREAD

**Issue by syferadmin** [mcollina/mosca#216]
Dear Sir/Madam,
I am trying to install mosca using a jailed ssh shell but have run into an error.
node installed and runs without issue.

[s1055375~]$ echo $PATH
/home/s1055375/local/node/bin:/home/s1055375/perl5/bin:/usr/lib/courier-imap/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/home/s1055375/bin

Any help would be greatly appreciated.
Regards Grant

[s1055375~]$ npm install mosca bunyan -g
npm WARN engine amqp@0.2.3: wanted: {"node":"0.4 || 0.6 || 0.8 || 0.9 || 0.10 || 0.11"} (current: {"node":"0.12.0","npm":"2.5.1"})

> hiredis@0.1.17 install /home/s1055375/local/node/lib/node_modules/mosca/node_modules/hiredis
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  AR(target) Release/obj.target/deps/hiredis.a
  COPY Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  SOLINK_MODULE(target) Release/obj.target/hiredis.node: Finished
  COPY Release/hiredis.node
make: Leaving directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/hiredis/build'

> ws@0.6.5 install /home/s1055375/local/node/lib/node_modules/mosca/node_modules/websocket-stream/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/websocket-stream/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/websocket-stream/node_modules/ws/build'

> dtrace-provider@0.4.0 install /home/s1055375/local/node/lib/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

> ws@0.6.5 install /home/s1055375/local/node/lib/node_modules/mosca/node_modules/mqtt/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/home/s1055375/local/node/bin/bunyan -> /home/s1055375/local/node/lib/node_modules/bunyan/bin/bunyan
make: Entering directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/mqtt/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/mqtt/node_modules/ws/build'

> dtrace-provider@0.3.2 install /home/s1055375/local/node/lib/node_modules/mosca/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

> zmq@2.8.0 install /home/s1055375/local/node/lib/node_modules/mosca/node_modules/zmq
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: warning: zmq.h: No such file or directory
../binding.cc: In function 'const char* zmq::ErrorMessage()':
../binding.cc:185: error: 'zmq_errno' was not declared in this scope
../binding.cc:185: error: 'zmq_strerror' was not declared in this scope
../binding.cc: In constructor 'zmq::Context::Context(int)':
../binding.cc:237: error: 'zmq_init' was not declared in this scope
../binding.cc: In member function 'void zmq::Context::Close()':
../binding.cc:249: error: 'zmq_term' was not declared in this scope
../binding.cc: In member function 'bool zmq::Socket::IsReady()':
../binding.cc:359: error: 'zmq_pollitem_t' was not declared in this scope
../binding.cc:359: error: expected ';' before 'item'
../binding.cc:361: error: 'item' was not declared in this scope
../binding.cc:361: error: 'ZMQ_POLLOUT' was not declared in this scope
../binding.cc:363: error: 'item' was not declared in this scope
../binding.cc:363: error: 'zmq_poll' was not declared in this scope
../binding.cc: In constructor 'zmq::Socket::Socket(zmq::Context*, int)':
../binding.cc:473: error: 'zmq_socket' was not declared in this scope
../binding.cc:486: error: 'ZMQ_FD' was not declared in this scope
../binding.cc:486: error: 'zmq_getsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::GetSockOpt(int) [with T = char*]':
../binding.cc:559: error: 'zmq_getsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::SetSockOpt(int, v8::Handle<v8::Value>) [with T = char*]':
../binding.cc:575: error: 'zmq_setsockopt' was not declared in this scope
../binding.cc: In static member function 'static void zmq::Socket::GetSockOpt(const v8::FunctionCallbackInfo<v8::Value>&)':
../binding.cc:601: error: 'zmq_strerror' was not declared in this scope
../binding.cc:601: error: return-statement with a value, in function returning 'void'
../binding.cc: In static member function 'static void zmq::Socket::SetSockOpt(const v8::FunctionCallbackInfo<v8::Value>&)':
../binding.cc:625: error: 'zmq_strerror' was not declared in this scope
../binding.cc:625: error: return-statement with a value, in function returning 'void'
../binding.cc: In static member function 'static void zmq::Socket::UV_BindAsync(uv_work_t*)':
../binding.cc:675: error: 'zmq_bind' was not declared in this scope
../binding.cc:676: error: 'zmq_errno' was not declared in this scope
../binding.cc: In static member function 'static void zmq::Socket::UV_BindAsyncAfter(uv_work_t*)':
../binding.cc:686: error: 'zmq_strerror' was not declared in this scope
../binding.cc: In static member function 'static void zmq::Socket::BindSync(const v8::FunctionCallbackInfo<v8::Value>&)':
../binding.cc:713: error: 'zmq_bind' was not declared in this scope
../binding.cc: In static member function 'static void zmq::Socket::Connect(const v8::FunctionCallbackInfo<v8::Value>&)':
../binding.cc:809: error: 'zmq_connect' was not declared in this scope
../binding.cc: At global scope:
../binding.cc:860: error: expected type-specifier before 'zmq_msg_t'
../binding.cc:892: error: expected type-specifier before 'zmq_msg_t'
../binding.cc:897: error: 'zmq_msg_t' does not name a type
../binding.cc: In member function 'v8::Local<v8::Value> zmq::Socket::IncomingMessage::GetBuffer()':
../binding.cc:866: error: 'zmq_msg_data' was not declared in this scope
../binding.cc:866: error: 'zmq_msg_size' was not declared in this scope
../binding.cc: In constructor 'zmq::Socket::IncomingMessage::MessageReference::MessageReference()':
../binding.cc:883: error: 'msg_' was not declared in this scope
../binding.cc:883: error: 'zmq_msg_init' was not declared in this scope
../binding.cc: In destructor 'zmq::Socket::IncomingMessage::MessageReference::~MessageReference()':
../binding.cc:888: error: 'msg_' was not declared in this scope
../binding.cc:888: error: 'zmq_msg_close' was not declared in this scope
../binding.cc: In static member function 'static void zmq::Socket::Recv(const v8::FunctionCallbackInfo<v8::Value>&)':
../binding.cc:969: error: 'zmq_recvmsg' was not declared in this scope
../binding.cc: At global scope:
../binding.cc:997: error: expected type-specifier before 'zmq_msg_t'
../binding.cc:1029: error: 'zmq_msg_t' does not name a type
../binding.cc: In constructor 'zmq::Socket::OutgoingMessage::OutgoingMessage(v8::Handle<v8::Object>)':
../binding.cc:985: error: 'msg_' was not declared in this scope
../binding.cc:986: error: 'zmq_msg_init_data' was not declared in this scope
../binding.cc: In destructor 'zmq::Socket::OutgoingMessage::~OutgoingMessage()':
../binding.cc:993: error: 'msg_' was not declared in this scope
../binding.cc:993: error: 'zmq_msg_close' was not declared in this scope
../binding.cc: In static member function 'static void zmq::Socket::Send(const v8::FunctionCallbackInfo<v8::Value>&)':
../binding.cc:1059: error: 'zmq_msg_t' was not declared in this scope
../binding.cc:1059: error: expected ';' before 'msg'
../binding.cc:1062: error: 'msg' was not declared in this scope
../binding.cc:1062: error: 'zmq_msg_init_size' was not declared in this scope
../binding.cc:1066: error: 'zmq_msg_data' was not declared in this scope
../binding.cc:1077: error: 'zmq_msg_send' was not declared in this scope
../binding.cc: In member function 'void zmq::Socket::Close()':
../binding.cc:1095: error: 'zmq_close' was not declared in this scope
../binding.cc: In function 'void zmq::ZmqVersion(const v8::FunctionCallbackInfo<v8::Value>&)':
../binding.cc:1131: error: 'zmq_version' was not declared in this scope
../binding.cc: In function 'void zmq::Initialize(v8::Handle<v8::Object>)':
../binding.cc:1211: error: 'ZMQ_VERSION_MAJOR' was not declared in this scope
../binding.cc:1211: error: 'ZMQ_VERSION_MINOR' was not declared in this scope
../binding.cc:1212: error: 'ZMQ_VERSION_MAJOR' was not declared in this scope
../binding.cc:1212: error: 'ZMQ_VERSION_MINOR' was not declared in this scope
../binding.cc:1213: error: 'ZMQ_VERSION' was not declared in this scope
../binding.cc:1214: error: 'ZMQ_VERSION_MAJOR' was not declared in this scope
../binding.cc:1214: error: 'ZMQ_VERSION_MINOR' was not declared in this scope
../binding.cc:1215: error: 'ZMQ_PUB' was not declared in this scope
../binding.cc:1216: error: 'ZMQ_SUB' was not declared in this scope
../binding.cc:1221: error: 'ZMQ_REQ' was not declared in this scope
../binding.cc:1222: error: 'ZMQ_XREQ' was not declared in this scope
../binding.cc:1223: error: 'ZMQ_REP' was not declared in this scope
../binding.cc:1224: error: 'ZMQ_XREP' was not declared in this scope
../binding.cc:1225: error: 'ZMQ_XREQ' was not declared in this scope
../binding.cc:1226: error: 'ZMQ_XREP' was not declared in this scope
../binding.cc:1227: error: 'ZMQ_PUSH' was not declared in this scope
../binding.cc:1228: error: 'ZMQ_PULL' was not declared in this scope
../binding.cc:1229: error: 'ZMQ_PAIR' was not declared in this scope
../binding.cc:1231: error: 'ZMQ_POLLIN' was not declared in this scope
../binding.cc:1232: error: 'ZMQ_POLLOUT' was not declared in this scope
../binding.cc:1233: error: 'ZMQ_POLLERR' was not declared in this scope
../binding.cc:1235: error: 'ZMQ_SNDMORE' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::GetSockOpt(int) [with T = int]':
../binding.cc:591:   instantiated from here
../binding.cc:536: error: 'zmq_getsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::GetSockOpt(int) [with T = unsigned int]':
../binding.cc:593:   instantiated from here
../binding.cc:536: error: 'zmq_getsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::GetSockOpt(int) [with T = long int]':
../binding.cc:595:   instantiated from here
../binding.cc:536: error: 'zmq_getsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::GetSockOpt(int) [with T = long unsigned int]':
../binding.cc:597:   instantiated from here
../binding.cc:536: error: 'zmq_getsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::SetSockOpt(int, v8::Handle<v8::Value>) [with T = int]':
../binding.cc:615:   instantiated from here
../binding.cc:550: error: 'zmq_setsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::SetSockOpt(int, v8::Handle<v8::Value>) [with T = unsigned int]':
../binding.cc:617:   instantiated from here
../binding.cc:550: error: 'zmq_setsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::SetSockOpt(int, v8::Handle<v8::Value>) [with T = long int]':
../binding.cc:619:   instantiated from here
../binding.cc:550: error: 'zmq_setsockopt' was not declared in this scope
../binding.cc: In member function 'v8::Handle<v8::Value> zmq::Socket::SetSockOpt(int, v8::Handle<v8::Value>) [with T = long unsigned int]':
../binding.cc:621:   instantiated from here
../binding.cc:550: error: 'zmq_setsockopt' was not declared in this scope
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/zmq/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/s1055375/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 2.6.32-458.23.2.lve1.2.48.el6.x86_64
gyp ERR! command "node" "/home/s1055375/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
cwd /home/s1055375/local/node/lib/node_modules/mosca/node_modules/zmq
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing zmq@2.8.0

> kerberos@0.0.9 install /home/s1055375/local/node/lib/node_modules/mosca/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/s1055375/local/node/lib/node_modules/mosca/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o

**Comment by mcollina** [comment]
This output is likely truncated, because NPM does not end that way.

Anyway, I never did this kind of installation, and I cannot really help without doing it. I can say it is definitely a problem with your setup.

**Comment by syferadmin** [comment]
Hello, The first time I tried to build it never finished because of the errors (just sat there). 
The log is not complete because I hit ctrl-c after the errors.  
The procedure I followed was:
(1) Install node.js
[~]# wget http://nodejs.org/dist/v0.12.0/node-v0.12.0.tar.gz 
[~]# tar xzf node-v0.8.2.tar.gz [~]# cd node-v0.12.0 
[~]# ./configure --prefix=$HOME 
[~]# make 
[~]# make install 

(2) Modify .bash_profile
# .bash_profile
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
# User specific environment and startup programs
PATH=$PATH:$HOME/bin
export PATH=$HOME/local/node/bin:$PATH
(3) Install mosca
npm install mosca bunyan -g

Anything else I can try?
Thanks Grant

**Comment by mcollina** [comment]
All the errors you see are optional dependencies that are failing, it should be able to finish without them.
