### ISSUE TITLE
Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by davgeek** [mcollina/mosca#220]
This is the error: Error: Cannot find module './lib/ascoltatori'

Node version:  0.10.32
Npm : 1.4.28

Thanks.

**Comment by mcollina** [comment]
I would try reinstalling, this sounds like an NPM problem.
Also, try `npm install npm@latest -g`, to update NPM itself.

**Comment by davgeek** [comment]
Thanks, i fixed this error, is a server error, need more than 1gb of memory for compiling. i make a swap memory and is fine.
