### ISSUE TITLE
Starting mosca with io.js (1.3.0 and higher) results in "Cannot find module './build/Release/DTraceProviderBindings'" on OSX

### ISSUE THREAD

**Issue by gfarrell** [mcollina/mosca#221]
I'm using IO.js (this happens on 1.3.0 and 1.4.3), and when starting Mosca, I get the following error three times:

    Cannot find module './build/Release/DTraceProviderBindings'

This does not happen on IO.js (1.4.3) in a Linux VM (boot2docker) nor with Node.js 0.11.0.

**Comment by mcollina** [comment]
See #222.
