### ISSUE TITLE
Trouble connecting to Mosca Server

### ISSUE THREAD

**Issue by imp-guru** [mcollina/mosca#223]
Hi,

I'm debugging an issue with data.sparkfun.com.  This is the MQTT server code:

    var mosca = require('mosca');

    /**** instance of mosca server ****/
    exports.server = false;
    
    /**
     * create
     *
     * make a single instance of the mosca server
     * so it can be shared with every module that
     * requires it
     */
    exports.create = function(config) {
    
      if (this.server instanceof mosca.Server) {
        return this.server;
      }
    
      config = config || {
        port: 1883
      };
    
      this.server = new mosca.Server(config);

      return this.server;
    
    };

Then a browserified version of MOWS is used to connect:

    e = mows.createClient("wss://data.sparkfun.com");
    e.subscribe("output/1nZawvldLzC4E169OnG9");
    e.on("message", function(a, d) {
         consloe.log(d)
    });

But when doing so, the following error keeps on happening:
    Uncaught Error: Connection refused: Not authorized

This used to work but I stopped sometime around Nov 17th 2014.

**Comment by imp-guru** [comment]
Hmm, this might have something to do with it:
https://github.com/mcollina/mosca/commit/3c25e9ff0d8ac7c74683e6dd2d45b22420d81c20

**Comment by imp-guru** [comment]
But what about connections where a username and password are undesired?

**Comment by mcollina** [comment]
MOWS is deprecated, just use MQTT.js.

Can you please send a full example that highlight the problem?
Il giorno sab 7 mar 2015 alle 19:39 imp-guru <notifications@github.com> ha
scritto:
