### ISSUE TITLE
Mosca not working with Redis/AWS Elasticache using example setup

### ISSUE THREAD

**Issue by spidie** [mcollina/mosca#228]
Been using Mosca for a while now with Redis as a backend. Works fine in dev, but once I went into production (using Amazon Elasticache) I ran into problems.

Keep getting this error 

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/var/www/secludedconsole/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/var/www/secludedconsole/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickDomainCallback (node.js:381:11)
```
Even though my redis is not on 127.0.0.1

I've been using the example instructions from:

https://github.com/mcollina/mosca/wiki/Mosca-basic-usage#in-this-example-we-will-be-using-redis

Still not sure if it is Amazon Elasticache or just having a remote Redis, I did a port forward of the elasticache ports (you can't access it outside of AWS) to my local machine and it all works fine - so I think not.

I tracked it down by adding some debug statements - there are 4 calls to redis CreateClient, the first 2 are fine but the second 2 had a nil 3rd argument causing it to default to localhost.

The 2nd 2 calls it seems are related to this 

```
persistence: {
   factory: mosca.persistence.Redis
}
``` 

In the mosca settings.

I noticed this line didn't appear in the mongo example, so I tried removing the persistence factory, and voila! it worked.

Is this an error in the doco or is there something else going on here?
What is the effect of removing the persistence factory? Everything seems to be working for me - but haven't given it a good test yet.

**Comment by mcollina** [comment]
You should add to the persistence property the same arguments you would use to connect with node_redis.

```js
persistence: {
   factory: mosca.persistence.Redis,
   host: 'your elasticache host',
  port: 'your elasticache port'
}
```

Let me know and sorry for the late reply

**Comment by spidie** [comment]
Awesome - I'll try that out today! 
Can we update documentation, I think many would be caught out by that!

**Comment by mcollina** [comment]
Can you please update the wiki yourself, if that works for you?
Il giorno mer 1 apr 2015 alle 21:18 Steve Dalton <notifications@github.com>
ha scritto:

**Comment by spidie** [comment]
Absolutely,  didn't realise I had access.

**Comment by spidie** [comment]
I've added a note in the main example page - on further reading I can now also see it mentioned under persistence settings in https://github.com/mcollina/mosca/wiki/Mosca-advanced-usage.
