### ISSUE TITLE
HTTP + MQTT + Express

### ISSUE THREAD

**Issue by niralkalavadia** [mcollina/mosca#233]
Hello,

I am using express and mosca in my project. I have developed REST API using express. I am starting HTTP and MQTT server from server.js. When specific rest url (HTTP) request received, server route it to other .js file. This file extract parameter and then it has to publish it to MQTT client. I am facing problem with last part i.e publish data from the .js file.

In server.js:

    var data = require('./routes/data.js');

    app.get('/data/:a/:b', data.data);

    var server = new mosca.Server(moscaSettings);   // Starting mosca

    http.createServer(app).listen(app.get('port'), function () {
    console.log('Express server listening on port ' + app.get('port'));
    }); // Starting HTTP client

in data.js:

    exports.data = function (req, res) {
        var data = { 
            "Data": {
                "a": req.params.a,
                "b": req.params.b
            }
        };
        
    res.send(data);
    //! Here I need to publish data to MQTT Client.
    };

How to achieve this?

**Comment by mcollina** [comment]
Rewrite data.js as:


```
module.exports= function build(server) {
return function publish(req, res) {
    var data = { 
        "Data": {
            "a": req.params.a,
            "b": req.params.b
        }
    };

res.send(data);
server.publish({ topic: "mytopic", payload: "mypayload" } );
};

```

**Comment by niralkalavadia** [comment]
I have rewrote data.js as you said. when I request url as "localhost:1337/data/9/10" it generates following error..

TypeError: Cannot read property 'publish' of undefined at publish <path of data.js> at callbacks <path of index.js>

I have index.js file as below. (./routes/index.js)

    exports.index = function (req, res) {
        res.render('index', { title: 'Express' });
    };

**Comment by mcollina** [comment]
How are you embedding that file? Are you passing the broker?

**Comment by niralkalavadia** [comment]
I have put data.js file inside routes directory.

server.js:

    var data = require('./routes/data.js');    // Dependencie

    app.get('/data/:a/:b', data.call(server));    // execute for url : localhost:8080/data/9/10

when client request localhost:8080/data/9/10, request is route to data.js. This is how I am embedding data.js file. Am I doing anything wrong? What is recommended way of embedding this file?

**Comment by mcollina** [comment]
you should replace:

```js
var data = require('./routes/data.js');    // Dependencie

app.get('/data/:a/:b', data.call(server));    // execute for url : localhost:8080/data/9/10
```

with

```js
var data = require('./routes/data.js');    // Dependencie

app.get('/data/:a/:b', data(server));    // execute for url : localhost:8080/data/9/10
```

I would suggest you to buy a node.js book or to follow one of the many (free) node.js course online.
