### ISSUE TITLE
dynamic permission for topic

### ISSUE THREAD

**Issue by Jxck** [mcollina/mosca#238]
## Problem

mosca has a hook point for pub/sub

- #authorizePublish
- #authorizeSubscribe

but, this hooks only first time.

for example, if A subscribe '/A' and wanna allow subscribe only for A.
it's possible with authorizeSubscribe and deny subscribe by other user after A adding permission.

but, if X subscribes '/#' before A subscribes '/A'.
X also subscribe '/A'. because this API doesn't update X's permission.

## Suggestion

to enable '/A' only subscribable for A,
broker need to have hook point for ever pub/sub not only first time.
it will be a `filter` like api for pub/sub between broker and client.
I wanna this API for all pub/sub message, and happy to contribute that
if you interested in this API.

thanks for your great work :)

**Comment by mcollina** [comment]
I'm kind of against this for performance reason, but I see your point. It should be a feature that is available, and then use it if needed.

**Comment by Jxck** [comment]
> performance reason
yes. and I think performance is trade-off with useful features.
so, I wanna use that on my own responsibility.

adding a hook point for publish/subscribe will help to design a dynamic permission.

**Comment by mcollina** [comment]
On second thought, this functionality is already there, just override https://github.com/mcollina/mosca/blob/master/lib/server.js#L395-L407.

**Comment by Jxck** [comment]
oh it's seems work for me.
thanks !
