### ISSUE TITLE
support for durable subscription/topics?

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#239]
How can I achieve this? or should I use `mosquitto` ?

**Comment by mcollina** [comment]
I'm not exactly sure what you mean, but Mosca has full QoS 1 support.

**Comment by behrad** [comment]
I ment true exact-once semantics.. (QoS 2)
dya know any open source broker that supports this? @mcollina

**Comment by mcollina** [comment]
QoS 1 supports offline mode, so it is durable.

The only one that support QoS 2 and it is OSS is mosquitto.

Anyway, QoS 2 is in the works here too #115.

**Comment by behrad** [comment]
great :+1:

**Comment by behrad** [comment]
@mcollina any samples that shows where should I pass `clean: false` to achive QoS 1?
and with which backends that will work?

found nothing in the docs..

**Comment by mcollina** [comment]
All backends works, and offline is enabled by default on Redis and MongoDB. I recommend to use Redis as a backend and persistence component, as it gives the best tradeoff.

You need to pass `clean: false` in the client, in the broker everything is already handled for you.

**Comment by behrad** [comment]
great... can you point me to the code where redis component is handling offline?

Eager to know if you are using a sort of redis `RPUSH`, and `BLPOP` to mimic durable subscribers, since redis has not durable subscriber support :)

**Comment by mcollina** [comment]
All that durable support is done here: https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js.

It does not use `RPUSH` and `BLPOP`, have a look at the implementation and let me know!

**Comment by behrad** [comment]
a `list` for each client subscription, detecting if isOffline and `storeOffline` with `lpush`
when subscriber is ready, `streamOffline` to him by `lrange 0, 10000`

**Comment by mcollina** [comment]
:)

**Comment by behrad** [comment]
I added credentials to my mosca, but couldn't find an authentication sample client :(

sorry for too much asking ;)

**Comment by mcollina** [comment]
This is a sample client (part of the CLI tools in MQTT.js): https://github.com/mqttjs/MQTT.js/blob/master/bin/pub.js

if you pass an username and password options, these will be sent to the browser.
