### ISSUE TITLE
Channel Scalability

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#240]
I want to ask if MQTT or the mosca implementation either could be bottleneck in high number of channels? (10m, 50m, ...) I have a per device/user channel, and each user's events goes into their private channel, so I have many million channels but each channel is very low traffic.

I'd really like to hear your comments @mcollina :) and thank you for you nice works

**Comment by mcollina** [comment]
The number of channels is not a scalability bottleneck, as it uses the same data structure that RabbitMQ is using, a [Trie](https://www.rabbitmq.com/blog/tag/trie/). You can see the implementation at https://www.npmjs.com/package/qlobber.

**Comment by behrad** [comment]
:+1: WoW, interesting stuff
