### ISSUE TITLE
how i can publish message in server 

### ISSUE THREAD

**Issue by hongtoushizi** [mcollina/mosca#241]
I want to achieve this effect，like this  :  
var server = new mosca.Server(moscaSettings);
server.publish('96',"hello");

?
can I?
you say subscribe is can not.
but  "publish "  can ???  (mqtt.js is ok)

**Comment by hongtoushizi** [comment]
i want to use to use this to achive offline message ？or,can you tell me what to do when i use mosca?

**Comment by mcollina** [comment]
You should do:

```
server.publish({
  topic: 'hello',
  payload: new Buffer('world'),
  qos: 1 // this is important for offline messaging
}, null, function done() {})
```
