### ISSUE TITLE
MQTT payload format issue using mongdb for persistence

### ISSUE THREAD

**Issue by xadh00m** [mcollina/mosca#242]
Hi,

I´m observing a payload format issue when using ponte to PUT topics with curl. I´ve setup ponte/mosca using an external mongodb for persistence. When using mosquitto_pub to publish a retained topic the resulting document in mongodb looks like this:
```
mosquitto_pub -h http://ponte.myserver -t hello -m "world" -r

// in mongodb
{ "_id" : ObjectId("55301b7fa3ff3b511c392f35"), "topic" : "hello", "payload" : BinData(0,"d29ybGQ="), "messageId" : "N1gwLtptb", "qos" : 0, "retain" : true }
```
When I use curl the document looks like this:
```
curl -X PUT --data-binary 'world' http://ponte.myserver/resources/hello

// in mongodb
{ "_id" : ObjectId("55301b7fa3ff3b511c392f35"), "topic" : "hello", "payload" : "world", "retain" : true }
```
Eventually I have an MQTT.js websocket client subscribed on that topic. If the topic has been set with curl the client receives an empty uint8[] array instead of the payload on subscription.

Do I have to configure mosca/ponte to retain payloads as binary? I installed ponte from npm which still depends on:
```
"mosca": "~0.26.2",
"ascoltatori": "~0.18.0"
```
Should I update these dependencies first?

Regards,
Mirko

**Comment by mcollina** [comment]
I think the bug is in Ponte, and in particular this line: https://github.com/eclipse/ponte/blob/master/lib/http.js#L144.

Would you like to send a PR there, also updating the dependencies?

Thanks!
