### ISSUE TITLE
Listening for mqtt events

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#243]
I want to persist/log mqtt events, and their status (acked/not acked/ttl expired) in my application. How can I achieve this in mosca or ascoltatori ?
Any callbacks to listen? pipe logs? ...?

**Comment by mcollina** [comment]
All events are documented in the wiki and in the code.
That level of logging is usually not exposed, mainly because it's a huge performance overhead.
Why do you need it, anyway?

**Comment by behrad** [comment]
want to report how many messages (total/delivered/expired) each user published.

**Comment by mcollina** [comment]
All the expiring thing is out of Mosca and usually handled by the db, so there are no events.
You  can listen to the messages being published in the `authorizeForward` method in the server.

**Comment by behrad** [comment]
how about separation of delivered/undelivered messages? can I listen for acks?

The black point for me is that, 
1) should I persist messages into another external db and roll our own business logic on it 
OR
2) use (and depend/account) the internal data/msgs  mosca stores !? I don't think it is a good practice to store delivered messages with large lifetimes. hm?

**Comment by mcollina** [comment]
Mosca does not offer this functionality. However it is an interesting feature request, so I will leave this issue open. At some point I may have time to code it.

If you want to contribute a PR, I am willing to review it.

**Comment by behrad** [comment]
I'll be more than happy to contribute, however can't see the resolution/specification of this yet... Can you suggest what'd be better to come out from this?

**Comment by mcollina** [comment]
I have currently no time to put my mind into this issue. Please make a proposal :).

**Comment by behrad** [comment]
my first change was adding a `delivered` (ack received) by adding this line: 

```js
that.server.emit("delivered", this.inflight[packet.messageId], that);
```

after https://github.com/mcollina/mosca/blob/master/lib/client.js#L351

this way mosca clients now can do:

```js
server.on('delivered', function(packet, client) {
  console.log( "================= MSG %j delivered to %s ", packet, client.id );
});
```

I can create a PR if you are ok with it @mcollina

**Comment by mcollina** [comment]
that's great, please go ahead and send a PR. Remember to add a unit test
for this feature.
Il giorno sab 2 mag 2015 alle 11:22 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
@mcollina I'm having trouble with this testcase I've written:
```js
it("should emit an event for puback of each published packet", function(done) {
    buildAndConnect(done, function(client) {

      var clientId = client.opts.clientId;
      var messageId = Math.floor(65535 * Math.random());

      var subscriptions = [{
        topic: "hello",
        qos: 1
      }];

      instance.on("delivered", function(packet, serverClient) {
        expect(packet.topic).to.be.equal("hello");
        expect(packet.payload.toString().toString()).to.be.equal("some data");
        expect(serverClient.id).to.be.equal(clientId);
        client.disconnect();
      });

      instance.on("subscribed", function(topic, serverClient) {
        client.publish({
          topic: "hello",
          payload: "some data"
        });
      });

      client.subscribe({
        subscriptions: subscriptions,
        messageId: messageId
      });

    });
  });
```
it seems published message nevers gets to subscribed client and so delivered is never called, seems I'm not comfortable with mosca's test DSL yet, or put it in a bad place `abstract_server.js` !?

**Comment by mcollina** [comment]
Which error are you getting? Can you send a PR so I can review your code? (Even if it doesn't work right now, it helps collaboration!)

**Comment by behrad** [comment]
test times out since the callback is never called, will create a PR just now

**Comment by behrad** [comment]
how can I force commit? npm tests prevent my commit @mcollina
