### ISSUE TITLE
Persist retained messages in Mongodb from external Mosquitto server

### ISSUE THREAD

**Issue by xadh00m** [mcollina/mosca#245]
Hi,

I´ve setup mosca (via ponte) to use my external mosquitto server and mongodb. When I use ponte to publish a message it is persisted in the database correctly and published to the mosquitto broker correctly.
But when I publish a message (retained) to mosquitto directly the database does not update. Is this a configuration issue? My configuration looks like this:

```
module.exports = {
  persistence: {
    type: "mongo",
    url: "mongodb://MONGODB:" + process.env.MONGODB_PORT_27017_TCP_PORT
  },
  broker: {
    type: "mqtt",
    json: false,
    port: "1883",
    host: <broker_url>
  },
  http: {
    port: 3000,
    bundle: true
  },
  logger: {
    level: 10, // 10==trace, 20==debug, info==30, warn==40, error==50, fatal==60
    name: "PonteLogger"
  }
};
```

**Comment by mcollina** [comment]
No it is not. If you want the messages to be stored in Mosca/Ponte before going to Mosquitto, all traffic needs to pass through Mosca/Ponte. The only solution I can think of is to have a subscriber that stores all retained messages in the persistence. Would you like to contribute this code to Ponte or Mosca?

**Comment by xadh00m** [comment]
Thank you for the quick answer. I see the design decision behind it. I´m not sure if such a subscriber approach should be part of mosca/ponte. If I understand the protocol correctly this would mean to subscribe to e.g. Mosquitto when ponte/mosca connects initially with a root wildcard. If the broker would hold a significant amount of retained messages it would flood ponte/mosca. Additionally it would be necessary to clear the database beforehand to ensure that old retained topics which have been removed from the broker while ponte/mosca was offline are not kept forever.

**Comment by mcollina** [comment]
Yes, exactly.
Il giorno mer 22 apr 2015 alle 09:32 Mirko Geissler <
notifications@github.com> ha scritto:

**Comment by xadh00m** [comment]
The only reason we want to use Mosquitto as external broker is the support for QoS 2. I´ll need to check back how we proceed and how hard the requirements are.
