### ISSUE TITLE
Custom puback

### ISSUE THREAD

**Issue by houssine91** [mcollina/mosca#247]
I want to change the broker so that published messages  with qos 1 will have a personalized puback.
 Can you please tell me where I can change the puback, I searched and Client.js server.js but I do not get it.

**Comment by mcollina** [comment]
Sorry, it's not clear what you want to achieve, a PUBACK in MQTT contains only a messageId.
What do you want to achieve?

**Comment by houssine91** [comment]
I want to return some informations after the published message is saved, for example message's receipt date.

**Comment by mcollina** [comment]
This is not possible with MQTT. You can extend Mosca to send this data on another topic if you want to, it's really easy.

**Comment by houssine91** [comment]
yes that's what I think do, thank you.
