### ISSUE TITLE
How to make ponte connect to existing Mosquitto broker? EADDRINUSE error

### ISSUE THREAD

**Issue by KrishnaPG** [mcollina/mosca#251]
Could not find 'issues' section under ponte project - hence posting the question here.

I have Mosquitto running on default 1883 port. I need to bridge this Mosquitto to http through Ponte.

If I try this below config with ponte it fails with EADDRINUSE error:
````
module.exports = {
  persistence: {    
    type: "mongo",
    url: "mongodb://<mongodb address>"
  },
  broker: {
    type: "mqtt",
    port: "1883",
    host: "localhost"
  },
  http: {
    port: 3000,
    bundle: true
  }
};

````
If I change the port section of mqtt to be something other, say 2883, it works fine. But it is starting a different broker altogether and the client / publishers have to explicitly connect to this 2883 port, which means messages posted to 'mosquitto' broker are not coming to ponte or vice-versa.

What is the configuration to use if I want Ponte to connect to existing Mosquitto and not create a separate mqtt broker?

**Comment by KrishnaPG** [comment]
Changed the 'bundled' option of `http` to be false. Still no result. I can see the mosquitto log showing the connection from ponte, but it is immediately getting terminated with socket error.
````
1431147639: New client connected from 127.0.0.1 as mqttjs_3f629e617d5c39fd (c1, k3000).
1431147645: Socket error on client mqttjs_3f629e617d5c39fd, disconnecting.

````
Where can we see which port is causing this EADDRINUSE problem with ponte?

**Comment by mcollina** [comment]
If you have Mosquitto running, it's probably 1883, Mosquitto. You should change the `port` in the `broker` config to something like `2883`. This is good article explaining how to get which process is listening on a port on Linux http://www.cyberciti.biz/faq/what-process-has-open-linux-port/. You can find similar things on the web for Mac OS X.

**Comment by KrishnaPG** [comment]
Thank you @mcollina .

As indicated in the original post, 
>If I change the port section of mqtt to be something other, say 2883, it works fine. But it is starting a different broker altogether and the client / publishers have to explicitly connect to this 2883 port, which means messages posted to 'mosquitto' broker are not coming to ponte or vice-versa.

Hence the question: What is the configuration to use if I want Ponte to connect to existing Mosquitto and not create a separate mqtt broker?

**Comment by mcollina** [comment]
That's not possible, as it needs to intercepts the messages.
