### ISSUE TITLE
maxInflightMessages !?

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#252]
What exactly should be broker's behavior on `maxInflightMessages`?
I considered this means to drop all further messages after subscription's offline maxInflightMessages reached, but mosca seems to disconnect the client:

Why the client is being closed here? https://github.com/mcollina/mosca/blob/master/lib/client.js#L231

I think it could simply not to forward later messages in offline! or better than that:
handle `maxInflightMessages` when storing into offline messages, later also helps the backend/storage not to shirink and being controlled by `maxInflightMessages`

**Comment by mcollina** [comment]
I know about this issue, however Mosca accepts all messages from a client, and the only thing that it can do it is to kill the client if it is sending too much. I am working on a complete rewrite of Mosca to address these problems, but that will come much later this year. The codebase is in http://github.com/mcollina/aedes.
