### ISSUE TITLE
Accepting a reconnect from the same clientId

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#253]
when same clientId tries to connect to mosca, and there already exists a connected client here (https://github.com/mcollina/mosca/blob/master/lib/client.js#L335), this line
`that.server.clients[that.id].close(completeConnection);`

causes client to enter a connect/disconnect loop :(

changing above to 
`that.server.clients[that.id].close(/*completeConnection*/);`

helped that not to happen, but I'm not sure this is the correct logic :) it seems there might be a race between `closing old client` which should be `that.server.clients[that.id]` and `completeConnection`... hm !?

**Comment by behrad** [comment]
this temporary happens when working/debugging on clients... so it is a robustness must for mosca to recover from different client/non client failures..  I can help to fix this @mcollina

**Comment by mcollina** [comment]
That is how MQTT spec says it should work, basically if a client with the same clientId connects, the old one needs to be disconnected.

**Comment by behrad** [comment]
Oh my first post had markup problems... fixed that :)

Then I'll look into `that.server.clients[that.id].close(completeConnection);` to see why client drops in a connect/disconnect-by-mosca loop :)

**Comment by behrad** [comment]
had changed that line to 
```js
that.server.clients[that.id].close( function(){
    setTimeout( function(){
      completeConnection();
    }, 1000 );
});
```
and seems we have no problems during this 2 weeks :)

Does it feel logical if it is a race between `close` and `completeConnection`?

**Comment by mcollina** [comment]
Can be. Would you mind sending in a PR?
Il giorno sab 30 mag 2015 alle 15:29 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
why not, but I don't think setTimeout is a beautiful workaround, can we use promises or you suggest a better one?

**Comment by mcollina** [comment]
Can you add also a test? ;)
Il giorno dom 31 mag 2015 alle 05:22 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
busy these days, but I'll try to..

**Comment by behrad** [comment]
debugged more deeply, the loop is because of both active clients trying to `reconnect` after being disconnected by Mosca, and at low `reconnectPeriods` is felt as a connect loop :)

So this is a connect loop that can be happened by the current MQTT spec when two live clients with the same clientId are connected!

**Comment by behrad** [comment]
closing this since I was unable to generate this with one live client of the same clientId
