### ISSUE TITLE
Confused with standalone and save data to mongodb 

### ISSUE THREAD

**Issue by dogrocker** [mcollina/mosca#256]
Hello, I have use Mosca and Ponte.

I try to publish temperature from sensor to mosca it work very well, But I need to save it to the MongoDB
to make a graph. 

So I try to config.js and run `ponte -v -c config.js | bunyan`

with this config

```
module.exports = {
  persistence: {
    // same as http://mcollina.github.io/mosca/docs/lib/persistence/mongo.js.html
    type: "mongo",
    url: "mongodb://localhost:27017/ponte"
  },
  broker: {
    // same as https://github.com/mcollina/ascoltatori#mongodb
    type: "mongo",
    url: "mongodb://localhost:27017/ponte"
  },
  logger: {
    level: 30, // or 20 or 40
    name: "MongoPonte"
  },
}
```

and it work but I when I publish data to some topic `room/temp` data `15` I can fine it in `pubsub` collection but can't read the data because type is binary and some minute it auto delete my data.

So I very confused with, How to save time series of data from MQTT to MongoDB?

**Comment by mcollina** [comment]
The `pubsub` collection is a capped collection, and it is used by Mosca and Ponte to communicate between the various instances, i.e. to scale. That collection is not meant for persistent storage, so you need to roll your solution. 

In Ponte, you would have to react to the `updated` event, as shown in the README. In Mosca, it is the `published` event.

**Comment by dogrocker** [comment]
OK, Thank you @mcollina.
