### ISSUE TITLE
How to detect client offline when client drop their internet connection or shutdown ?

### ISSUE THREAD

**Issue by tinamore** [mcollina/mosca#258]
Hi.
Current, Mosca fire clientDisconnected when client send command Disconnected to mosca Broker.

Is there any way to mosca detect offline client in an intelligent way (Ex: client drop their internet connection or shutdown)?

Can the mosca will ping and client pong back on cycles to detect client offline and offline event firing.

**Comment by mcollina** [comment]
Mosca detects offline in an intelligent way, but this is not exposed to the end user. Would you like to submit a PR to add that functionality? 

This is the relevant method: https://github.com/mcollina/mosca/blob/master/lib/client.js#L502-L519

**Comment by tinamore** [comment]
Hi
Can you add method function for end user Configure limit the number of not pong of client (EX: ESP8266) when server ping for detect offline.

Example: Mosca broker will ping (Publish message to client mqtt) every 2 second when client begin connected to broker, When receiving a ping from the broker then client will pong back (Publish message pong back), if client not pong 5 times (device offline 10 second), Mosca fire offline trigger, If client pong back, mosca will detect client online again.

This has implications in the iOT, if the device is offline in the list, the user will have to check the device crash and reboot the device to ensure reliability.

**Comment by psorowka** [comment]
This is requires a heartbeat protocol also implemented in the client. This is an application layer demand you can easily implement yourself on top of mqtt and therefore respect your specific requirements.

**Comment by mcollina** [comment]
Mosca follows the MQTT 3.1.1 standard, have a look how it's handled there!
Il giorno lun 25 mag 2015 alle 14:52 Peter Sorowka <notifications@github.com>
ha scritto:
