### ISSUE TITLE
Redis Scalability

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#263]
I want to cluster on top of redis (both backend and persistence), is there anything in-memory within mosca or something I should take care of? or simply scale up/out.

I tried to reach 50K mqtt subscribed clients (via mqtt.js) but felt some unstablities on my single node embedded mosca (1 process)

Nodejs process takes 100% CPU and no response from mosca...

**Comment by mcollina** [comment]
Are you already using redis? How many messages are transiting through?
Il giorno sab 30 mag 2015 alle 15:39 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
yes @mcollina , all subscribes subscribe to two topics:
1. $SYS/#/clients/connected with qos:0
2. app/adp-nms-push/user/stress with qos:1 (this topic is empty, no published messages)

no publishers...
I have two listeners on `server.clientConnected` and `server.clientDisconnected` which do a single mongo update each :)

after 30K connections, mosca node process sticks to 100% core usage :(

**Comment by behrad** [comment]
both mosca backend and persistence is on Redis, I'm using mongo for my Rest API :)

**Comment by mcollina** [comment]
What's the keepalive? Can you attach a script to reproduce?
Il giorno dom 31 mag 2015 alle 05:25 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
it is mqttjs default value (which I don't know how much it is).

my code is as simple as this:
```js
function newClient( i ) {
  var client  = mqtt.connect(
    'mqtt://'+config.broker.user+':'+config.broker.pass +'@'+config.broker.host+':' + config.broker.port,
    {clientId: 'mqtt-stress-client-'+i }
  );
  client.on('connect', function () {
    client.subscribe({
      '$SYS/#/clients2/connected': 0, // changed this to an invalid topic to prevent stats push load
      'app/adp-nms-push/user/stress': 1
    }, function(err, subs){
      console.log( "Subscribed to `%s`",  err || '', subs[0], subs[1] );
    });
  });
  client.on('message', function (topic, message/*as Buffer*/) {
    console.log('%s: %s', topic, message.toString());
  });
  client.on( 'error', function( err ) {
    console.error( err );
  });

}


var numberOfClients = process.argv[2] || 1;
for( var i=1; i<=numberOfClients; i++ ) {
  (function(i){
    setTimeout( function(){
      newClient( i + Date.now() );
    }, i * 100 );
  })(i);
}
```

**Comment by behrad** [comment]
I am seeing constantly 50% of core usage with 20K clients of above code! I expected to it be idle... What may be mosca doing?

**Comment by mcollina** [comment]
Are you running that code on the same machine? How is Mosca configured?
Which os, and how is the network stack configured?
Are all devices connected successfully? Checking the auth credentials is
CPU intesive.

My best deployment (on Mongo), currently handles 1GB every half an hour. We
use two instances in HA behind a load balancer.

I think the keepalive might be 10s in mqttjs, which means roughly 2000
packets/s for doing nothing.

To address these issues (and adding more features), I am rewriting Mosca,
the new one will be much more lightweight. You can give it a spin at
http://github.com/mcollina/aedes.

Anyway, can you please check in the logs of Mosca? It is pretty chatty if
you enable info or debug, you can probably track down what is happening.

Il giorno dom 31 mag 2015 alle 17:08 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
I'm planning mosca for production @mcollina , aedes is currently far from production. 
I increase `keepAlive` to 60 which is more real-world I think.

> Are you running that code on the same machine?

Yes


> How is Mosca configured?

```js
var moscaSettings = {
    id: [require('os').hostname(),process.pid].join('-'),
    port: config.broker.port || 1883,
    stats: config.broker.stats,
    logger: {
      level: config.broker.logger.level
    },
    mqtt_credentials: __dirname + "/../mqtt_credentials.json",
    http: {
      port: config.broker.http.port || 1884,
      bundle: config.broker.http.bundle,
      static: config.broker.http.static
    },
    //maxInflightMessages: 10, currently isn't working in mosca!
    backend: {
      type: 'redis',
      redis: require('redis'),
      host: "localhost",
      port: 6379,
      return_buffers: true // to handle binary payloads
    },
    persistence: {
      factory: mosca.persistence.Redis,
      channel: 'moscaSync2',
      ttl: {
        packets: 24 * 60 * 60 * 1000,
        subscriptions: 30 * 24 * 60 * 60 * 1000
      }
    }
  };
```



> Which os, and how is the network stack configured?

we have both Ubuntu 14 and Centos 7 servers. aside `ulimit` I've not tweaked any kernel/network parameters. Do you recommend any sysctl/network settings?


> Are all devices connected successfully? Checking the auth credentials is
> CPU intesive.

Yes If I've not dropped something in logs... authentication handler is the same as I provided you before (picked up from mosca's wiki)



> currently handles 1GB every half an hour

what dya mean by 1GB? message payload bandwidth?



> We
> use two instances in HA behind a load balancer.

haproxy? or Nginx? 

Have you tested offloading SSL on them? I don't think we should put SSL on Mosca :)

**Comment by mcollina** [comment]
The normal kernel settings are not suitable for handling lots of
connections. My fear (giving your pattern), is that a lot of clients are
not connecting properly or gets disconneted, and then they go through an
auth cycle again.
Try disabling the auth, and see if if that's the case.

Here are my settings for a machine with 8GB RAM:

net.core.rmem_default 536870912

net.core.wmem_default 536870912

net.core.rmem_max 536870912

net.core.wmem_max 536870912

net.core.netdev_max backlog 100000

net.ipv4.tcp_rmem 4096 16384 33554432

net.ipv4.tcp_wmem 4096 16384 33554432

net.ipv4.tcp_mem 786432 1048576 26777216

net.ipv4.tcp_max_tw buckets 360000

net.ipv4.tcp_max_syn backlog 10000

vm.min_free kbytes 65536

vm.swappiness 0

net.core.somaxconn 100000


Which version of node/io are you running? Best results are with the latest
iojs (I released an updated version that runs there 2 days ago).

As 1GB is the total payload size transfered in half an our.
Il giorno dom 31 mag 2015 alle 17:51 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
> Try disabling the auth, and see if if that's the case

Oh, forgot to say that auth is currently disabled.


> Which version of node/io are you running? Best results are with the latest
> iojs (I released an updated version that runs there 2 days ago).

`node 0.10.38`

very valuable information provided in this topic @mcollina great :+1: 

and can you also comment on my SSL offloading please?

**Comment by mcollina** [comment]
I don't use SSL in Mosca at all, all offloaded in the load balancer.

Use iojs v2, you will probably see between 50% to 100% perf increase.
Il giorno dom 31 mag 2015 alle 18:23 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
> I don't use SSL in Mosca at all, all offloaded in the load balancer.

Are you using ha-proxy? or nginx?



> Use iojs v2, you will probably see between 50% to 100% perf increase.

WoW! great, cause of latest v8 improvements...? I should test it then

**Comment by mcollina** [comment]
I used Haproxy, ELB and the Azure one. All great, just use one. Ngnix with
tcp is not good.
Il giorno dom 31 mag 2015 alle 18:41 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
perfect, I should first use cluster to scale up and then Haproxy to scale out :)

**Comment by behrad** [comment]
it seems Mosca is keeping busy handling client's `pingreg`s, in debug mosca log I found

```
2015-06-01T09:53:34.926Z pid:4550 worker:1 {"name":"mosca","hostname":"behrad","pid":4550,"client":"mqtt-stress-client-1433152055460","level":20,"msg":"pingreq","time":"2015-06-01T09:53:34.925Z","v":0}
2015-06-01T09:53:34.926Z pid:4550 worker:1 {"name":"mosca","hostname":"behrad","pid":4550,"client":"mqtt-stress-client-1433152055460","level":20,"timeout":90000,"msg":"setting keepalive timeout","time":"2015-06-01T09:53:34.925Z","v":0}

```

**Comment by behrad** [comment]
@mcollina I could get to 65639 concurrent clients (keepalive=300) with around 2% cpu usage on a 12core machine (12G RAM) with your sysctl settings... however server is not accepting any new connections... even telnet to the machine hangs!!!

```
telnet 192.168.100.32 8883
Trying 192.168.100.32...
```

**Comment by mcollina** [comment]
Wooow! That's good. Probably there is one more setting to tweak, because 65639 seems like to close to a constant. What's your ulimit?

BTW, the telnet thing is perfectly normal, the kernel could not create any more sockets.

**Comment by behrad** [comment]
seems the answer was `net.netfilter.nf_conntrack_max`, should Mosca be able to handle +100K connections on proper hardware?

**Comment by mcollina** [comment]
Probably, never put it that far, I brought it to 50K.

Anyway, can you please post your network tuning? So that we keep track of
all of it.

Let me know how it goes in regard of messages and so on.

What do you use to simulate that load?

Il giorno dom 14 giu 2015 alle ore 20:42 Behrad <notifications@github.com>
ha scritto:

**Comment by behrad** [comment]
stuck in `83242` this time :( nothing appears in /var/log/messages... 2G free -m memory.

Dya mean tunings other than sysctl?

I'm using simple mqttjs in node.js client processes ;)

**Comment by mcollina** [comment]
Probably it's the network memory? Can you ssh in there?

Can you please share the script to spawn all those?

Or maybe is the clients VM that needs tuning?
Il giorno dom 14 giu 2015 alle 22:22 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
I guess it should be net memory... lets decrease memory options. 
I ssh, machine is normal, free -m shows 2G free memory...

```js
for( var i=0; i<numberOfClients; i+=1 ) {
  (function(i){
    setTimeout( function(){
      newClient( base + i, prefix );
    }, j * 50 );
  })(i);

//where newClient is

var client  = mqtt.connect( url, {
      clientId: clientId,
      keepalive: config.keepalive,
      reconnectPeriod: config.reconnectPeriod
  });

  client.on('connect', function () {
    client.subscribe(topics, function(err, subs){ //each client subscribes to one qos1 topic
      console.log( "Subscribed to `%s`",  err || '', subs[0], subs[1] );
    });
  });
```

I run multiple processes each with numberOfClients=10000.

**Comment by behrad** [comment]
it was my client reaching its 60k on its ip :) however decreasing net memory as below
```
net.core.rmem_default = 33554432
net.core.wmem_default = 33554432
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.ipv4.tcp_rmem = 4096	4096	16777216
net.core.netdev_max_backlog = 2500
net.core.somaxconn = 1024
net.netfilter.nf_conntrack_max = 1000000
```
improved processes overall memory usage as you can see below:

![screen shot 2015-06-15 at 4 10 13 am](https://cloud.githubusercontent.com/assets/2151889/8151003/25962bdc-1315-11e5-9f02-1be0eff5684a.png)

machine is at 3% cpu usage with keepalive 300

**Comment by mcollina** [comment]
Great!!! :dancer:

You should write a blog post about all this!!

**Comment by behrad** [comment]
:+1: sure, when I find some free time

**Comment by ihsenCh** [comment]
Can you please tell  which tool have you been using to see graphs of connected clients , memory usage and so on? Thank you
