### ISSUE TITLE
Retained messages with embedded mosca

### ISSUE THREAD

**Issue by doofmars** [mcollina/mosca#264]
I ran into an problem with my embedded mosca broker.
The retained messages will not get retained.
The sending and receiving of messages works.

I can see that the broker receives the retained message with the retained flag set to true via the ```broker.on('published')``` hook. But when I subscribe to an topic I will not get the previously retained message.

I have tested different clients (paho, mqtt.js and hivemq) and finally switched to another broker (hivemq) which supports the retained messages.

To eventually help with this issue I have setup an yeoman angular-fullstack project which can be found here: https://github.com/doofmars/mosca-retained-test the mosca setup is in ![server/mosca](https://github.com/doofmars/mosca-retained-test/tree/master/server/mosca) and is initialized in server/app.js.

The client part can be found in [client/app/main/main.controller.js](https://github.com/doofmars/mosca-retained-test/blob/master/client/app/main/main.controller.js)
I am using mongo db.

**Comment by mcollina** [comment]
Retained messages are supported, but you need to add a persistence, as
specified in the docs/wiki.
Il giorno dom 31 mag 2015 alle 01:01 doofmars <notifications@github.com> ha
scritto:

**Comment by doofmars** [comment]
Ok, thanks I managed to get it working.
But find the instructions on https://github.com/mcollina/mosca/wiki/Persistence-support confusing.
For instance what dose "it needs to be explicitly wired up" mean?

For my example I managed to get it working with 
```javascript
persistence: {
        factory: mosca.persistence.Mongo,
        url: 'mongodb://localhost:27017/mqtt'
    }
```
added to the mosca configuration without wirering something up.

**Comment by Densaugeo** [comment]
I'm having the same problem. I can see from the server that it is getting messages with the retain flag, but new subscribers don't get the retained messages. I tried adding a persistence like this:

~~~
var mosca_settings = {
  interfaces: [
    { type: 'mqtt', port: 1883 },
    { type: 'http', port: 8883 }
  ],
  persistence: mosca.persistence.Memory()
}

var mosca_server = new mosca.Server(mosca_settings);
~~~

But it still doesn't work. Does the memor persistence require something else? The documentation says something about 'wiring' and 'LevelUp options', but doesn't explain what those are.

**Comment by mcollina** [comment]
Try: https://github.com/mcollina/mosca/blob/master/test/server.js#L12-L14

**Comment by Densaugeo** [comment]
That works, thank you.

**Comment by alexandretok** [comment]
That works for me too, but if the broker is restarted the retained messages are gone.

Any tips on how to keep them even after a restart?

**Comment by mcollina** [comment]
You need to configure a RedisPersistence, LevelPersistence or MongodbPersistence

**Comment by enmotion** [comment]
I have a question about qos , I did check the Doc ,and discript text about mosca...
mosca not support for qos2 yet? for now ? or for longtime?
thanx mocallina,anyway mosca is a great project!

**Comment by mcollina** [comment]
You can use http://npm.im/aedes. It supports QoS 2.
