### ISSUE TITLE
Redis Persistence problem

### ISSUE THREAD

**Issue by volumetric** [mcollina/mosca#266]
Hi,

I am trying to use Redis as a persistent storage for all the communication happening on the mosca server, for that i added the persistence config in the moscasettings. But none of the messages are getting saved in the DB. when i am monitoring the redis server with MONITOR command in redis-cli, i am seeing only ```get``` and ```del``` commands for mqtt client_ids on the db on which i configured the persistence to occur. Shouldn't it be something like ```type``` or ```set``` for storing the key/value pair. Please check my config and log i am getting on monitoring:

```
var mosca = require('mosca')

var pubsubsettings = { // mosca uses "ascoltatori" for integration with redis and mongo and whatnot
  type: 'redis',
  redis: require('redis'),
  db: 12,
  port: 6379, // default port
  return_buffers: true, // to handle binary payloads
  host: "localhost"
};

var moscaSettings = {
  port: 1883,
  backend: pubsubsettings,
  persistence: {
    factory: mosca.persistence.Redis,
    host: "localhost",  //#TODO change this if not default host and port
    port: 6379,
    db: 2
  },
  http: {
    port: 3000,
    bundle: true
  }
};
```

This is the log on redis-cli when i MONITOR:

```
1433230280.488758 [2 127.0.0.1:38848] "get" "client:sub:mqttjs_2b3443e"
1433230280.489769 [2 127.0.0.1:38848] "del" "client:sub:mqttjs_2b3443e"
1433230280.491580 [2 127.0.0.1:38848] "del" "packets:mqttjs_2b3443e"
1433230280.492278 [12 127.0.0.1:38847] "publish" "$SYS/E1Nn5H8H/new/clients/" "{\"message\":\"mqttjs_2b3443e\",\"options\":{\"messageId\":\"NkKJoSIB\"}}"
1433230280.500943 [12 127.0.0.1:38847] "publish" "case1/alice/" "{\"message\":\"31323334646464646435\",\"options\":{\"qos\":0,\"messageId\":\"41xK1jrLS\",\"clientId\":\"mqttjs_2b3443e\"},\"binary\":true}"
```

Thanks for helping out.

**Comment by volumetric** [comment]
I think, i might be missing some bit for persistent storage, as i tried it with mongo db with this:
```
persistence: {
    factory: mosca.persistence.Mongo,
    url: 'mongodb://localhost:27017/mqtt'
}
```
and after few publish commands, their are collection named ```packets``` ,  ```retained``` and ```subscriptions``` has been formed in the DB names ```mqtt```, but not populated. their is also collection ```ascoltatori``` is built and getting populated and updated by client subscription and publications.

**Comment by volumetric** [comment]
Can anyone help me regarding this. Thanks

**Comment by mcollina** [comment]
It's perfectly normal that some of those collections are not populated, as they are used for some specific features. Plus, __you should not look into them__, as they can have TTLs or they are capped collections.
These collections (and Redis), are used by Mosca to perform its duties, and they should not be tampered or accessed directly.

If you want to store data for you own usage, use the provided callbacks to store it there.
