### ISSUE TITLE
Unable to install mosca using npm in ubuntu 14.04 

### ISSUE THREAD

**Issue by infigon** [mcollina/mosca#269]
tried with sudo permissions and changing ownership and file permissions for folder

getting error installing mosca through npm in ubuntu 14.04

npm http 304 https://registry.npmjs.org/bindings

> buffertools@2.1.2 install /usr/local/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/qlobber-fsq/node_modules/buffertools
> node-gyp rebuild

> leveldown@0.10.5 install /usr/local/lib/node_modules/mosca/node_modules/leveldown
> node-gyp rebuild

> fs-ext@0.4.5 install /usr/local/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/qlobber-fsq/node_modules/fs-ext
> node-gyp configure build

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
npm http 304 https://registry.npmjs.org/vm-browserify
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/qlobber-fsq/node_modules/fs-ext
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
make: Entering directory `/usr/local/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/qlobber-fsq/node_modules/buffertools/build'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mosca/node_modules/leveldown
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
  CXX(target) Release/obj.target/buffertools/buffertools.o
npm WARN optional dep failed, continuing leveldown@0.10.5
npm WARN optional dep failed, continuing qlobber-fsq@0.3.1
mkdir: cannot create directory ‘Release’: No such file or directory
mkdir: cannot create directory ‘./Release’: No such file or directory
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/qlobber-fsq/node_modules/buffertools/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/qlobber-fsq/node_modules/buffertools
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm http 304 https://registry.npmjs.org/browserify-zlib
npm http 304 https://registry.npmjs.org/browser-pack
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/sha.js
npm http GET https://registry.npmjs.org/json-stable-stringify
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/sha.js
npm http GET https://registry.npmjs.org/date-now
npm http GET https://registry.npmjs.org/path-platform
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/rfile
npm http GET https://registry.npmjs.org/ruglify
npm http GET https://registry.npmjs.org/indexof/0.0.1
npm http GET https://registry.npmjs.org/typedarray
npm http GET https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/date-now
npm http GET https://registry.npmjs.org/stream-splicer
npm http 304 https://registry.npmjs.org/path-platform
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/acorn
npm http 304 https://registry.npmjs.org/rfile
npm http GET https://registry.npmjs.org/Base64
npm http GET https://registry.npmjs.org/punycode/1.3.2
npm http GET https://registry.npmjs.org/querystring/0.2.0
npm http GET https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/ruglify
npm http 304 https://registry.npmjs.org/typedarray
npm http GET https://registry.npmjs.org/create-ecdh
npm http GET https://registry.npmjs.org/create-hash
npm http GET https://registry.npmjs.org/create-hmac
npm http 304 https://registry.npmjs.org/indexof/0.0.1
npm http 304 https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/diffie-hellman
npm http GET https://registry.npmjs.org/pbkdf2
npm http GET https://registry.npmjs.org/public-encrypt
npm http GET https://registry.npmjs.org/randombytes
npm http 304 https://registry.npmjs.org/stream-splicer
npm http 304 https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/browserify-aes
npm http GET https://registry.npmjs.org/browserify-sign
npm http GET https://registry.npmjs.org/JSONStream
npm http GET https://registry.npmjs.org/combine-source-map
npm http GET https://registry.npmjs.org/lexical-scope
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/acorn
npm http 304 https://registry.npmjs.org/Base64
npm http 200 https://github.com/mongodb-js/node-pre-gyp/archive/v0.6.5-appveyor.tar.gz
npm http 304 https://registry.npmjs.org/punycode/1.3.2
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/querystring/0.2.0
npm http 304 https://registry.npmjs.org/create-ecdh
npm http 304 https://registry.npmjs.org/create-hash
npm http 304 https://registry.npmjs.org/diffie-hellman
npm http 304 https://registry.npmjs.org/pbkdf2
npm http 304 https://registry.npmjs.org/public-encrypt
npm http 304 https://registry.npmjs.org/randombytes
npm http 304 https://registry.npmjs.org/create-hmac
npm http 304 https://registry.npmjs.org/browserify-aes
npm http 304 https://registry.npmjs.org/browserify-sign
npm http 304 https://registry.npmjs.org/JSONStream
npm http 304 https://registry.npmjs.org/combine-source-map
npm http 304 https://registry.npmjs.org/lexical-scope
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/json-stable-stringify
npm http 304 https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/callsite
npm http GET https://registry.npmjs.org/bn.js
npm http GET https://registry.npmjs.org/elliptic
npm http GET https://registry.npmjs.org/ripemd160
npm http 304 https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/pako
npm http 304 https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/callsite
npm http 304 https://registry.npmjs.org/ripemd160
npm http 304 https://registry.npmjs.org/pako
npm http GET https://registry.npmjs.org/miller-rabin
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/bn.js
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/inline-source-map
npm http GET https://registry.npmjs.org/convert-source-map
npm http GET https://registry.npmjs.org/is-array
npm http GET https://registry.npmjs.org/base64-js/0.0.8
npm http GET https://registry.npmjs.org/ieee754
npm http 304 https://registry.npmjs.org/miller-rabin
npm http 304 https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/convert-source-map
npm http GET https://registry.npmjs.org/readable-wrap
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/jsonify
npm http 304 https://registry.npmjs.org/ieee754
npm http 304 https://registry.npmjs.org/readable-wrap
npm http 304 https://registry.npmjs.org/is-array
npm http 304 https://registry.npmjs.org/base64-js/0.0.8
npm http 304 https://registry.npmjs.org/jsonify
npm http 304 https://registry.npmjs.org/inline-source-map
npm http GET https://registry.npmjs.org/brorand
npm http GET https://registry.npmjs.org/browserify-rsa
npm http GET https://registry.npmjs.org/parse-asn1
npm http GET https://registry.npmjs.org/resolve/1.1.6
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/brorand
npm http 304 https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/astw
npm http 304 https://registry.npmjs.org/parse-asn1
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/defined
npm http GET https://registry.npmjs.org/jsonparse/0.0.5
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/stream-combiner2
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/jsonparse
npm http 304 https://registry.npmjs.org/astw
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/resolve/1.1.6
npm http 304 https://registry.npmjs.org/defined
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/stream-combiner2
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/jsonparse/0.0.5
npm http 304 https://registry.npmjs.org/jsonparse
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/through2
npm http GET https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/through2
npm http 304 https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/npmlog
npm http GET https://registry.npmjs.org/rc
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/tar-pack
npm http GET https://registry.npmjs.org/estraverse
npm http GET https://registry.npmjs.org/esutils
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/optionator
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/npmlog
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/tar-pack
npm http 304 https://registry.npmjs.org/estraverse
npm http 304 https://registry.npmjs.org/esutils
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/optionator
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/rc
npm http GET https://registry.npmjs.org/prelude-ls
npm http GET https://registry.npmjs.org/deep-is
npm http GET https://registry.npmjs.org/levn
npm http GET https://registry.npmjs.org/type-check
npm http GET https://registry.npmjs.org/fast-levenshtein
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/levn
npm http 304 https://registry.npmjs.org/type-check
npm http 304 https://registry.npmjs.org/fast-levenshtein
npm http 304 https://registry.npmjs.org/elliptic
npm http 304 https://registry.npmjs.org/deep-is
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/ansi
npm http GET https://registry.npmjs.org/are-we-there-yet
npm http GET https://registry.npmjs.org/gauge
npm http GET https://registry.npmjs.org/deep-extend
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/uid-number/0.0.3
npm http GET https://registry.npmjs.org/fstream-ignore/0.0.7
npm http 304 https://registry.npmjs.org/browserify-rsa
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/gauge
npm http 304 https://registry.npmjs.org/deep-extend
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/ansi
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/are-we-there-yet
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/uid-number/0.0.3
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/delegates
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/delegates
npm http GET https://registry.npmjs.org/has-unicode
npm http GET https://registry.npmjs.org/lodash.padleft
npm http GET https://registry.npmjs.org/lodash.pad
npm http GET https://registry.npmjs.org/lodash.padright
npm http 304 https://registry.npmjs.org/fstream-ignore/0.0.7
npm http GET https://registry.npmjs.org/hash.js
npm http GET https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/lodash.padright
npm http GET https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/hash.js
npm http 304 https://registry.npmjs.org/has-unicode
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/lodash.pad
npm http 304 https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/lodash.padleft
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/har-validator
npm http GET https://registry.npmjs.org/asn1.js
npm http GET https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/lodash._basetostring
npm http GET https://registry.npmjs.org/lodash._createpadding
npm http GET https://registry.npmjs.org/delayed-stream
npm http GET https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/lodash._basetostring
npm http 304 https://registry.npmjs.org/lodash._createpadding
npm http 304 https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/delayed-stream
npm http 304 https://registry.npmjs.org/prelude-ls
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.3
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/is-my-json-valid
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/lodash.repeat
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/ctype/0.5.3
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/is-my-json-valid
npm http 304 https://registry.npmjs.org/lodash.repeat
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/brorand
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/brorand
npm http GET https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/generate-function
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/generate-function
npm http GET https://registry.npmjs.org/generate-object-property
npm http GET https://registry.npmjs.org/jsonpointer
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/jsonpointer
npm http GET https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/get-stdin
npm http 304 https://registry.npmjs.org/is-property

> bson-ext@0.1.7 install /usr/local/lib/node_modules/mosca/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)

/usr/bin/env: node: No such file or directory
npm http 304 https://registry.npmjs.org/asn1.js
npm http GET https://registry.npmjs.org/minimalistic-assert
npm http 304 https://registry.npmjs.org/minimalistic-assert
/usr/local/bin/mosca -> /usr/local/lib/node_modules/mosca/bin/mosca

> mosca@0.30.0 postinstall /usr/local/lib/node_modules/mosca
> npm run bundle

> mosca@0.30.0 bundle /usr/local/lib/node_modules/mosca
> browserify -r mqtt -s mqtt | uglifyjs --screw-ie8 > public/mqtt.js

/usr/bin/env: node: No such file or directory/usr/bin/env: node
: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by mcollina** [comment]
The nodejs installed via apt-get is broken and it should not be used.
It places the executable of node as nodejs (vs node)
I recommend installing it from the binaries provided on the website or with [npm](http://npm.im/npm).

**Comment by infigon** [comment]
Thanks @mcollina  fixed it with your suggestion.

nodejs installed through apt-get is available as "nodejs" and not "node"

created a symlink 

```
sudo ln -s /usr/bin/nodejs /usr/bin/node

```
