### ISSUE TITLE
simple config on mongodb not working

### ISSUE THREAD

**Issue by nsiitk** [mcollina/mosca#272]
mosca version 0.30.0 , mongodb 3.0.1, mqtt@1.2.1 on linux rhl 6.4 
used code

var mosca = require('mosca');
var ascoltatore = {
  type: 'mongo',
  url: 'mongodb://mqtt:abcdef@localhost:27017/mqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};
var persist={
    factory: mosca.persistence.Mongo,
    url: ascoltatore.url,
  };
var settings = {
  port: 1883,
backend: ascoltatore,
logger: {level: 'debug'},
http:{port:3000,bundle:true}
};
var server = new mosca.Server(settings);
server.on('clientConnected', function(client) {
    console.log('client connected', client.id);
});
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});
server.on('ready', setup);
function setup() {
  console.log('Mosca server is up and running');
}

for subscription from my  mac 
nitin-mac:dummy nitinsingh$ node node_modules/mqtt/mqtt.js sub -t 'hello' -h '192.168.1.128' -v
then for publish from other console
node node_modules/mqtt/mqtt.js pub -t 'hello' -h '192.168.1.128' -m 'from MQTT.js 17'

no message is delivered to subscriber. 
db has one collection ascoltatori with data
{ 
    "_id" : ObjectId("5579594f6572f420256cf504"), 
    "value" : "mqttjs_2ad57327", 
    "topic" : "$SYS/419w_BzI/new/clients", 
    "options" : {
        "qos" : null, 
        "messageId" : "Ey1uOBML"
    }
}
{ 
    "_id" : ObjectId("5579594f6572f420256cf505"), 
    "value" : "mqttjs_2ad57327", 
    "topic" : "$SYS/419w_BzI/new/subscribes", 
    "options" : {
        "qos" : null, 
        "messageId" : "Ekg_urzU"
    }
}
{ 
    "_id" : ObjectId("557959596572f420256cf506"), 
    "value" : "mqttjs_bc910bd6", 
    "topic" : "$SYS/419w_BzI/new/clients", 
    "options" : {
        "qos" : null, 
        "messageId" : "VyqOdSz8"
    }
}
{ 
    "_id" : ObjectId("557959596572f420256cf507"), 
    "value" : BinData(0, "ZnJvbSBNUVRULmpzIDE3"), 
    "topic" : "hello", 
    "options" : {
        "qos" : NumberInt(0), 
        "messageId" : "Nkx9_dBM8", 
        "clientId" : "mqttjs_bc910bd6"
    }
}

if backend removed setting message is delivered to subscriber.

if persistence: persist is added to setting three collections are created but no data in it
 
debug logs are
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"level":30,"mqtt":1883,"http":3000,"msg":"server started","time":"2015-06-11T09:47:55.439Z","v":0}
Mosca server is up and running
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_2ad57327","level":20,"timeout":15000,"msg":"setting keepalive timeout","time":"2015-06-11T09:47:59.080Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_2ad57327","level":30,"msg":"client connected","time":"2015-06-11T09:47:59.084Z","v":0}
client connected mqttjs_2ad57327
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"level":20,"packet":{"topic":"$SYS/419w_BzI/new/clients"},"msg":"published packet","time":"2015-06-11T09:47:59.093Z","v":0}
Published mqttjs_2ad57327
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_2ad57327","level":20,"timeout":15000,"msg":"setting keepalive timeout","time":"2015-06-11T09:47:59.102Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_2ad57327","level":20,"packet":{"messageId":36654,"qos":1,"subscriptions":[{"topic":"hello","qos":0}]},"msg":"subscribe received","time":"2015-06-11T09:47:59.102Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_2ad57327","level":30,"topic":"hello","qos":0,"msg":"subscribed to topic","time":"2015-06-11T09:47:59.105Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"level":20,"packet":{"topic":"$SYS/419w_BzI/new/subscribes"},"msg":"published packet","time":"2015-06-11T09:47:59.110Z","v":0}
Published mqttjs_2ad57327
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_2ad57327","level":20,"msg":"pingreq","time":"2015-06-11T09:48:09.103Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_2ad57327","level":20,"timeout":15000,"msg":"setting keepalive timeout","time":"2015-06-11T09:48:09.104Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_bc910bd6","level":20,"timeout":15000,"msg":"setting keepalive timeout","time":"2015-06-11T09:48:09.794Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_bc910bd6","level":30,"msg":"client connected","time":"2015-06-11T09:48:09.795Z","v":0}
client connected mqttjs_bc910bd6
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"level":20,"packet":{"topic":"$SYS/419w_BzI/new/clients"},"msg":"published packet","time":"2015-06-11T09:48:09.796Z","v":0}
Published mqttjs_bc910bd6
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_bc910bd6","level":20,"timeout":15000,"msg":"setting keepalive timeout","time":"2015-06-11T09:48:09.811Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_bc910bd6","level":20,"packet":{"topic":"hello"},"msg":"published packet","time":"2015-06-11T09:48:09.813Z","v":0}
Published <Buffer 66 72 6f 6d 20 4d 51 54 54 2e 6a 73 20 31 37>
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_bc910bd6","level":20,"msg":"disconnect requested","time":"2015-06-11T09:48:09.815Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_bc910bd6","level":20,"msg":"closing client","time":"2015-06-11T09:48:09.816Z","v":0}
{"name":"mosca","hostname":"TollfreeDBServer","pid":9504,"client":"mqttjs_bc910bd6","level":30,"msg":"closed","time":"2015-06-11T09:48:09.817Z","v":0}

**Comment by mcollina** [comment]
All seems good, and messages are inserted in the collection just fine.
Can you please check if downgrading to MongoDB 2.8 solves the issue? I never tested it there.

**Comment by mcollina** [comment]
Mosca now supports MongoDB 3.
