### ISSUE TITLE
Adding users for Authentication purpose

### ISSUE THREAD

**Issue by niralkalavadia** [mcollina/mosca#274]
I am using Mosca as an embedded mode along with express. I have developed REST API using express. I am planning to add and remove user from browser via http (REST API). Can I use addUser and rmUSer method defined in authorizer.js?

Thanks

**Comment by mcollina** [comment]
the authorizer.js stores stuff on the file system, while you would probably want to store them in a database. You should override the `authenticate` method of the mosca server.
