### ISSUE TITLE
mosca fails to install with ponte

### ISSUE THREAD

**Issue by avelampudi** [mcollina/mosca#278]
I'm trying to install Eclipse Ponte on my system, which includes mosca. When I do so, npm runs an error saying 'this is most likely a problem with the mosca package and not with npm itself. this fails on my system : browserify lib/webClient.s -s mqtt > public/mqtt.js

The errors continue with :::

mosca@0.26.2 postinstall: 'npm run bundle'
exit status 1

failed at the mosca@0.26.2 postinstall script 'npm run bundle'
this is most likely a problem with the mosca package,
not with npm itself
tell the author that this fails on your system: npm run bundle

Please help me out! I tried npm install mosca and that runs fine, but I can't get Ponte to install.

**Comment by behrad** [comment]
have you installed `browserify` ?

**Comment by mcollina** [comment]
Which version of node are you running on?

**Comment by avelampudi** [comment]
@mcollina I am running v0.12.4 of node which comes with npm version 2.10.1.
I'm aware that Ponte usually asks for 0.10.x version of nodejs but when I tried to install it with v0.10.0, npm wasn't able to work at all.

@behrad Yes, I have installed browserify. (npm install browserify) That installed just fine too. It just Ponte with its mosca bundle that seems to be running the error.

**Comment by mcollina** [comment]
Ponte does not work on node 0.12 yet. I will get that updated shortly (next week?)

**Comment by mcollina** [comment]
Fixed long ago.
