### ISSUE TITLE
 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by anishmenon** [mcollina/mosca#279]
My code :
var mosca = require('mosca')

var ascoltatore = {
  //using ascoltatore
  type: 'mongo',
  url: 'mongodb://localhost:27017/amqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};

var settings = {
  port: 1883,
  backend: ascoltatore
};

var server = new mosca.Server(settings);

server.on('clientConnected', function(client) {

  console.log('client connected', client.id);

});

// fired when a message is received
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});

var server = new mosca.Server(settings);
server.on('ready', setup);

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running')
}

Output :

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:448:13)

**Comment by mcollina** [comment]
Something else is using port 1883, probably RabbitMQ or Mosquitto. Change port or stop them.

**Comment by anishmenon** [comment]
sudo netstat -lpn |grep :1883 
returns blank . 

already killed the port 1883 

and i've stopped service of RabbitMQ,Mosquitto

**Comment by mcollina** [comment]
Try rebooting? It's something running on your machine.

**Comment by anishmenon** [comment]
rebooted after my last comment still same error .

**Comment by mcollina** [comment]
Try putting in a port in the 5xxx range.

**Comment by mcollina** [comment]
Which OS are you on?

**Comment by anishmenon** [comment]
Its working on another machine  (PC)  . i'm on ubuntu 14.04
