### ISSUE TITLE
Continuous incoming message 

### ISSUE THREAD

**Issue by anishmenon** [mcollina/mosca#281]
i'm using mqtt.js for subscribing and publishing . The server is mosca

var mosca = require('mosca');

var ascoltatore = {
  //using ascoltatore
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};

var settings = {
  port: 1883,
  backend: ascoltatore
};

var server = new mosca.Server(settings);

server.on('clientConnected', function(client) {
    console.log('client connected', client.id);
});

// fired when a message is received
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});

server.on('ready', setup);

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running');
}

=============================================
sudo node server.js

Mosca server is up and running

Published mqttjs_127a1168

Published mqttjs_127a1168

client connected mqttjs_f37b398d

Published mqttjs_f37b398d

===============================================

mqtt sub -t 'hello' -h 'localhost' -v
black 

===============================================

mqtt pub -t 'hello' -h 'localhost' -m 'from MQTT.js'
done

===============================================

mqtt sub -t 'hello' -h 'localhost' -v

hello from MQTT.js
hello from MQTT.js
hello from MQTT.js
hello from MQTT.js
hello from MQTT.js
hello from MQTT.js

Continuing until CTRL + C
===============================================

**Comment by mcollina** [comment]
This should be fixed in the top-most ascoltatori. Just reinstall mosca and it should be ok.

**Comment by anishmenon** [comment]
i've tried re-installing 

which i run server 

mosca -v | bunyan

its working fine . 

but on the script i shown below repeatedly throwing or receiving incoming message

**Comment by mcollina** [comment]
Sorry, you should delete `node_modules/mosca` entirely for this to take effect.

**Comment by anishmenon** [comment]
done again same error . i'm on ubuntu 14.04 . Is that mqtt.js issue ?

**Comment by mcollina** [comment]
I have released an updated version of Mosca (0.30.3) that uses the newer ascoltatori (with the fix).

**Comment by anishmenon** [comment]
How i can install that version ? steps ?

**Comment by anishmenon** [comment]
i've done that .
when i run script node server.js
 now it shows .


  throw err;
          ^
Error: Cannot find module 'mosca'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/node4/anish/server.js:1:75)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Function.Module.runMain (module.js:490:10)
node4@Node4:~/anish$ ^C


but when i type simply mosca on my terminal is working fine . 
       +++.+++:   ,+++    +++;   '+++    +++. 
      ++.+++.++   ++.++  ++,'+  `+',++  ++,++ 
      +`  +,  +: .+  .+  +;  +; '+  '+  +`  +` 
      +`  +.  +: ,+  `+  ++  +; '+  ;+  +   +. 
      +`  +.  +: ,+  `+   +'    '+      +   +. 
      +`  +.  +: ,+  `+   :+.   '+      +++++. 
      +`  +.  +: ,+  `+    ++   '+      +++++. 
      +`  +.  +: ,+  `+     ++  '+      +   +. 
      +`  +.  +: ,+  `+  +:  +: '+  ;+  +   +. 
      +`  +.  +: .+  .+  +;  +; '+  '+  +   +. 
      +`  +.  +:  ++;++  ++'++   ++'+'  +   +. 
      +`  +.  +:   +++    +++.   ,++'   +   +.

**Comment by mcollina** [comment]
npm install mosca in the same directory of your script?
Il giorno gio 25 giu 2015 alle 13:24 Anish Menon <notifications@github.com>
ha scritto:

**Comment by anishmenon** [comment]
Thanks .
