### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by anishmenon** [mcollina/mosca#282]
If public understood that my app is using mqtt on my server . If they directly publish without any credentials that will be bad for the subscribed fellows r8 ?

broker:

var mosca = require('mosca');
var mongoUrl = 'mongodb://localhost:27017/mqtt';
var ascoltatore = {
  //using ascoltatore
  type: 'mongo',
  url: mongoUrl,
  pubsubCollection: 'ascoltatori',
  mongo: {}
};

var settings = {
  port: 1883,
  persistence: {
    factory: mosca.persistence.Mongo,
    url: mongoUrl,
  },
  backend: ascoltatore
};

// Accepts the connection if the username and password are valid
var authenticate = function(client, username, password, callback) {
  var authorized = (username === 'alice' && password.toString() === 'secret');
  if (authorized) client.user = username;
  callback(null, authorized);
}

// In this case the client authorized as alice can publish to /users/alice taking
// the username from the topic and verifing it is the same of the authorized user
var authorizePublish = function(client, topic, payload, callback) {
  callback(null, client.user == topic.split('/')[1]);
}

// In this case the client authorized as alice can subscribe to /users/alice taking
// the username from the topic and verifing it is the same of the authorized user
var authorizeSubscribe = function(client, topic, callback) {
  callback(null, client.user == topic.split('/')[1]);
}

var server = new mosca.Server(settings);

server.authenticate = authenticate;
server.authorizePublish = authorizePublish;
server.authorizeSubscribe = authorizeSubscribe;

server.on('ready', setup);

server.on('clientConnected', function(client) {
    console.log('client connected', client.id);
});

// fired when a message is received
server.on('published', function(packet, client) {
    console.log('Published',packet.payload);
    if(client!==undefined&&client!==null){
        console.log("\tclient",client.id);  
    }
});

// Fired when the mqtt server is ready
function setup() {
    console.log('Mosca server is up and running');
}

server.on('clientConnected', function(client) {
  console.log('New connection: ', client.id );
});

Publisher :

var mqtt = require('mqtt');
var client = mqtt.connect();

var message = {
  topic: 'mqtt/offline',
  payload: 'hello', 
  qos: 1, 
  retain: false
};

client.publish(message,
  function() {
  console.log("pubOffline","publish done!");
  client.end();
});

Output:

Error: Connection refused: Not authorized
Please reply how to pass username and password

when i do something like

var settings = {
  keepalive: 1000,
  protocolId: 'MQIsdp',
  protocolVersion: 3,
  clientId: 'Thermostat 1a',
  username:'alice',
  password:'secret'
}

// client connection
var client = mqtt.createClient(port, host, settings);

output : 
createClient is deprecated, use connect instead

**Comment by anishmenon** [comment]
@mcollina please help .

**Comment by mcollina** [comment]
This covers it: https://github.com/mcollina/mosca/wiki/Authentication-&-Authorization

**Comment by anishmenon** [comment]
yes but its a client side issue with mqtt.js

output : 
createClient is deprecated, use connect instead

**Comment by mcollina** [comment]
`mqtt.connect(url, { username: 'matteo', password: 'collina' })`
