### ISSUE TITLE
MQTT-over-Websockets Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by whisher** [mcollina/mosca#285]
Hi,
sorry to bother you but I'm stuck on this
point.
Following this doc https://github.com/mcollina/mosca/wiki/MQTT-over-Websockets

I set up the broker like
```javascript
var settings = {
  http: {
    port: 1884,
    bundle: true,
    static: './'
  }
};

//here we start mosca
var server = new mosca.Server(settings);
```

But when I run

> node broker

I've got this ugly error

```javascript
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at net.js:1270:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

```javascript
ps -ax | grep node
5266 pts/2    R+     0:00 grep --colour=auto node
kill -9 5266
bash: kill: (5266) - No such process
```

>vpn con node v0.12.2
>Linux Mint 17.1 Rebecca

Best regard.

**Comment by mcollina** [comment]
I think it is still listening to 1883 for MQTT, and probably there is
something else listening on that port, like RabbitMQ or Mosquitto.
Il giorno lun 29 giu 2015 alle 08:22 Bedini Fabio aka whisher <
notifications@github.com> ha scritto:

**Comment by whisher** [comment]
Thanks for the reply, but
it doesn't work also with
var settings = {
  http: {
    port: 3000,
    bundle: true,
    static: './'
  }
};

**Comment by mcollina** [comment]
You need to change the MQTT port. Much better, turn off or uninstall any
other thing running on port 1883: usual culprits are mosquitto or rabbitmq.
Il giorno lun 29 giu 2015 alle 12:36 Bedini Fabio aka whisher <
notifications@github.com> ha scritto:

> Thanks for the reply, but
> it doesn't work also with
> var settings = {
> http: {
> port: 3000,
> bundle: true,
> static: './'
> }
> };
>

**Comment by whisher** [comment]
Just worked it out with
>sudo lsof -i TCP:1883
I see mosquitto process the culprit !
so simple 
>sudo service mosquitto stop
I've got a lot of problem to uninstall mosquitto !
I've tried with 
>sudo apt-get purge mosquitto
with no lucky.

You can close the issue.

Thanks a ton for the clue.
