### ISSUE TITLE
Connected client stat inconsistency

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#286]
Observed that `connected clients last X` is always showing total number of connected clients (as connected clients) and not the connected clients in past X time, however I believe it should mean as `publishes lastX` which is showing last publishes done in past X time.

**Comment by mcollina** [comment]
Great spot, would you like to submit a PR?
Il giorno lun 29 giu 2015 alle 13:14 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
Sure, see #289

**Comment by behrad** [comment]
published messages are also counting internal `$SYS` publishes, shouldn't we exclude them from stats? https://github.com/mcollina/mosca/blob/master/lib/stats.js#L118

**Comment by mcollina** [comment]
Of course just put it in :).

**Comment by behrad** [comment]
:+1:  Ok

**Comment by mcollina** [comment]
@behrad can we close this?

**Comment by behrad** [comment]
yes, 
however I saw that m1, m5, m15 values are all near the same, there are all reset at the same interval! isn't this an issue?
