### ISSUE TITLE
Need help regarding MQTT SSL connection to Mosca broker. When I try to connect to broker, it gives me following error.

### ISSUE THREAD

**Issue by PritamUpadhyay** [mcollina/mosca#288]
**Error-Stack**
 
    { [Error: connect ECONNREFUSED]
      code: 'ECONNREFUSED',
      errno: 'ECONNREFUSED',
      syscall: 'connect' }

**mosca-broker_server.js**

    var mosca = require('mosca');
    
    var SECURE_KEY = 'C:\openssl\key.pem';
    var SECURE_CERT = 'C:\openssl\cert.pem';
    
    var moscaSetting = {
    port: 8443
    , secure: {
    keyPath: SECURE_KEY,
    certPath: SECURE_CERT,
    }
    };
    
    var server = new mosca.Server(moscaSetting);
    
    server.on('ready', function () {
    console.log('Mosca server is up and running.\n')
    });
    
    server.on('clientConnected', function (client) {
    console.log('Client Connected \t:= ', client.id);
    });
    
    server.on('clientDisconnected', function (client) {
    console.log('Client Disconnected := ', client.id);
    });

**mqtt-client.js**

    var mqtt = require('mqtt');
    var tls = require('tls');
    
    var host = 'mqtts://localhost:8443'; 
    
    
    var SECURE_CERT = 'C:\\openssl\\cert.pem';
    
    var options = {    
       clientId: "NodeClient"
       , clean: true   
       , certPath: SECURE_CERT    
    }
    
    var client = mqtt.connect(host, tls.connect(options)); 
    
    client.on('connect', function () {
        console.log('client connected: \t' + client_Id + '\n');
    });
    client.subscribe("Hello");
    client.publish("Hello", "World!..");
    
    client.on('message', function (topic, message, pakcet) {
        console.log("Recieved:= " + message.toString());
    });

**Can you please tell me what is wrong in this code or where am I making mistake?**

**Comment by PritamUpadhyay** [comment]
@mcollina or @behrad  : can you help me out with this?

**Comment by behrad** [comment]
1) please post codes in appropriate github markup to be readable

2) from your code I can't see any issue, please make sure your server is really started on port 8443, see your console logs for any errors.

**Comment by PritamUpadhyay** [comment]
@behrad : Thanks for your response. 
> 1) please post codes in appropriate github markup to be readable.

I have updated accordingly. 

> from your code I can't see any issue, please make sure your server is really started on port 8443, see your console logs for any errors.

Yes. Server is starting on port 8443. The error stack which I gave in the questions shows connections is refused. There is no error in server console.

**Comment by jesusofsuburbia** [comment]
Hi,

I think the default port for MQTT over TLS is 8883. Set your logging level down in the Mosca settings...
```javascript
var settings = {
    logger: {
        name: "tls example",
        level: 0,
    }
    // ...
}
```

and you see more server console output. Probably the wrong port on the client side.
In the server output, you should be able to see the port used for mqtts!
I have Mosca + mqtt.js with TLS working now, and I only got `ECONNREFUSED` when the port was unreachable (Server crashed, port blocked by firewall or I just chose the wrong port in mqtt.js)

**Comment by jaydeep17** [comment]
@PritamUpadhyay I have the exact same problem, how did you fix it ?

**Comment by PritamUpadhyay** [comment]
@jaydeep17 : May be [this] (https://github.com/PritamUpadhyay/mosca/blob/patch-1/examples/Server_Wtih_All%20Interfaces-Settings.js) can help you...
