### ISSUE TITLE
Support more stats

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#289]
Can you help to arrange a PR for

`$SYS/broker/clients/inactive`
`$SYS/broker/clients/maximum`

`$SYS/broker/bytes/received`
`$SYS/broker/bytes/sent`
`$SYS/broker/load/bytes/sent/Xmin`

**Comment by mcollina** [comment]
Implenting 'inactive' is kind of tricky. Basically this value is not tracked anywhere, in the sense that the number of clients that are not connected but have an offline subscription.

Maximum is easier, if we consider the maximum client, just extend this to track the maximum https://github.com/mcollina/mosca/blob/master/lib/stats.js#L90-L110.

As for the bytes, there is no visibility in Mosca of these numbers. I will get the support for this kind of introspection when the Aedes refactoring lands.

**Comment by behrad** [comment]
@mcollina I need client disconnects like `$SYS/+/new/clients`
This can be implemented two ways:

1) adding a new `$SYS/+/SOMETHING/clients` where SOMETHING=disconnect e.g.

2) adding details to the payload of existing `$SYS/+/new/clients` stat, this means converting payload from raw string (currently is clientId) to a json string



The same also is true for `new/subscribes` where we can also emit unsubscribes.

I want to hear your comments before I open a PR

**Comment by behrad** [comment]
this is a sample way of doing it: https://github.com/emqtt/emqttd/wiki/%24SYS%20Topics#client-sys-topics

**Comment by mcollina** [comment]
I'm in for `$SYS/+/disconnect/clients`, and also `$SYS/+/new/unsubscribes`.
I would not put too much parsing/generating of JSONs in these topics, as it's pure overhead.

**Comment by behrad** [comment]
I'll for new topic names then mcollina

**Comment by mcollina** [comment]
:+1:

**Comment by psorowka** [comment]
What do you think how much of these stats should be 'default' vs 'configurable'.

Following my own experience and the various discussions about the $SYS topics here I think there are very different requirements in every application.

To name a few:

- combine stats in fewer topics using json vs. publishing single numbers on more topics
- generate deeper insights
- lower or higher update rate than the current 10s default
- ... 

So, before adding more and more default stats to the core which can never match all (possible divergent) requirements simultaneously, wouldn't it be a good idea to find a flexible approach? I think the of three fundamentally different possibilities:

- provide config options for stats (sticking to the current 'nested' stat generation)
- expose module-api for custom stat generation (similar to current authorization api)
- pull stat generation into a seperate module.

**Comment by behrad** [comment]
agreed @psorowka However brokers should provide only low level, base stats on which apps can build upon. For example I can build client connections per applicationId by listening to default connection stat. 
I believe all stats discussed here are lower bound defaults and I was thinking of config switches for them to be turned on/off as like the `publishNewClient` already available in mosca config.

I think first option is currently so close :)

**Comment by psorowka** [comment]
we should probably differentiate between real "stats" (e.g. msgs per minute) and low level "events" (e.g. client connected). Both are appear similar because they are published on $SYS/ scoped topics.

I agree, basic low level events can be part of mosca, but fancy stats (and the various requirements, see above) could be pulled out to a better fitting, more flexible place

**Comment by behrad** [comment]
I was missing topic's base proposal for extra stats, you're right @psorowka 

However I am ok atleast with 

`$SYS/broker/clients/inactive`
`$SYS/broker/clients/maximum`

if they could be implemented with low overhead.

**Comment by psorowka** [comment]
@behrad following up on @mcollina's first response. What would you expect in `clients/inactive`? Disonnected clients that have offline subscriptions or connected clients that do not send anything? I think the broker should be clearly separated from a toplevel device-management logic (in the sense of mosca doesn't can never know how many clients are out there, configured for your server but not connected).

You stated: 

> @mcollina I need client disconnects like $SYS/+/new/clients

Couldn't you implement that with the last-will feature?

**Comment by behrad** [comment]
> @behrad following up on @mcollina's first response. What would you expect in clients/inactive? Disonnected clients that have offline subscriptions or connected clients that do not send anything? I think the broker should be clearly separated from a toplevel device-management logic (in the sense of mosca can never know how many clients are out there, configured for your server but not connected).

Disonnected clients that have offline subscriptions. 
But I accept that this is a application logic and can be achieved, however mosca should provide basic info like max clients, max subscriptions stored, ...



> Couldn't you implement that with the last-will feature?

I need it for my own stats generation. Don't think last-will is a good idea for this scenario, and we have no last-will set in our clients currently. 

disconnect events are simple counterparts of connect events.

**Comment by psorowka** [comment]
> disconnect events are simple counterparts of connect events.

....which you would expect to be generated at the point where mosca currently would issue the last-will? Makes sense for me.

**Comment by mcollina** [comment]
Some stuff around stats:

1. I plan to have it as a separate module, mainly for seamless use with [Aedes](http://npm.im/aedes), something boring like 'mqtt-broker-stats', or 'mosca-stats'. How this module will be used here is yet to be decided, as right now it is highly coupled to Mosca.
2. I am concerned about supporting the number of 'inactive' clients, mainly because of the accurancy of this number. The `persistence` should be responsible for it, but then this will not be a per-instance stat, but rather a glob stat replicated by all instances.
3. Calculating the number of inactive clients is an I/O operation, which I wanted to avoid for stats generation
4. Max clients (in the lifetime of an instance/process) can easily be achieved, I am accepting a PR on this (cc @behrad).
5. Inactive clients and subscriptions stored are something more tricky. If you want to send a PR, please go for it, but you will have to touch all persistences.

**Comment by mcollina** [comment]
Closing as it has been open for a long time, feel free to reopen.
