### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by Whitebeard86** [mcollina/mosca#290]
Hello,

I need help to understand the multiple instance concept.

I have an environment that may require more than 1 instance of Mosca operable (on multiple servers). To make this seamless to the clients I know that I have to insert a load balancer (HAProxy for instance) to balance the connections.

My question is, if client A is connected to server A and client B is connected to server B and if both have the same topic subscribed, both can receive/send messages? What are the essential steps required to make this work?

Thanks in advance,
john.

note: nice project, congratulations!

**Comment by behrad** [comment]
> My question is, if client A is connected to server A and client B is connected to server B and if both have the same topic subscribed, both can receive/send messages? What are the essential steps required to make this work?

If you are sharing a single shared backend between mosca instances, it should already work as is.

a good example is Redis backend, thanks redis pub/sub helping mosca instances to talk to each other. 

However I have not tested with other backend configurations, 

local LevelUP should also work :)

**Comment by Whitebeard86** [comment]
Ok, thanks!

There is any performance differences between that situation I mentioned and if the users were both connected on the same server (Client A & B both connected to server A)?

**Comment by behrad** [comment]
I think simple answer is NO! However you would earn some HA. and again it depends to your backend implementation.

@mcollina can tell about mosca internals

**Comment by mcollina** [comment]
There is no performance difference between the two scenarios, as @behrad said.

**Comment by iOiurson** [comment]
Hello @mcollina !
We are having an issue on the matter of multiple broker instances.

We are trying to set up 2 distinct instances of mosca (both on redis, with different db numbers), that need to connect with 2 distinct MQTT clients. All 4 instances are on the same server.
Broker A is connected to client A with port A, broker B is connected to client B with port B, and there shouldn't be any cross communications.

Setting up 1 client and the 2 brokers is fine, the connection between the client and its broker is working okay.
If we set up the second MQTT client, then both our 2 clients enter an infinite connection/disconnection loop, which makes them totally unavailable to use.

Is there something we're not doing right ?

Thanks !

````
var pubsubsettings = {
    type: 'redis',
    redis: require('redis'),
    db: 11, // or 12 for the B broker instance 
    host: 'localhost',
    return_buffers: true
}; 
````

**Comment by hicaro** [comment]
@iOiurson did you end up solving the issue with your two broker instances? I have the same problem using two instances and redis (with different db numbers).
