### ISSUE TITLE
Server callback called twice

### ISSUE THREAD

**Issue by arvindr21** [mcollina/mosca#291]
Hello,

I have the following setup 

```js
var mosca = require('mosca');

var settings = {
    port: 2191,
    persistence: mosca.persistence.Memory
};

var server = new mosca.Server(settings, function() {
    console.log('Mosca server is up and running 2191');
});
```

When I start the server, the console log prints twice. Not sure what I am doing incorrectly. 

Can you please help?

Thanks.

**Comment by arvindr21** [comment]
Upon modifying the above like

```js
var mosca = require('mosca');

var settings = {
    port: 2191,
    persistence: mosca.persistence.Memory
};

var server = new mosca.Server(settings, function(err, srv) {
   console.log(err || srv);
    console.log('Mosca server is up and running 2191');
});
```

The response for the first time callback was `Error: is not of a type(s) object]` & the second time, it works fine.

**Comment by PritamUpadhyay** [comment]
@arvindr21 : This fixes your problem. I think you should use **persistence** as shown below.

    var settings = {
        port: 2191,
        persistence:
            {
                factory:mosca.persistence.Memory
            }
    };
    
    var server = new mosca.Server(settings, function () {
        console.log('Mosca server is up and running 2191');
    });

**Comment by mcollina** [comment]
Thanks @PritamUpadhyay for helping him, that should be good!
