### ISSUE TITLE
not possible to pass options to TLS module of node

### ISSUE THREAD

**Issue by jesusofsuburbia** [mcollina/mosca#292]
Hi,

just playing around with MQTT using TLS.
Got it working with a client using mqtt.js and all the right certificates.

Now I tried to refuse clients that don't have a certificate signed by a trusted CA.
I want to define the trusted CA's in the TLS options as mentioned here:
https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

Refusing clients should be possible by setting `rejectUnauthorized : true`.

Problem is, there seems no way to pass options in `new Mosca.Server` to the TLS module
I tried something like this, but I think only `keyPath` and `certPath` are used in the TLS options here...
```javascript
var settings = {
    logger: {
        name: "secureExample",
        level: 0,
    },
    secure : { 
        port : 8883,
        keyPath: __dirname + '/keys/mqtts.key',
        certPath: __dirname + '/keys/mqtts.crt',
        ca: [ fs.readFileSync(__dirname + '/keys/ca.crt') ],
        requestCert: true,
        rejectUnauthorized: true
    }
};
```

Any suggestions on this?
Fallback to mqtt.js-Server?

**Comment by mcollina** [comment]
I would not recommend using MQTT.js-server, which exists solely for testing purposes.

I think the best course of action is to figure out where that should be put in here:
https://github.com/mcollina/mosca/blob/master/lib/options.js

And probably add a unit test for this use case.

**Comment by mcollina** [comment]
Have a look at https://github.com/mcollina/mosca/pull/283 for how to make this change.

**Comment by mcollina** [comment]
Should be fixed now.
