### ISSUE TITLE
help reading payload

### ISSUE THREAD

**Issue by 577473** [mcollina/mosca#293]
Hi. I have succesufully run a mosca server and as i was testing it with MQTT.fx, i noticed in the logs (on published event), that the payload (it's just a string) is encoded  : 

    topic: '/alfa',
    payload: <Buffer 6a 6f 72> 

Do i need to implement the decoding or is something builtin that i am missing?

thanks.

**Comment by mcollina** [comment]
I recommend you familiarize yourself with Node.js, there are plenty of resources, from http://nodeschool.io to the node.js API.

The payload in MQTT is a binary (opaque) blob, and then it is exposed as a `Buffer`, which is the standard node type for binary data. A `payload.toString()` will get your string.
