### ISSUE TITLE
Problem with offline subscriptions

### ISSUE THREAD

**Issue by bossqone** [mcollina/mosca#294]
Hello, I've found a problem with offline subscriptions.

I'm using 4 different clients (chrome, firefox, internet explorer, and android's chrome).
All clients are subscribed to channel 'testing' without any problems and I can send messages to this channel, but when I turn off WiFi on android phone, send some messages from other clients and turn back on WiFi, no messages are delivered to this client.
So I tried to turn off WiFi again, send messages from other clients and turn back on WiFi. This time were messages delivered succesfully.

MongoDB's collections (packets, retained, subscriptions) are empty, even all connected clients are subscribed in channel 'testing'.
This subscription entry was created when phone client reconnected for first time.

```javascript
/* 0 */
{
  "_id" : ObjectId("559b081d75ee310859863f27"),
  "client" : "714ce18f-c58a-45a4-b4f1-49df8b590b88",
  "topic" : "testing",
  "qos" : 1,
  "added" : ISODate("2015-07-06T22:59:06.613Z")
}
```

Log file: https://gist.github.com/bossqone/3b716c8baa68652ec6ae
Phone client id: 714ce18f-c58a-45a4-b4f1-49df8b590b88

Thanks for every response :)

-------------------------------------------

My server configuration:
```javascript
var server = require('http').createServer(app);
var mosca = require('mosca');

var moscaServer = new mosca.Server({
    logger: {
        streams: [{
            level: 'debug',
            path: './log'
        }]
    },
    backend: {
        type: 'mongo',
        url: 'mongodb://localhost:27017/mqtt',
        pubsubCollection: 'mqtt_pubsub',
        mongo: {}
    },
    persistence: {
        factory: mosca.persistence.Mongo,
        url: 'mongodb://localhost:27017/mqtt',
        ttl: {
            subscriptions: 1000 * 60 * 10,
            packets: 1000 * 60 * 10
        }
    }
});
moscaServer.attachHttpServer(server);

moscaServer.on('ready', function () {
    console.log('Mosca server is up and running');
});

moscaServer.on('clientConnected', function(client) {
    console.log('client connected', client.id);     
});

moscaServer.on('clientDisconnecting ', function(client) {
    console.log('client disconnecting', client.id);     
});

moscaServer.on('clientDisconnected', function(client) {
    console.log('client disconnected', client.id);     
});

server.listen(config.httpOptions.httpPort, function () {
    Pribe.app().logger().success('Pribe is running on PORT: ' + server.address().port);
});
```

And this is client-side script (using MQTT.js lib):
```javascript
controllers.controller('TestCtrl', ['$scope', 'Question', function ($scope, Question) {
    "use strict";

    function generateUUID() {
        var d = new Date().getTime();
        var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
            var r = (d + Math.random() * 16) % 16 | 0;
            d = Math.floor(d / 16);
            return (c == 'x' ? r : (r & 0x3 | 0x8)).toString(16);
        });
        return uuid;
    };

    var clientId = generateUUID();
    var reconnecting = false;
    $scope.messages = [];

    var client = mqtt.connect('ws://192.168.2.100:8000', {
        protocolId: 'MQIsdp', // mosca broker supports for now only protocol 3.1 (not 3.1.1)
        protocolVersion: 3,
        clientId: clientId,
        clean: false,
        connectTimeout: 10 * 1000
    });

    client.on('connect', function () {
        $scope.$apply(function () {
            if (reconnecting) {
                $scope.messages.push('reconnected');
                reconnecting = false;
            } else {
                $scope.messages.push('connected');
            }
        });

        client.subscribe('testing', {
            qos: 1
        });
    });

    client.on('offline', function () {
        $scope.$apply(function () {
            $scope.messages.push('offline');
        });
    });

    client.on('reconnect', function () {
        reconnecting = true; 
    });

    client.on('message', function (topic, message) {
        $scope.$apply(function () {
            $scope.messages.push('topic:  '+ topic + ' | message: ' + message.toString());
        });
    });

    $scope.send = function () {
        var message = new Date().getTime().toString();

        client.publish('testing', message, {
            qos: 1
        });
    };
}]);
```

**Comment by mcollina** [comment]
I have tested your server with a non-angular client (on Chrome and iOS) and it worked without issues.

Which version of node.js are you using on the server? Which version of MQTT.js are you using in the client?

This is the client I used:
```html
<html>
  <head>
    <script src="/mqtt.js"></script>
  </head>
  <body>
    <script>
var client = mqtt.connect({
  clientId: 'alongclientid',
  clean: false
});

client.subscribe("mqtt/demo", { qos: 1 });

      client.on("message", function(topic, payload) {
        alert([topic, payload].join(": "));
      });

    </script>
  </body>
</html>
```

**Comment by bossqone** [comment]
I've tried all this:
- without angular - no fix
- take 'subscribe' call out of 'on connect' callback - no fix
- tested other mobile browsers (firefox, opera) - all got same problem

node.js: 0.12.5
mosca: 0.30.3
mqtt.js: 1.3.3

**Comment by mcollina** [comment]
We are at a stall, I cannot reproduce - so I cannot suggest a fix, and you experience the issue.

Let's not consider mobile browsers: does this work on Chrome? Does offline works for you using the CLI (mosquitto or mqtt.js)? Does offline work over tcp (not websocket)?

Which OS are you running Mosca on? Are you on Windows (Mosca has not been battle-tested on Windows)?

Here is my broker module:

```js
var mosca = require('./')
var path = require('path')

var ascoltatore = {
  //using ascoltatore
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};

var settings = {
  port: 1883,
  backend: ascoltatore,
  persistence: {
    factory: mosca.persistence.Mongo,
    url: 'mongodb://localhost:27017/mqtt',
    ttl: {
      subscriptions: 1000 * 60 * 10,
      packets: 1000 * 60 * 10
    }
  },

  http: {
    port: 3000,
    bundle: true,
    static: path.join(__dirname, 'examples/ws/'),
  },
  logger: {
    level: 'debug'
  }
};

var server = new mosca.Server(settings);

server.on('clientConnected', function(client) {
  console.log('client connected', client.id);
});

// fired when a message is received
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});

server.on('ready', setup);

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running');
}
```

**Comment by bossqone** [comment]
So, used same configuration as you.
I connected from my laptop using websockets (desktop chrome) + mqtt.js node (mqtt://) - messages were delivered after reconnect to both clients without any problems.

But when I connected using websockets from my android phone - no messages after first reconnect.

**Comment by mcollina** [comment]
We are making progress! So it is an android specific issue. It is probably due to some bugs in MQTT.js rather than in Mosca. (Also coded by me, so keep blaming myself :P).

I do not have an Android device, so it's probably hardish for me to help on this one. I might try a simulator later on.
Anyway, can you try running the browser tests https://github.com/mqttjs/MQTT.js/blob/master/package.json#L28 on your android phone?

You can also try https://eclipse.org/paho/clients/js/ if you want.

**Comment by bossqone** [comment]
@mcollina I think that this issue can be closed
