### ISSUE TITLE
mosca offline messages limit

### ISSUE THREAD

**Issue by anishmenon** [mcollina/mosca#295]
is there any  quota settings per client ID of the user should set/edit dynamically . When it end up its not required to store offline messages to db . 

We are working on some android/iOS apps , where GCM / APNS not found to be the best solution for real time notifications . We think to setup a centerlized mqtt service on a server which can be communicated with any apps we develop in future .

**Comment by behrad** [comment]
we are doing actually the same @anishmenon however you should take this in mind that broker will disconnect your client when max_offline_messages exceeds ! 
So I don't think you can support offline quota with this broker feature.

**Comment by behrad** [comment]
you can find the maxInflightMessages: https://github.com/mcollina/mosca/wiki/Mosca-advanced-usage#other-options-of-mosca-the-ones-we-inserted-in-our-moscasettings-var

**Comment by anishmenon** [comment]
@behrad maxInflightMessages : here its a common value for all clients . how i can give separate value for different clients  with ClientID i recommend a database entry than a static value written on script

**Comment by behrad** [comment]
I'm afraid Mosca (and most of mqtt brokers) doesn't support per client values for maximum offline messages. I don't think MQTT says anything on this, so this would be a broker bonus feature.
@mcollina can elaborate more on this, he may also wanna accept a PR on this.

**Comment by mcollina** [comment]
Closing as it has been open for more than 1 year.
