### ISSUE TITLE
QoS1 without persistence not being handled properly?

### ISSUE THREAD

**Issue by bmcustodio** [mcollina/mosca#299]
Mosca supposedly supports QoS1 without external storage, as per

https://github.com/mcollina/mosca/blob/master/lib/server.js#L47

However, when using either the AMQP or the Mongo backends and no persistence, if I subscribe to topic A with QoS1 and then disconnect, messages sent to A with QoS1 by other clients while I'm offline are not being delivered. Am I overlooking something?

**Comment by mcollina** [comment]
QoS 1 is supported without a persistence, but offline mode is not. You have to set a persistence if you want to use AMQP.

**Comment by mcollina** [comment]
Of course, that comment in the doc is quite misleading, if you want to send a PR to amend that, feel free to do so :).
