### ISSUE TITLE
topic info not available in $SYS/+/new/subscribes payload

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#302]
`$SYS/+/new/subscribes`'s payload is currently the clientId, and no information of the subscribed topic is passed.

Changing the current payload to a json string containing the topic info seems to solve this https://github.com/mcollina/mosca/blob/master/lib/server.js#L256

**Comment by behrad** [comment]
if you are ok with the change I can open another PR after resolving #289

**Comment by mcollina** [comment]
I'm not very fancy on generating JSONs in these topics, but if you think it's a good idea, let's do it :).

**Comment by behrad** [comment]
Whats your proposal for the raw string payload for (un)subscribes where we have two fields `topic` and `qos` ?

1) Currently we can omit `qos` !?

2) invent a convention of concatenating of them?

!?

**Comment by mcollina** [comment]
let's just use a JSON then :)

Just a side note, have a look at the discussion in https://github.com/mcollina/mosca/pull/96.

**Comment by behrad** [comment]
can be closed now: https://github.com/mcollina/mosca/pull/324
