### ISSUE TITLE
Mosca delivering old packets as "offline" ones?

### ISSUE THREAD

**Issue by ghost** [mcollina/mosca#310]
Mosca seems to be delivering QoS1 packets already delivered (and ack'ed) once when a client disconnects and reconnects back again. These are the steps to reproduce:

1. `clientA` connects with clean session.
2. `clientB` connects with clean session.
3. `clientB` subscribes to `some/topic` with QoS1.
4. `clientA` publishes to `some/topic` with QoS1 and payload `1`.
5. `clientB` receives (and ack's) the packet with payload `1`.
6. `clientB` disconnects.
6. `clientA` publishes to `some/topic` with QoS1 and payload `2`.
7. `clientB` connects once again.
8. `clientB` receives both packets (`1` and `2`).

In step 8, from what I understand, `clientB` should only receive the packet with payload `2`. However, it receives both. Inspecting the persistence backend (it occurs with both Redis and Mongo) shows that the packet with payload `1` is not deleted between steps 5 and 6 (it is only deleted after step 8). Can you confirm this? Is this the expected behaviour?

**Comment by mcollina** [comment]
How long are you waiting before the steps 5, 6 and 7? There might probably be a race condition between your code and Mosca (also the ACK might be in flight and not delivered yet). If that's the case it's perfectly fine, as QoS 1 packets might be duplicated in these particular case.

**Comment by mcollina** [comment]
The packet is removed when the PUBACK is received by Mosca.

**Comment by behrad** [comment]
Don't think if I faced this on redis persistent, Are you sure aren't you passing `retain` flag for your first payload?

**Comment by bmcustodio** [comment]
As much as 1 minute between each (I did a few manual tests using a desktop
MQTT client). Also, no retained flag is being set.

**Comment by bmcustodio** [comment]
I don't think it has to do with clients not sending `puback`. I tried using
`mqtt-spy` and `mqttfx` (desktop) and with HiveMQ's client (browser) and
the behaviour is the same.

**Comment by mcollina** [comment]
I cannot reproduce it on MongoDB or memory. I am using MQTT.js or mosquitto cli tools.

**Comment by bmcustodio** [comment]
Just tried with `mqttjs`, the behaviour is the same. In one terminal pane

```
mqtt subscribe -h 192.168.1.5 -p 1883 -i mqttjs-bmcustodio-2 -q 1 --no-clean -t "something/#" -k 900 -l mqtt -v
```

At this point, in Mongo:

```
> db.subscriptions.find()
< { "_id" : ObjectId("55a92ead8b96fd37ddd9df28"), "client" : "mqttjs-bmcustodio-2", "topic" : "something/#", "qos" : 1, "added" : ISODate("2015-07-17T16:34:53.316Z") }
> db.packets.find()
< (nothing)
```

Now, in another terminal pane:

```
mqtt publish -h 192.168.1.5 -p 1883 -i mqttjs-bmcustodio-1 -q 1 -t "something/1" -m "1" -C mqtt
```

The message is received in the first pane. However, now in Mongo:

```
> db.packets.find()
< { "_id" : ObjectId("55a92ee18ecec3e50d6bb839"), "client" : "mqttjs-bmcustodio-2", "packet" : { "topic" : "something/1", "payload" : BinData(0,"MQ=="), "messageId" : "NylzWRGGF", "qos" : 1, "retain" : false }, "added" : ISODate("2015-07-17T16:35:45.932Z") }
```

If I exit the first pane and re-run the command, the message is still delivered.

**Comment by bmcustodio** [comment]
In case it matters, this is my broker:

```javascript
var http = require("http");
var mosca = require("mosca");

var config = {
 backend: {
  json: false,
  mqtt: require("mqtt"),
  type: "mqtt",
  url: "mqtt://127.0.0.1:11883" // This is RabbitMQ with the MQTT plugin.
 },
 persistence: {
   factory: mosca.persistence.Mongo,
   url: "mongodb://127.0.0.1:27017/mqtt-test" // This is a stock MongoDB setup.
 },
 port: 1883
};

var srvMqtt = new mosca.Server(config);

srvHttp = http.createServer();
srvMqtt.attachHttpServer(srvHttp);

srvMqtt.on("ready", function () {
 console.log("Mosca is now running...");
});

srvHttp.listen(3000);
```

**Comment by mcollina** [comment]
Probably it is due to:

```
 backend: {
  json: false,
  mqtt: require("mqtt"),
  type: "mqtt",
  url: "mqtt://127.0.0.1:11883" // This is RabbitMQ with the MQTT plugin.
 }
```

Which is not something that is well tested in production (at least by me).

Can you give it a spin using Mongo or Redis for the backend (or just nothing)?

**Comment by bmcustodio** [comment]
You're right. I just tried with the `amqp` and `mongo` backends and it works as expected. It seems to happen only with the `mqtt` one. Do you have any idea why?

I'd rather use the `mqtt` backend, but I can switch to one of the others for the time being.

**Comment by mcollina** [comment]
I have no specific idea, but if you want to send a PR, please do!
Il giorno ven 17 lug 2015 alle 19:50 Bruno M. Custódio <
notifications@github.com> ha scritto:

**Comment by kevingo** [comment]
@mcollina Do you know how to use mqtt.js client send `PUBACK` to the mosca borker ?

**Comment by kevingo** [comment]
Thanks.
