### ISSUE TITLE
Mosca fails to install because of missing browserify/uglify

### ISSUE THREAD

**Issue by bachp** [mcollina/mosca#316]
I tried installing mosca on a new virtual machine using: `npm install mosca`. And the installation failed during the `postinstall` step, which seems to execute the following command `browserify -r mqtt -s mqtt | uglifyjs --screw-ie8 > public/mqtt.js`.

From what I understand is that this to work it would require that browserify and uglify is already installed. An if I do a `npm install -g uglify` and `npm install -g browserfiy` the installation works.

This fact makes it unnecessary hard to deploy to [OpenShift](https://www.openshift.com/).
Could there be a better solution then this postinstall step? For example checking in the bundled version into npm or installing browserify/uglify executables during a normal npm install?

**Comment by mcollina** [comment]
I think I should move those in the prepublish hook, so the deps get built at publish time rather than at install time. This will reduce install time as well.

A PR is coming on that one, it should be straightforward.

**Comment by mcollina** [comment]
This should be fixed in latest master. Once I get in https://github.com/mcollina/mosca/pull/315 I will release 0.32 with the fix.

**Comment by bachp** [comment]
That was fast :smile: . I'm looking forward to version 0.32. Thanks.
