### ISSUE TITLE
Problem with Ascoltatori when starting application

### ISSUE THREAD

**Issue by Arilas** [mcollina/mosca#317]
I've use Mosca with MongoDB as Backend. And when client tries to connect before server is up, I've receive:
```
/.../node_modules/mosca/node_modules/ascoltatori/lib/mongo_ascoltatore.js:114
  this.collection.insert(messageObj, { w: 1 }, done);
                  ^
TypeError: Cannot call method 'insert' of undefined
```
It's looks like there's publish request about new client with format:
```
{ value: 'lens_MbdZIBdQ3TAVxD6REO20Ta2sk9p',
  topic: '$SYS/VkL9kaBt/new/clients',
  options: { qos: undefined, messageId: 'N1w9kpSY' } }
```
Before Collection is ready

**Comment by mcollina** [comment]
Can you paste the code that is giving you this error?

**Comment by Arilas** [comment]
I've have very simple application:
```js
import {Server, persistence} from 'mosca'
import resitify, {createServer} from 'restify'

var moscaBackend = {
  //using ascoltatore
  type: 'mongo',
  url: process.env.MONGO_URL,
  pubsubCollection: 'reading',
  mongo: {}
}

var moscaSettings = {
  port: 1883,
  backend: moscaBackend,
   persistence: {
     factory: persistence.Mongo,
     url: process.env.MONGO_URL
   }
};

class Application {
    constructor() {
        this.Server = createServer({ name: 'fsdf', version: '1.0.0' })
        this.Server.listen(8080)
        this.Broker = new Server(moscaSettings)
        this.Broker.attachHttpServer(this.Server);
    }
}

export default new Application
```
I've try to connect using MQTTLens (Chrome Application) through WebSockets. When I've start application without connection inside MQTTLens, everything works. But If I've try to restart server, I've receive this error.

**Comment by mcollina** [comment]
you should call `attachHttpServer(this.Server)` from within the callback passed to `new Server(moscaSettings, callback)`.

**Comment by Arilas** [comment]
Thanks, it's works. Can you update docs here - https://github.com/mcollina/mosca/wiki/MQTT-over-Websockets ?

**Comment by mcollina** [comment]
you can do that too :), it's a wiki!
