### ISSUE TITLE
Raw TCP and Websockets both on port 443

### ISSUE THREAD

**Issue by mishoboss** [mcollina/mosca#321]
Is it possible to have a raw TCP MQTT and MQTT over Websockets, both listening on port 443 (TLS)? The idea is that some strict firewall setups have only 80 and 443 ports enabled. I have hardware devices and a mobile app. Devices speak MQTT over raw TCP, and the mobile app speaks MQTT over Websockets. Is it possible to have them all on port 443?

**Comment by mcollina** [comment]
It is not currently possible, you need to use two ip addresses.

**Comment by mishoboss** [comment]
That means two running Mosca instances, right?

**Comment by mcollina** [comment]
You can run that setup on the same Mosca instance, you can have it listening on two different IPs. I would recommend two instances anyway.

**Comment by mishoboss** [comment]
Excuse me, but how should look like the Mosca settings object is I want to have one instance listening on same port of two different IPs? I just can't imagine this setup in my head. Thanks.

**Comment by mcollina** [comment]
You should pass them via the 'interfaces' key: https://github.com/mcollina/mosca/blob/master/examples/Server_Wtih_All%20Interfaces-Settings.js#L15-L20

**Comment by mishoboss** [comment]
Sorry, but I really can't understand how the IP mapping should be done. This sample settings doesn't show that. What do you mean by "IP" - a separate address for the same server machine running the same Mosca instance? If yes, couldn't this be somehow done via vhost or something? I really can't understand how this should be done. Can you describe the whole thing? The whole server topology and setup? Or give me a sample that covers this case. Thank you really much for the support.

**Comment by PritamUpadhyay** [comment]
@mcollina  meant  to say that you have to use two different **ports** for running HTTPS and MQTTS. You can not run both on same... @mishoboss

**Comment by mishoboss** [comment]
Hmm, I was leaved with the impression that in order to have the same port, I need two host names (IP addresses). Which makes sense. The tricky part is how to serve these two host names from the same Mosca instance? I think @mcollina had a solution of that? Or maybe I didn't understood him?

**Comment by mcollina** [comment]
@mishoboss you should just pass an `host` option for each interface.
