### ISSUE TITLE
Error: EMFILE, too many open files

### ISSUE THREAD

**Issue by tibotiber** [mcollina/mosca#322]
Hi Matteo,

My server is crashing with the following error after running for a long time (few weeks). Also even after restart, the crash will happen much faster than it took the first time. I am unsure where it comes from and thought you may have an idea...

```
/home/.../node_modules/mosca/lib/stats.js:157
    var mem = process.memoryUsage();
                      ^
Error: EMFILE, too many open files
    at null.<anonymous> (/home/.../node_modules/mosca/lib/stats.js:157:23)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

Thanks.
Thibaut.

**Comment by mcollina** [comment]
Hi Thibaut!

How many clients are you connecting? How it is configured the linux server?
It is probably an issue on the TCP kernel stack, leaving around zombie connections for too long.

**Comment by tibotiber** [comment]
Woaw! That's fast :).
We've got a dozen of clients only, those should usually be permanently connected (IoT gateways).
I am not sure what part of the server configuration you're requesting about.. what do you mean?

**Comment by mcollina** [comment]
The TCP settings for the server, which hosting provider are you using and generally if your Mosca code is doing something special (like opening a new connection on every published messages) and the like.

**Comment by tibotiber** [comment]
We're on digital ocean, Ubuntu 14.04, vanilla TCP stack, no special mosca code or config. I'm gonna check further on the TCP details. Thanks.

**Comment by cfan8** [comment]
Have you configured the keepalive argument? Using this enables the server to detect dead connnections.

**Comment by tibotiber** [comment]
Hi @cfan8, sorry I've missed your response. I don't remember having modified anything from the default keepalive argument. I'm also not sure at which level I'm supposed to do that? Is it mosca, node or Ubuntu/TCP? Thanks.

**Comment by tibotiber** [comment]
@mcollina I am currently using no pub/sub broker (storage in memory). Can this be related to the bug, would it be better switching to say Mongo? Thanks.

**Comment by cfan8** [comment]
@tibotiber I suggest you to switch to mongo or redis. This has been tested in production environment. Keepalive is a mqtt protocol level feature which can be configured at the client side.

**Comment by tibotiber** [comment]
Thanks, I'm gonna check/change all that.

**Comment by tibotiber** [comment]
Hi guys. FYI, switching from no pub/sub broker to the mongodb option solved this issue (no more issue for 10 days in production, used to crash every 20h or so before that)! Maybe a note should be put about this in the doc, not sure (?). Thanks a lot for your help.
