### ISSUE TITLE
Unexpected QoS downgrade, missing QoS handling callback and Retained messages not delivered 

### ISSUE THREAD

**Issue by cefn** [mcollina/mosca#327]
Hello again,

I've been struggling with the behaviour of a system I've built on MQTT.js and Mosca and gone back to basics to verify behaviour with a minimal test based on promise sequences which you can see at this gist... https://gist.github.com/cefn/747c7123c4c6a34e7775

In its current form it succeeds at end-to-end dispatching a ["Hello","World"] topic pair. However, to get this to work, several unexpected workarounds have been required...

* A downgraded QoS had to be accepted
* A missing QoS callback had to be ignored

The test does the basics
* Launches a server
* Launches a receiving client and listens to message events
* Subscribes the receiving client to a topic with QoS 2
* Launches a sending client
* Sends a retained message to the topic with QoS 2

When the code is run, it outputs the following...

Requesting QoS 2
QoS granted is: 1
No QoS callback from publish()
Message Received

I am also confused why if I put promiseSubscription() after promisePublication() then the test fails. If you switch the two 'then' clauses in the promise sequence then the test times out with no message received. I would expect a retained message to be dispatched regardless if the publication took place before the subscription.

What am I missing about the configuration which is causing Mosca to behave in this way (downgrade QoS, omit callbacks and fail to deliver retained messages)?

**Comment by mcollina** [comment]
QoS 2 is not supported by Mosca.
A future version will support it.
Il giorno dom 9 ago 2015 alle 16:06 Cefn Hoile <notifications@github.com>
ha scritto:

**Comment by cefn** [comment]
Thanks, Matteo. A few follow-up questions.

1. Should I raise the non-delivery of retained messages as a separate issue. This doesn't seem  connected to the QoS levels? I could be wrong that a subscriber to a topic with a previously-published retained message should be notified of that message. I thought that's what retained messages were all about. See the comment within the gist https://gist.github.com/cefn/747c7123c4c6a34e7775 to see how to cause the test to fail by switching the order of publishing and subscription. This fails even when QoS level 1 is explicitly requested.
2. If I can't work around double-delivery and I need a server with support for Websockets and QoS:2 do you have any suggestions? Can Mosca proxy for another MQTT server and provide support that way?

**Comment by mcollina** [comment]
Retained messages should work fine.

Try with QoS 1, QoS 2 may give unexpected results, and in case raise
another issue. Please don't include any other libraries in the example,
just MQTT.js and Mosca.

I'm on vacation till the 19th. I will look into that afterwards.
Il giorno dom 9 ago 2015 alle 18:20 Cefn Hoile <notifications@github.com>
ha scritto:

**Comment by cefn** [comment]
Understood. Having investigated some other server options I have an MQTT.js retained message test case which succeeds with Mosquitto (built with websocket support) but fails with Mosca, so should be worth looking at. I'll file as a separate bug.
