### ISSUE TITLE
retained & qos 1 offline messages return empty data

### ISSUE THREAD

**Issue by JoalePampala** [mcollina/mosca#329]
Hello. When i publish message with retain flag true and new clients connect.. he receive only empty data ... {"type":"Buffer", "data":[]} ... same thing with qos 1 offline, everything else work fine... qos 1 in keepalive interval works... but after reconnect client recieve {"type":"Buffer", "data":[]} again.

perstistance - mongodb last version with wiredtiger engine

Thx for help.

**Comment by Chipsi** [comment]
:+1:

**Comment by JoalePampala** [comment]
i tried redis as backend & persistance and it works...

**Comment by Chipsi** [comment]
As @JoalePampala said, works with redis store, but database for `backend` which stores several infromations of users, for example `userSubscribed`, `userConnected` etc...doesn't work. Redis database is still empty. This is my configuration:
```

**Comment by mcollina** [comment]
The database that stores anything on Redis is the the one specified in `persistence`. the `backend` wil always be empty.

**Comment by mcollina** [comment]
This has been inactive for more than 1 year. closing now, feel free to reopen.
