### ISSUE TITLE
Module not installing on Windows

### ISSUE THREAD

**Issue by ashwanikumar04** [mcollina/mosca#331]
Hello:
I am trying to install the module on Windows. But Getting the error:
..\fs-ext.cc(195): error C3861: 'fcntl': identifier not found
..\fs-ext.cc(379): error C3861: 'fcntl': identifier not found

This issue is related to https://github.com/baudehlo/node-fs-ext/issues/44.
Can anybody tell me how to fix this issue?

Thanks,
Ashwani

**Comment by mcollina** [comment]
That module come down from the 'optionalDependencies' (it's a dependency of qlobber-fsq).
So, Mosca should install fine even if installing that module errors.

Which version of Node are you using? NPM? OS?

**Comment by ashwanikumar04** [comment]
Thanks for the response.
I am using node v12.2 on Windows 7. Can I use Mosca even with this build error?

**Comment by mcollina** [comment]
Yes.

**Comment by ashwanikumar04** [comment]
Thanks :)
