### ISSUE TITLE
Persistence Messages Limit

### ISSUE THREAD

**Issue by Whitebeard86** [mcollina/mosca#335]
Hello,

I'm using Redis to save my application messages, the problem is only the last one is being saved, where can I increase this value?

Thanks,
J.

**Comment by mcollina** [comment]
Can you write an example of what are you trying to do? MQTT feature no 'saving' function, and persisting is done via retained messages or QoS=1/2  and clean=false.

**Comment by mcollina** [comment]
If this is related to #334, then only one retained messages is saved. This is by the MQTT spec.

**Comment by Whitebeard86** [comment]
Let's see if I understand correctly.

Redis is used for scalability only? The "persistent feature" only works for the last message? Is there any way to store more then just the last by configuration or I have to implement a system of my own?  

In my client i'm setting QoS to 1 and Retained = true. What's this Clean setting? It is client related as well? What  does it do?

Thanks.

**Comment by Whitebeard86** [comment]
I'm trying to do a chat application and I want the offline users to receive all the messages they didn't get while they were offline. Do you have any suggestion regarding the options mosca provides to do this?

Thanks.

**Comment by psorowka** [comment]
MQTT is probably not what you are searching for. I suggest to have a look at XMPP Protocol rather than MQTT for this usecase. Many features you would want for a chat application (online/away/offline signalling, queuing,....) are implemented there.

**Comment by mcollina** [comment]
@Whitebeard86 You should send messages with `retain: false`, and connect your client with `clean: false`, specifying a unique `clientId`. That will work as expected.

**Comment by Whitebeard86** [comment]
@psorowka I'll take a look, thanks for pointing it out. Any libraries you recommend?

@mcollina When I set those parameters none of the messages are saved (not even the last one).

**Comment by mcollina** [comment]
@Whitebeard86 the messages are saved only if the senders sends them with QoS 1, and the recipient is offline.

**Comment by Whitebeard86** [comment]
I'm doing it like you say but the result is the same, maybe there is a problem with my client library, can you recommend me one that you know that works? (javascript client)

Thanks.

**Comment by mcollina** [comment]
[mqtt](http://npm.im/mqtt) works fine, or also the Paho one works. You need to subscribe using QoS 1, also.

**Comment by Whitebeard86** [comment]
Ok thanks, I am going to use the one you refer. Do you have an example with all those configurations set?

**Comment by mcollina** [comment]
There are plenty in the MQTT.js unit tests.

**Comment by Whitebeard86** [comment]
Ok, I've made the following:

```
    var client;
      var topic = "mqtt/demo";

      function connect() {
        var input = document.getElementById("userText");
        client = mqtt.connect("myserverAdress", { clean: false, clientId: input.value}); // you add a ws:// url here
        input.enabled = false;

        client.on("connect", function() {
          console.log("client connected");
          client.subscribe(topic);
        });

        client.on("message", function(topic, payload) {
          console.log([topic, payload].join(": "));
        });
      }

      function sendMessage() {
        var input = document.getElementById("chatText");
        client.publish(topic, input.value, {qos : 1, retain: false });
        input.value = "";
      }

```

But again, no messages are being saved.. If I use retain: true, only the last shows.

**Comment by stableShip** [comment]
```
var client = mqtt.connect('mqtt://localhost:1883',{clientId:'1',clean:false});

client.subscribe('test',{qos:1});
client.on('message', function (topic, message) {
    console.log(message.toString());
});
```
in subscribe side,set ` clean:false ` it save for me~
