### ISSUE TITLE
Client Disconnecting Message Not Received

### ISSUE THREAD

**Issue by prerakmody** [mcollina/mosca#336]
var server = new mosca.Server(moscaSettings);
server.on('ready', setup);
server.on('clientConnected', function(client) {
      temptopic = 'some_topic'
      var packet = { cmd: 'subscribe',
       retain: false, qos: 1,messageId: 1,
       subscriptions: [ { topic: temptopic, qos: 0 } ]
      }
      //logger.info({'SERVERINFO':{'type':'manualSubscribe','id':client.id,'subscription':temptopic}})
      client.handleSubscribe(packet)
}

//nothing happens here when I abruptly power off my client
server.on('unsubscribed', function(topic, client) {
    logger.info({'SERVERINFO': {'type': 'unsubscribed','id': client.id,'topic': topic}
    });

//nothing happens here when I abruptly power off my client
server.on('clientDisconnected', function(topic, client) {
    logger.info({'SERVERINFO': {'type': 'unsubscribed','id': client.id,'topic': topic}
 });

I believe this would be enough to communicate the issue I am facing.

**Comment by mcollina** [comment]
Can you reproduce this with a MQTT.js client?

**Comment by prerakmody** [comment]
Ok, so it was a QOS = 1 issue on the subscriptions.
