### ISSUE TITLE
Is it possible to know Protocol being used by client?

### ISSUE THREAD

**Issue by maitrysh** [mcollina/mosca#340]
Is it possible to get the full requested url (or the connection request) sent by client on mosca's `client.prototype.handleConnect()` ?

I am trying to differentiate  MQTT or WS and MQTTS and WSS requests.

Thanks in advance.
~MS~.

**Comment by arnauorriols** [comment]
Same here, I need to differentiate when the requests come from WebSockets. Any ideas?

**Comment by mcollina** [comment]
Probably it is the only way. Would you like to send a PR to handle this features?

**Comment by maitrysh** [comment]
@arnauorriols: I am not able to access `client.connection.stream.socket.upgradeReq` object. It gives me error. Can you please give me some more details for accessing this?
Thanks.
@mcollina : Thanks.

**Comment by PritamUpadhyay** [comment]
@maitrysh  & @arnauorriols :you can try this work around.
````Javascript
// checks for request type. i.e websocket or mqtt request.
if (client.stream.socket) { // if websocket request found
       // checks for WSS port
        if (client.stream.socket.upgradeReq.headers['host'].split(":")[1].toString() == "3001") { 
            console.log("WSS request");
        }
        else{ 
            console.log("WS request");
        }
    }
    else { // if mqtt request found
         // checks for MQTTS port
        if (client.stream.server._connectionKey.split(":")[2].toString() == "8883") {
            console.log("MQTTS request");
        }
        else{ 
            console.log("MQTT request");
        }
    }
````

**Comment by PritamUpadhyay** [comment]
@maitrysh : if you want to know the requested url,
for _websockets_
`client.stream.socket.upgradeReq.headers['host']`
and for _mqtt_
`client.stream.server._connectionKey`

**Comment by maitrysh** [comment]
@PritamUpadhyay : :+1:  Thank you very much. This is what I was looking for. The example you gave is the exact thing what I wanted to implement.

Thanks a million.
~MS~.

**Comment by arnauorriols** [comment]
@mcollina @PritamUpadhyay Thanks for your feedback, and yes, I'll give it a go and work on a PR. Cheers!

**Comment by mcollina** [comment]
Thanks folks! :)
