### ISSUE TITLE
Mosca backed by mongodb on Azure issue

### ISSUE THREAD

**Issue by jaydeep17** [mcollina/mosca#341]
Recently I moved from DigitalOcean to Azure, and faced a strange problem, I wasn't able to receive messages after 7 or so messages.

So I tried the sample mosca code, below is the complete code I used to test.
```js
var mosca = require('mosca');

var ascoltatore = {
    //using ascoltatore
    type: 'mongo',
    url: 'mongodb://abc:xyz@dogen.mongohq.com:10050/some-db',
    pubsubCollection: 'ascoltatori',
    mongo: {}
};

var settings = {
    port: 1883,
    backend: ascoltatore
};

var server = new mosca.Server(settings);

function waitAndDo() {

    setTimeout(function() {

        var message = {
            topic: 'abc',
            payload: 'abcde', // or a Buffer
            qos: 1, // 0, 1, or 2
            retain: false // or true
        };
        server.publish(message, function () {
            console.log('done!');
        });

        waitAndDo();
    }, 2000);
}

server.on('clientConnected', function (client) {
    console.log('client connected', client.id);
    waitAndDo();
});

// fired when a message is received
server.on('published', function (packet, client) {
    console.log('Published', packet.payload);
});

server.on('ready', setup);

// fired when the mqtt server is ready
function setup() {
    console.log('Mosca server is up and running');
}
```

The code is simple, it just sends a message to topic `abc` every two seconds.

Here are the different scenarios I tried:

### 1) Local MongoDb
Installed mongodb locally on the same machine (Azure VM)
✔ It works perfectly! (I was able to receive messages)

### 2) Mosca over RAM
✔ Works as expected!

Note : "done!" printed in the publish callback, is executed everytime whether I receive a message or not.

From this I assumed may be there is a bug in the mongodb driver, so I tried the below code.

```js
var MongoClient = require('mongodb').MongoClient;

// Connection URL
var url = 'mongodb://abc:xyz@dogen.mongohq.com:10050/some-db';

var db = null;

function waitAndDo() {

    setTimeout(function () {

        var collection = db.collection('test');
        collection.find({}).toArray(function (err, docs) {
            if (err) {
                return console.error(err);
            }
            console.log('again');
            docs.forEach(function (doc) {
                console.log('found document: ', doc)
            });
        });
        waitAndDo();
    }, 2000);
}

// Use connect method to connect to the Server
MongoClient.connect(url, function (err, dbObj) {
    db = dbObj;
    console.log("Connected correctly to server");

    waitAndDo();
});
```

I tried to make this code similar as the above, so it queries the db every two seconds.

But that also works as expected!

P.S. : As mentioned I previously used DigitalOcean, it worked perfectly on it. I also tried it on AWS EC2, it works there also.

I'm kinda stuck here. Any help is appreciated.

**Comment by mcollina** [comment]
You should check which version of MongoDB you are running on Azure, and some other MongoDB settings. With the release of MongoDB 3, we have been several regressions :(.
