### ISSUE TITLE
paho android java mqtt client & mosca redis qos 1 clean false strange behavior

### ISSUE THREAD

**Issue by JoalePampala** [mcollina/mosca#342]
Hello. I tried paho java mqtt client with mosca & redis. With QoS 1 and cleanSession false.

quick example : 

1) server publish message "aaa" with qos 1
2) android client get "aaa"
3) client disable mobile network
4) server publish message "bbb" with qos 1
5) client enable mobile network & reconnect
6) client get message "aaa" and "bbb"

Client after reconnect always get message which recieved as first and then offline messages.

I tried same application with public mosquitto server and it works fine.

// update 
first message published to android client is always saved as undelivered packet in redis.. next messages are deleted successfully

// update 2
with javascript web client it works fine with mosca & redis ... i don't understand

**Comment by mcollina** [comment]
Extremely weird. You should probably check what is going on the wire between the two parties. A problem might be:

1. clientId are for some reason not indentical
2. the messageId gets changed somewhere

You should try reproducing this using https://github.com/mqttjs/mqtt-connection, which is a very low-level client.

**Comment by JoalePampala** [comment]
I tried mosca version 0.28.1 like on test.mosca.io server and it works
