### ISSUE TITLE
Support publish to specified clients

### ISSUE THREAD

**Issue by xiulunlin** [mcollina/mosca#345]
As mentioned in [issue#214](https://github.com/mcollina/mosca/issues/214).
It may be out of concept but would be very handy in many use cases.

I try to use internal forward method https://github.com/mcollina/mosca/blob/master/lib/client.js#L199, but I don't know how to handle those options, arguments and things like messageId properly in order not to cause side effects.

**Comment by mcollina** [comment]
The changes needed to support this will be quite complex, mainly for keeping the offline support working.

This would probably be in [aedes](http://github.com/mcollina/aedes), and at some point Mosca will run on its top.
