### ISSUE TITLE
[MongoDb] No more documents in tailed cursor

### ISSUE THREAD

**Issue by jaydeep17** [mcollina/mosca#346]
I use the following config for mosca.

```js
MongoClient.connect(mongo_url, {}, function (err, db) {
    var ascoltatore = {
        type: 'mongo',
        db: db,
        pubsubCollection: 'ascoltatori'
    };
    var settings = {
        port: 1883,
        backend: ascoltatore
    };
    var server = new mosca.Server(settings);
});
```

It is able to connect to the db successfully, messages are inserted in the collection, but none of the messages published by the server are received by the client.

**Edit:**
Same is the case when I use
```js
var ascoltatore = {
    type: 'mongo',
    url: mongo_url,
    pubsubCollection: 'ascoltatori',
    mongo: {}
};
```

Using Mosca `v0.28.2` & MongoDB `v2.4.12`.

**Update:**
Updated Mosca to `v0.32.0` and now I can receive first few messages, then it stops.
Again the messages are inserted in the mongo collection, but not received by the client.

**Note:** I'm running this code on my **local machine**, the client is also on the same machine, just MongoDB is on [compose.io](https://www.compose.io/)

**Update 2:**
I further dug into module ascoltatori and found that I'm getting the below error, after a few successful transmissions
```js
{ [MongoError: No more documents in tailed cursor]
  name: 'MongoError',
  message: 'No more documents in tailed cursor',
  tailable: true,
  awaitData: true }
```
further logs
```sh
ascoltatori:mongodb handleCursorClosed +1ms
ascoltatori:mongodb handleCursorClosed -> Wait for the database to be connected... +0ms
ascoltatori:mongodb handleCursorClosed -> Stats failed: MongoError: unauthorized +285ms
ascoltatori:mongodb handleCursorClosed -> Handle cursor failed: retry #1 +0ms
```

**Update 3:**
Downgrading node's mongodb driver to `v1.4.39` solves the problem.
But I didn't get a solution for `v2.x`
For more info : [MongoError: No more documents in tailed cursor](https://jira.mongodb.org/browse/NODE-435)

**Comment by mcollina** [comment]
Feel free to try it again on v2.0.0. It should probably be fixed.
