### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by xiulunlin** [mcollina/mosca#347]
I use mobile to connect to Mosca. Then I lock the screen and after serval minutes I unlock the screen and publish a message, it works. But If I do this after more than 10 minutes, the broker didn't receiver any message, and neither `clientDisconnected` nor `unsubscribed` event is fired.

I guess this might be a timeout problem? Any ideas on this?

**Comment by mcollina** [comment]
After a while you would get a `clientDisconnected` event. It also depends on the operating system settings for TCP, and on the keepalive value when you connect via MQTT.
Set up an agressive keepalive (5min?) and you would start seeing these events popping up.

**Comment by xiulunlin** [comment]
Thanks, I will have a try.@mcollina If I didn't set up a keepalive, will `clientDisconnected` event be fired when a `timeout` event of net.Socket occurs or if client dies?

**Comment by mcollina** [comment]
yes, also when the socket is closed by the OS

**Comment by xiulunlin** [comment]
I add `duplex.on('close', function(){console.log('close')})` in https://github.com/mqttjs/mqtt-connection/blob/master/connection.js#L33.
And I set up an 10s keepalive, then I cut off the network of client. After a few seconds I see `clientDisconnected` event is fired but the `close` event of duplex is not fired. 
Mosca does not destory net.Socket?
@mcollina
