### ISSUE TITLE
Retain Message Behavior

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#349]
Considering client A is offline and has an offline subscription to topic foo.
client B publishes two retain messages with qos=0 with contents C1 and C2.

Whats the correct behavior?

I was expecting the client A to see only C2 with he is back online, but Mosca is storing all retain message as offline messages too. so client A sees one C1 and two C2s !!!

This is clearly visible here https://github.com/mcollina/mosca/blob/master/lib/persistence/abstract.js#L54-L72

**Comment by mcollina** [comment]
You are right! Would you mind sending a PR to address this?

It's really a busy period for me, sorry about the absence :(.

**Comment by behrad** [comment]
Me busy too... :)) Ok, I need this, but need you to approve if my change isn't hurting anything.

Can we add an `else` so that not to storeOfflinePacket for retain messages !? is this safe:

```js
    if (packet.retain) {
      total++;
      that.storeRetained(packet, done);
    } else {
      that.storeOfflinePacket(packet, done);
    }
```

**Comment by behrad** [comment]
This looks more correct however:

```js
    if (packet.retain) {
      total++;
      that.storeRetained(packet, done);
    }
    if( packet.qos !== 0 ) {
      that.storeOfflinePacket(packet, done);
   }
```

**Comment by mcollina** [comment]
The first one is wrong, the second one is correct :).

Thanks!

**Comment by behrad** [comment]
@mcollina I can't remember why the later is more correct, but problem raises for retained, qos=1 messages.
we can't process/store/forward a single retain=true, qos=1 message twice.
I wonder what MQTT spec says on this kind of messages? since they both are retained, and should be acknoledged by QOS=1 way.
I think since this is a retained message we don't need storeOffline although qos=1

**Comment by mcollina** [comment]
@behrad I think the two things are independent. So, we should store it as retained, and for both offline consumption.

**Comment by behrad** [comment]
> I think the two things are independent

but the behavior in existence of both options should be clarified.


> So, we should store it as retained, and for both offline consumption.

storing message twice looks not ok to me, this way message will be forwarded to client twice.
I think we should check the spec and clarify the correct behavior for (retain=true & qos=1)

**Comment by mcollina** [comment]
> storing message twice looks not ok to me, this way message will be forwarded to client twice.
I think we should check the spec and clarify the correct behavior for (retain=true & qos=1)

So, we should store the message in the retained storage, but not forward retained messages on reconnect.

**Comment by behrad** [comment]
> but not forward retained messages on reconnect

if and only if the client has already received that retained messages. right?
If so, we are coupling forwardRetained to offline message handling, and this really complicates things.

**Comment by mcollina** [comment]
The two things should be completely independent. When a user subscribes it
receives retained messages. When a user reconnects receives everything that
has happened till that point.

The current codebase does handle this case poorly, I agree.
Il giorno sab 10 set 2016 alle 10:41 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
So a retained message only should be forward in reply to a SUBSCRIBE command?
