### ISSUE TITLE
[Nginx] Load Balancer problem

### ISSUE THREAD

**Issue by dophantrunghieu5** [mcollina/mosca#351]
Hi,

I have a problem when setup Nginx as a load balancer for mosca instances. 

**My purpose**:
+ Client -> requests with SSL -> Nginx -> Deliver requests to mosca instances.

**My setup environment**:
+ CentOS 7
+ 3 mosca instances run by systemd at ports 5000, 5003, 5006

I setup for over Web-Socket mosca instances successfully with below settings:

```
upstream mqtt_server {
    server 127.0.0.1:5000 fail_timeout=0;
    server 127.0.0.1:5003 fail_timeout=0;
    server 127.0.0.1:5006 fail_timeout=0;
}

location /mqtt {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_pass http://mqtt_server;
}
```
But when I setup mosca broker without over Web-Socket, above setup didn't work as I expected. I can connect to mqtt://my_host_name:5000/mqtt but cannot connect to mqtt://my_host_name/mqtt

I think this may be caused by wrong protocal(http) I setup in Nginx. I think it should be mqtt instead.  
But I don't know Nginx can be setup with mqtt protocal or not? 

I'm looking for your advices. 
Thanks.

**Comment by behrad** [comment]
you should configure mqtt ports as tcp upstreams, I don't know about the corresponding Nginx config but haproxy simple does this.

**Comment by mcollina** [comment]
Exactly as @behrad said. NGINX supports tcp upstreams in the "enterprise" version.
