### ISSUE TITLE
Can't use meteor user in mosca authentication methods

### ISSUE THREAD

**Issue by iascchen** [mcollina/mosca#356]
I created a mqtt mosca server as follow, but I can't use meteor collection in authentication() method, it will return Error: Can't wait without a fiber, here is my code :

    var ascoltatore = {
        //using ascoltatore
        type: 'mongo',
        url: 'mongodb://localhost:3001/mqtt',
        pubsubCollection: 'ascoltatori',
        mongo: {}
    };
    
    var settings = {
        port: 1883,
        backend: ascoltatore
    };
    
    var server = new mosca.Server(settings);
    
    var user = Meteor.users.find().fetch();  // this sentences works ok
    console.log("user", user); 
    
    // Accepts the connection if the username and password are valid
    var authenticate = function (client, username, password, callback) {
    
        console.log("user", username, password.toString());
    
        var user2 = Meteor.users.find({
                _id: "fCishK3WBCpPWvctY"
            }).fetch();   // this sentences throw Error: Can't wait without a fiber
        console.log("user", user2);
    };
    
    // In this case the client authorized as alice can publish to /users/alice taking
    // the username from the topic and verifing it is the same of the authorized user
    var authorizePublish = function (client, topic, payload, callback) {
        var ok = client.user == topic.split('/')[2];
        // we can alter the message here
        if (ok)
            callback(null, payload);
        else
            callback(null, false);
    };
    
    // In this case the client authorized as alice can subscribe to /users/alice taking
    // the username from the topic and verifing it is the same of the authorized user
    var authorizeSubscribe = function (client, topic, callback) {
        var ok = client.user === topic.split('/')[2];
        callback(null, ok);
    };
    
    // fired when the mqtt server is ready
    function setup() {
        server.authenticate = authenticate;
        server.authorizePublish = authorizePublish;
        server.authorizeSubscribe = authorizeSubscribe;
    
        console.log('mCotton mqtt server is up and running');
    }
    
    server.on('ready', setup);
    
    server.on('clientConnected', function (client) {
        console.log('mqtt client connected', client.id);
    });

**Comment by mcollina** [comment]
I do not use meteor, and the error seems definitely meteor specific. Unfortunately, I can't help.

I would suggest to expose the functions that you need to call from Meteor in an HTTP API, and then call them from your Mosca broker.
