### ISSUE TITLE
API to count/list offlineMessages by clientId

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#358]
@mcollina Is this ok to propose a PR to expose an application API so apps can list/count offlineMessages by clientId?

**Comment by mcollina** [comment]
This is already implemented in Aedes: https://github.com/mcollina/aedes/blob/master/lib/persistence.js#L128-L130

I'm ok in bringing it here as well :).

**Comment by behrad** [comment]
that would be grate to bring it to mosca, since I'm still running on mosca until Aedes gets ready for production.

**Comment by behrad** [comment]
However that is counting offline clients, not offlineMessages persisted for a client

**Comment by mcollina** [comment]
@behrad you can get that with https://github.com/mcollina/aedes/blob/master/lib/persistence.js#L115.

I'm in to review merge that feature :D.

**Comment by behrad** [comment]
Not exactly @mcollina , We should count stored offline messages by clientId by subscritionId in each persistence engine...

**Comment by mcollina** [comment]
@behrad I think we can close this.
