### ISSUE TITLE
redis ascoltatore topic no method

### ISSUE THREAD

**Issue by nottledim** [mcollina/mosca#364]
redis_ascoltatore.js fails at line 135 complaining that 'topic' has no method 'replace'. I'm using the redis variant example of a server  from the basic wiki and publishing a message using the example from node mqtt (https://www.npmjs.com/package/mqtt).  I get the same error if publishing a message from an arduino-esp8266 client.

I don't get this error with mongo ascoltatore.

node v 0.10.29 (Debian)

Sorry if that's a bit vague but I'm in "lets try this out to see how it works" mode (and it doesn't) :-)

Mosca server is up and running
client connected arduinoClient
Published arduinoClient

/usr/local/lib/node_modules/mosca/node_modules/ascoltatori/lib/redis_ascoltatore.js:135
        topic = topic.replace(new RegExp('/$'), '');
                      ^
TypeError: Object $SYS/EJ6RvbC1e/new/clients/ has no method 'replace'
    at Object._onImmediate (/usr/local/lib/node_modules/mosca/node_modules/ascoltatori/lib/redis_ascoltatore.js:135:23)
    at processImmediate [as _immediateCallback] (timers.js:336:15)

**Comment by sguilly** [comment]
Same issue with redis > 2.0.0

Work fine with redis 1.0.0

change in your package.json
 "redis": "1.0.0"

and npm install (to downgrade the redis package)

**Comment by mcollina** [comment]
Should be fixed since some versions.
