### ISSUE TITLE
how to change the packet.payload before forward to client

### ISSUE THREAD

**Issue by hisway** [mcollina/mosca#368]
when a client submit an message to broker,I want to change the packet before to be published.
I find `Server.prototype.publish` in server.js ,how to do this?

**Comment by paularmand** [comment]
Can this help you on your way?

```
server.publish = function publish(packet, client, callback) {

  console.log("in publish");
  console.log(packet);
  var that = this;
  var logger = this.logger;

  if (typeof client === 'function') {
    callback = client;
    client = null;
  } else if (client) {
    logger = client.logger;
  }

  if (!callback) {
    callback = nop;
  }

  var newPacket = {
    topic: packet.topic,
    payload: packet.payload,
    messageId: this.generateUniqueId(),
    qos: packet.qos,
    retain: packet.retain
  };

  var opts = {
    qos: packet.qos,
    messageId: newPacket.messageId,
    dukt_origin: dukt_origin
  };

  if (client) {
    opts.clientId = client.id;
  }

  that.storePacket(newPacket, function() {

    if (that.closed) {
      logger.debug({ packet: newPacket }, "not delivering because we are closed");
      return;
    }

    that.ascoltatore.publish(
      newPacket.topic,
      newPacket.payload,
      opts,
      function() {
        that.published(newPacket, client, function() {
          if( newPacket.topic.indexOf( '$SYS' ) >= 0 ) {
            logger.trace({ packet: newPacket }, "published packet");
          } else {
            logger.debug({ packet: newPacket }, "published packet");
          }
          that.emit("published", newPacket, client);
          callback();
        });
      }
    );
  });

```

@mcollina , I'm far from an expert at javascript (and the scoping rules), but I think that the storePacket and ascoltatore.publish should be using the newPacket (instead of packet). I've already changed the code in the example above to help. Can you please advise, so that I'm not giving the wrong advice to the OP ?

Ps: I believe the client.js will also use it's own version of the packet, so better check that the client (or more exact, the representation of the client) isn't doing a forward based on the original packet. See this.forward = function(topic, payload, options, subTopic, qos, cb) in client.js

**Comment by mcollina** [comment]
I'm not getting your point :D.

Send a PR, and we'd discuss in there.

**Comment by rahulbhanushali** [comment]
@paularmand This still does not solve the problem.

**Comment by paularmand** [comment]
Did you follow up in https://github.com/mcollina/mosca/pull/403 for this? 
Please also note mcollina's comment towards to other code that would need to be changed.

**Comment by mepdr** [comment]
With v1.1.2 I tried to modify packet.payload in server#published event but as expected it didn't work.
After https://github.com/mcollina/mosca/pull/403, hpw is it possible to modify the published message before sending it to the clients ?

**Comment by paularmand** [comment]
Just looking at my previous response

> Ps: I believe the client.js will also use it's own version of the packet, so better check that the client (or more exact, the representation of the client) isn't doing a forward based on the original packet. See this.forward = function(topic, payload, options, subTopic, qos, cb) in client.js

I haven't got the code on the top of mind, and no time to dig into it now, but I believe that you should make sure the correct packet topic and payloads are being used in this function when you want to alter them.

**Comment by ccravens** [comment]
+1

This feature came up for us as a pretty critical immediate need and would like to start a discussion on how best to go about implementing and merging into a future version of Mosca and getting a PR merged.

**Comment by mcollina** [comment]
@ccravens this feature is already present on Aedes (at some point I will rebase mosca on top of it) https://github.com/mcollina/aedes#instanceauthorizepublishclient-packet-doneerr. As of _how_ it should be implemented, refer to that one.
