### ISSUE TITLE
web socket example

### ISSUE THREAD

**Issue by knodeit** [mcollina/mosca#369]
I've installed mosca and use two simple clients from NodeJS they all work great.
Now i want another simple nodeJS server with Express to render a HTML page which will simply log the message after subscribing to presence.
I've tried various examples but always get message that mqtt can not be found

can someone make a working example 
This doesn't work
<html>
<head>

</head>
<body>
<script src="./public/browserMqtt.js"></script>
<script>
	var client = mqtt.connect();

	client.subscribe("presence");

	client.on("message", function(topic, payload) {
		//alert([topic, payload].join(": "));
			alert('hi');
	});

	client.publish("presence", "hello world! I'm a browser");
</script>
</body>
</html>

**Comment by mcollina** [comment]
Unfortunately I have very little time to build that example.
Regarding the MQTT.js not found issue, you can build your own with https://github.com/mqttjs/MQTT.js#browser

If you managed to do it, would you mind sending a PR with an example? Thanks!

Hope that helps.
