### ISSUE TITLE
Auth Publish denial issue

### ISSUE THREAD

**Issue by OrahKokos** [mcollina/mosca#370]
Hello,
I'm writing some auth on subscribe and publish, however there is some trouble when publishing is denied.
Namely when calling ```return callback(null, false)``` (authorizePublish), the MQTT client publish callback gets called (with no args) and the client loses connection. 
Is it possible to not get disconnected but rather get something like subscribe has ```callback(err, granted)``` so some damage control can be implemented on the client side?

Hope to hear from you soon.

**Comment by mcollina** [comment]
No, it's not possible. The MQTT protocol does not support that.
