### ISSUE TITLE
Websocket Connection Failed

### ISSUE THREAD

**Issue by ccravens** [mcollina/mosca#371]
Hello,

I'm brand new to Mosca, so I might be approaching this incorrectly, but I'm trying to use the "attachHttpServer()" method with my express app. The mosca server starts, but I can't connect to it using mqtt.js.

Here's an example of what I'm doing on the server to attach the Mosca server to the Express HTTP server:

```javascript
	var mosca = require('mosca');
	var app = express();
	var pubsubsettings = {
	  type: 'mongo',
	  url: 'mongodb://localhost:27017/app',
	  pubsubCollection: 'mqtt',
	  mongo: {}
	};

	var server = new mosca.Server({
		backend: pubsubsettings
	});
	server.attachHttpServer(app);
	app.listen(3000);
```

I then attempt to connect to my Mosca server via a browser with the following client-side code based on mqtt.js:

```javascript
	var client = mqtt.connect('mqtt://localhost:3000');
```

But I get the following error in Chrome:
**WebSocket connection to 'ws://localhost:3000/' failed: Connection closed before receiving a handshake response**

I'd like to be able to communicate with Mosca on the same port as the express HTTP server so that we can easily deploy to environments such as Heroku and not have to manage two separate ports for HTTP and for Mosca (websockets). I have done this with other pub/sub applications such as SocketCluster. Would love to see the same thing in Mosca if possible.

Any guidance is much appreciated, thanks!!

**Comment by mcollina** [comment]
You need to call `attachHttpServer` on an instance of https://nodejs.org/api/http.html#http_class_http_server. Basically what is returned by `http.createServer()`. It's easy to setup express to do that.
