### ISSUE TITLE
MessageId generation using a lot of cpu time

### ISSUE THREAD

**Issue by platy** [mcollina/mosca#372]
I have been profiling mosca with a bunch of devices and it looks like 12% of samples were in Server.publish in crypto.randomBytes.

It looks like this is for generating the messageId in shortid. Is this necessary for all messages or could it just be done for those with retain=true (and then maybe only if not using a memory persistence)?

```javascript
  var newPacket = {
    topic: packet.topic,
    payload: packet.payload,
    messageId: this.generateUniqueId(),
    qos: packet.qos,
    retain: packet.retain
  };
```

I tried removing the messageId and no tests failed - (except the mongo and redis tests which I failed to setup)

**Comment by mcollina** [comment]
I agree. However, this is difficult to solve in the current system. A new version (almost a complete rewrite) would solve the problem. The new version is already 5x faster than this one. You can find the 'core' part at https://github.com/mcollina/aedes.

That id is used to disambiguate when using an external backend, and it has been completely removed in aedes.

**Comment by platy** [comment]
Ok, nice to know. I didn't know about Aedes, I like the looks of the api - I'll give it a try some time soon.
