### ISSUE TITLE
Node v4 Compatability

### ISSUE THREAD

**Issue by benjaminjt** [mcollina/mosca#373]
I understand we're probably being held back by dependency compatibility, but support for node.js v4.x.x would be really nice. Is this on the horizon?

**Comment by behrad** [comment]
I am currently running Mosca on v4.1.x and v4.2.x @benjaminjt , and seems no problem for a month or two :)

**Comment by benjaminjt** [comment]
Oh, thanks @behrad! Please excuse my naivety. My assumption was based on errors I see during `npm install mosca` in my v4.2.2 environment, that don't occur when running in v0.12.7. I figured this was the reason v0.10 and v0.12 are quoted explicitly in the README. I'll see if I can set up a fork to pass CI tests using v4.2.

**Comment by benjaminjt** [comment]
I reproduced the `npm install mosca` errors from my environment on travis; see lines 211-423 from https://travis-ci.org/benjaminjt/mosca/jobs/91333122#L221

With that said, those errors may not be related to that particular CI test failure.

**Comment by iOiurson** [comment]
Hello there !
I'm having the same kind of issue as @benjaminjt: just upgraded from Node v0.10.40 to v4.2.1, and i can't get mqtt.js nor mosca.js installed correctly.

**Comment by mcollina** [comment]
MQTT.js should work fine, on Mosca.. I will get that sorted asap :(.

**Comment by mcollina** [comment]
Fixed in v1.0.0

**Comment by benjaminjt** [comment]
Awesome :smile:
