### ISSUE TITLE
handling mosca-server's internal failure

### ISSUE THREAD

**Issue by mudassir-ngineous** [mcollina/mosca#377]
Consider because of some reason my mosca server gets down but still my nodejs service is up and running. Is there any way to catch the event when mosca server gets down. If there, how can i do that.

**Comment by mcollina** [comment]
I don't understand what the problem is. How does it gets down? Why it gets down? So you have a node.js process that is running Mosca and something else, and mosca goes down?

**Comment by mudassir-ngineous** [comment]
Yes I have a node.js process that is running Mosca server, the node.js service runs Mosca as mqtt-broker and whenever a message comes it passes the message to some message handler, which subsequently does other stuff related to message. But it usually happens that mosca-server gets down because of some exceptions like NO Memory on server etc and then client fails to connect with mqtt-server. How can I track such failures events of Mosca and take appropriate action and log the failures to monitor my server.

**Comment by mcollina** [comment]
These errors will get logged to stdout. You should restart your broker using tools like: upstart, monit, pm2. Usually these tools have ways to redirect the logs to files, so that you can access them later.
