### ISSUE TITLE
When would wss support be ready for aedes?

### ISSUE THREAD

**Issue by shailen1** [mcollina/mosca#378]
@mcollina Ran aedes yesterday with 20000 clients sending 1 msg/sec each and aedes kept up and did NOT drop any of them which mosca unfortunately seems to be doing. Consequently, we can't use mosca in production.

We'd however like to use aedes, considering it's a complete rewrite: hence the question.

Thank you for an answer at your earliest convenience.

**Comment by mcollina** [comment]
Aedes runs on streams, so you can already do that using https (from node)
and websocket-stream.
Il giorno ven 4 dic 2015 alle 18:26 shailen1 <notifications@github.com> ha
scritto:
