### ISSUE TITLE
Client object is undefined in published function

### ISSUE THREAD

**Issue by bastisk** [mcollina/mosca#380]
Hi there,
i used the authenticate function to save additional data to the client element. 

Now I am trying to get the client object in the server.on published function as it is described in Mosca documentation here(3) in order to get the information on every publish.

When running my sample(1) the client object is undefined in the published function.
Confusingly it is available in the connect function (see console output (2)). 

### Links
(1) Sample Code - https://gist.github.com/bastisk/54ca64874c93cfb5b294
(2) Console Output - https://gist.github.com/bastisk/c773c01b26c48c952acb 
(3) Mosca Documentation - https://github.com/mcollina/mosca/wiki/Mosca-basic-usage

### Environment
OS: Windows Server 2012 64bit
Node-Version: v4.2.2

**Comment by mcollina** [comment]
This is normal, and probably the docs is wrong. If you publish using `publish` (this happens for stats), `client` will be null.
