### ISSUE TITLE
Unsubscribe did't work as I expected.

### ISSUE THREAD

**Issue by tedqiao** [mcollina/mosca#382]
Hi,
i got an issue, I was trying to build website that supports chatting , everything worked fine until i tested the unsubscribe.
test steps:
  1 connect to mosca broker
  2 sub a topic:'topic'
  3 pub a message to topic:'topic'(client can receive that message)
  4 unsubscribe 'topic' (in mongodb the 'topic' subscription was still there )
  5 pub a message to topic:'topic'(client cannot receive those messages, looks fine now)
  6 disconnect to broker
  7 connect to broker again
  8 all message i sent to 'topic' that i have unsubscribed popped up(this was not what i expected, i expect that once a client unsubscribes a topic, that client no long can receive any message from that topic )

my english sucks, hope you can understand what i am trying to say and help me out.

**Comment by wujin099** [comment]
Hi,tedqiao:I meet the same problem,I don't know why, Did you have the solution for this ?

**Comment by tedqiao** [comment]
Hi wujin
What I know so far is that mosca will not remove the subscription in mongodb while you unsubscribe one it only remove that subscription in broker and broker won't keep the information as client disconnect with it. And the broker will retrieve subscriptions from mongodb every time you make connection to broker. Therefore, all message will pop up while client connect to broker again. I think you have to remove the subscription from mongodb on your own when you unsubscribe a topic.  I cannot guarantee everything I said is correct, but it works for me. hopes this can help you out.

**Comment by mcollina** [comment]
@tedqiao I don't think that should happen. I have little time to fix this, if you have time to send a PR I'll get that reviewed.

**Comment by wujin099** [comment]
@tedqiao today I test the subscription and unsubscription of topoic, I found that the format of topic affect the result, I use 'subcategory/100002' as the topic ,but subscription and unsubscription has problem, but when I change the topic format to 'subcategory-100002', the subscription and unsubscription can work correctly.

**Comment by mcollina** [comment]
It should be fixed in #391

**Comment by mcollina** [comment]
@xthuan Can you please open another issue, attaching a gist or github repo with a sample program showing the issue?
