### ISSUE TITLE
Retained packet is also being stored as offline

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#383]
Another issue still exists with retain messages in Mosca @mcollina and that is retained messages should not be stored as offline, or mosca will forward the message twice when client connects. (once via forwardRetained, and once with forwardOffline)
I should add an `else` here:
https://github.com/mcollina/mosca/blob/2694214e230a6b1febfd40fa55c7d33d40876fb0/lib/persistence/abstract.js#L67-L74

**Comment by behrad** [comment]
I'm waiting for your ack, to create a PR

**Comment by mcollina** [comment]
Fixed in v1.0.0

**Comment by behrad** [comment]
@mcollina This should have been fixed but why not????
https://github.com/mcollina/mosca/blob/master/lib/persistence/abstract.js#L67-L75

**Comment by behrad** [comment]
We should re-open this

**Comment by behrad** [comment]
Oh I found this discussion: https://github.com/mcollina/mosca/issues/349

**Comment by mcollina** [comment]
Is this still the case, why we should reopen? Is this not what https://github.com/mcollina/mosca/issues/540 is about?

**Comment by behrad** [comment]
> Is this not what #540 is about?

No, it is related to #349

**Comment by mcollina** [comment]
can yu please open a new issue then? There are two new bugs, and two hold issues involved.
