### ISSUE TITLE
Client Authentication with mosca broker

### ISSUE THREAD

**Issue by Ctvidyak** [mcollina/mosca#386]
We are using node.js' Mosca broker module for one of our applications. We are planning to add client authentication with a certificate on the broker side but I'm unable to find any configuration or settings in Mosca has for client authentication.

 If the client is passing certificate then what is way to get the same at mosca broker side.Like in node js http request req.connection.getPeerCertificate() will give me the client certificate and then I use the same to check the client authenticity

**Comment by 50774283** [comment]
You can try do it.

web page client:
var client = mqtt.connect('ws://localhost:3000', {username:'1',password:'2'});

node.js client
var client = mqtt.connect('tcp://localhost:1883', { username: '1', password: '2' });

Mosca broker

var settings = {
    port: 1883, 
    http: {
        port: 3000,
        bundle: true,
        static: './'
    }
    //backend: ascoltatore
};

server.on('ready', function () {
    console.log('Mosca server is up and running');
    server.authenticate = function (client, username, password, callback) {
        callback(null, (username === '1' && password.toString('ascii') === '2'));
    };
});

**Comment by Ctvidyak** [comment]
@50774283  I have implemented authentication with username and password .i need to include client certificate as well with username and password .Is there any way to work with client certificate?

**Comment by 50774283** [comment]
@Ctvidyak 
I think may could you to visit the link below
http://mcollina.github.io/mosca/docs/lib/server.js.html#Server
That constructor function have provide "secure" option.

**Comment by Ctvidyak** [comment]
@50774283  Secure option in mosca provides server side ssl authentication.Where in we can pass server certificate and server key .

**Comment by mcollina** [comment]
This should be fixed in v1.0.0. Please check and reopen if that's not the case.

**Comment by ignjat** [comment]
Is there configuration for client side certificates now? I am interested in using CRLs for client certs.

**Comment by mcollina** [comment]
You should be able to pass all options related to ssl defined in https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

**Comment by spmohan77** [comment]
I tried the TLS CRL option using Mosca. But it is updating the latest CRL after server restarts only. Is there any other way to fetch the latest CRL without server restarts?

**Comment by mcollina** [comment]
@spmohan77 that is a question generic to Node, check out https://nodejs.org/api/tls.html

**Comment by Yuu94** [comment]
Hello.
Is it possible to client authenticate using SSL certificates between Mosca and IoT devices now?
