### ISSUE TITLE
Redis 2.3.0 + STATS - 'Argument must be a string'

### ISSUE THREAD

**Issue by sguilly** [mcollina/mosca#387]
With redis : 2.3.0
Same issue as https://github.com/mcollina/mosca/issues/260

```javascript
Stats.prototype.wire = function wire(server) {
...
function doPublish(topic, value) {
      server.publish({
      topic: "$SYS/" + server.id + "/" + topic,
     payload: "" + value
    });
  }
...
doPublish("started_at", ""+server.stats.started.toISOString());
```

--> Generate 

"message":"Argument must be a string","name":"TypeError","stack":"TypeError: Argument must be a string\n    at TypeError (native)\n    at Buffer.write (buffer.js:535:21)\n    at writeStringNoPos (/backend/node_modules/mqtt-packet/generate.js:547:10)...

Work fine with : 

```javascript
function doPublish(topic, value) {
      server.publish({
      topic: "$SYS/" + server.id + "/" + topic,
     payload: JSON.stringify(value)
    });
  }
```

**Comment by mcollina** [comment]
Redis 2.3 is not supported, I presume. It's very old and ancient.

**Comment by sguilly** [comment]
Sorry, 

node_redis : 2.3 (30 Oct 2015) and +

**Comment by mcollina** [comment]
Would you please test it with version 1.0.0 of Mosca just released?
