### ISSUE TITLE
Integrate with express-ws

### ISSUE THREAD

**Issue by rushidesai** [mcollina/mosca#390]
Would be awesome if I could do something like this:

```javascript
import express as 'express'
import expressWs as 'express-ws'
import mosca as 'mosca'

let mqttServer = new mosca.Server(/*... */)

let app = express()
expressWs(app)

app.use(/* my middlewares */)
app.get(/* some route */)
app.ws('/mqtt', function(ws, req) {
  mqttServer.attachWebsocket(ws)
})
```

**Comment by mcollina** [comment]
This would probably be possible in the next major version of Mosca.

It is already possible with its new core (see [Aedes](http://npm.im/aedes)), because it is fully stream-based. Just pass the `ws` stream to the `server.handle()` function.
