### ISSUE TITLE
about  topic.replace is not a function??

### ISSUE THREAD

**Issue by jonahzheng** [mcollina/mosca#397]
## sys info
debian 7 64bit
nodejs v4.2.2
node-gyp v3.0.3

## ===sever code===
var mosca = require('mosca');

var ascoltatore = {
  type: 'redis',
  redis: require('redis'),
  db: 12,
  port: 6379,
  return_buffers: true, // to handle binary payloads
  host: '192.168.1.15'
};

var moscaSettings = {
  port: 1883,
  backend: ascoltatore,
  persistence: {
    factory: mosca.persistence.Redis,
    host:'192.168.1.15',
    port:'6379'
  }
};

var server = new mosca.Server(moscaSettings);
server.on('ready', setup);

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running')
}

server.on('clientConnected', function(client){
    console.log('client connected', client.id);
});

server.on('published', function(packet, client) {
 	console.log('Published', packet.payload);
});
 

## ====client code====
var mqtt    = require('mqtt');
var client  = mqtt.connect('mqtt://192.168.1.15:1883');

client.on('connect', function () {
  client.subscribe('presence');
  client.publish('presence', 'Hello mqtt');
});

client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString());
  client.end();
});

## ====debug info====
root@debian:~/msc# nodejs index.js
Mosca server is up and running
client connected mqttjs_bd8eeb36
Published mqttjs_bd8eeb36
/root/msc/node_modules/mosca/node_modules/ascoltatori/lib/redis_ascoltatore.js:135
        topic = topic.replace(new RegExp('/$'), '');
                      ^

TypeError: topic.replace is not a function
    at Immediate._onImmediate (/root/msc/node_modules/mosca/node_modules/ascoltatori/lib/redis_ascoltatore.js:135:23)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by mcollina** [comment]
Fixed in 1.0.0

**Comment by jonahzheng** [comment]
Wow, you are so great!
thank you
