### ISSUE TITLE
[Question] Listen on both 1883 and 8883 port?

### ISSUE THREAD

**Issue by JokerQyou** [mcollina/mosca#398]
Hi, I'm here to ask a question about TLS configuration. 

I expect Mosca to listen on 1883 for MQTT connections as well as on 8883 for secured MQTT connections, configured as follows:

```js
var settings = {
    port: 1883,
    id: 'mosca-broker',
    stats: true,
    logger: {
        level: 'info'
    }
};
if(ssl_key && ssl_cert){
    settings.secure = {
        keyPath: ssl_key ,
        certPath: ssl_cert
    };
    settings.https = {
        port: 9001
    };
}else{
    settings.http = {
        port: 9001
    };
}
```

But the result is, Mosca only listens on 8883 for secured MQTT connections, port 1883 is not opened at all. 

Is this behavior intentional? If so, can I configure Mosca to listen on both ports? If I enabled TLS, does that mean I can only communicate with Mosca via secured MQTT?

**Comment by psorowka** [comment]
Instead of the `port` option, use:

```
  interfaces: [
   { type: 'mqtt', port: 1883 },
   { type: 'mqtts', port: 8883 }
  ]
```

This will make mosca listen on both ports concurrently

**Comment by JokerQyou** [comment]
Thanks! I did not notice that Mosca has implemented a new set of options, besides, I'm using a pretty old version. I'll update Mosca and give it a try tomorrow.

**Comment by psorowka** [comment]
Actually the wiki pages / README aren't very clear on this. I'll write myself a note that this should be updated.

On the other hand, mosca 1.0.0 was released just today with a lot of improvements, so it should be worth updating.
