### ISSUE TITLE
Mosca not deleting messages from redis when using mosquitto as a Pub/Sub

### ISSUE THREAD

**Issue by Debdutto** [mcollina/mosca#404]
So, I have a setup where I'm using mosca and it's available hooks to build my application on nodejs. Where I am using mosquitto as the Pub/Sub and redis as the persistence.

Now, the issue is that when a client is connected and subscribed to a topic, any messages that are published to the topic are delivered to the subsciber but are not deleted from redis. So, when the client connects again the messages are re-delivered.

The core issue is that when it's storing messages into redis it's storing with a messageId generated using shortid (like 'NyVaBDxtg', 'E1lV6HPgKx', etc) but when it's trying to remove them from redis it's making it's key using a simple messageId (like '1', '2', etc).

As far as my understanding, when publishing to mosca messages are stored in redis with a messageId generated using shortid (example 'NyVaBDxtg'), then published using Ascoltatore to mqtt, when the puback comes from ascaltatore that the message has been delivered, it's trying to deleteOfflineMessages with a different messageId (example '1'). And hence it's not able to delete messages which have already been delivered.

**Comment by mcollina** [comment]
Would you like to send a PR to address this issue?

**Comment by Debdutto** [comment]
Okay. So, I did a little more digging.

It appears that ascoltatore is using mqtt.js to publish to the mosquitto broker. And since mqtt.js generates it's own messageIds. It's not able to map it to the mosca generated messageIds using shortid.

As far as I can see, we have 3 options:

* send pull-request to mqtt.js to modify the publish implementation, so that it can take it client generated messageIds
* Use a forked version of mqttjs so that it can take in clientIds on publish
* Align mosca generated Ids to the one mqtt.js generates using nextId (I don't think this will be good)
* create and maintain some kind of map between the two ids. (Which seems a little too complex for such a simple thing.

Let me know if I'm wrong anywhere.
I don't know if there's any other option. I'm willing to help, can you please guide me with this?

**Comment by mcollina** [comment]
I'm the lead maintainer of MQTT.js, just to clarify :).

MQTT.js is fine as it is, and it handles messageIds in its own way (good for a client), but I'll be more than happy to add "bridge" mode support in there (see #25 and Mosquitto). Beware that the shortids are not easily convertible to 2 bytes messageId (as defined in the MQTT spec).

I think that the only solution is to map ids, or ditch MQTT.js in ascoltatori completely, and just go with a straight implementation of mqtt using mqtt-packet.

**Comment by rahulbhanushali** [comment]
@mcollina I am looking forward to use mosca in production. However, I am facing the same issue and its very critical for me to fix this before I can use this in production.

I am looking forward to fix this issue and create a PR for the same.

As suggested by you, I am looking forward to use a map of the message id's generate for the newPacket  and by MQTT.js. However, after digging deep at the code, I have realised that the MQTT.js does not expose the new id generated to the mosca server through ascoltatori, hence it will be difficult to maintain a mapping without altering MQTT.js.

**Comment by rahulbhanushali** [comment]
Found a better approach which did not involve maintaining the mapping.
Sent the messageId used for persistence in the payload and modified the this.forward inside client.js to decode and read this messaged from the payload and then call the updateOfflinePacket using this id.

The rest is taken care of automatically.

**Comment by mcollina** [comment]
@rahulbhanushali not sure it would work with other backends, but why don't you send a PR and we'll have a look?

**Comment by rahulbhanushali** [comment]
@mcollina Tested it out with mongo and redis, works fine for both. I don't think different backend will have an impact because of this change as there's not change in any of the persistence files, the only change is that the correct message id is being set by server when updateOfflinePacket is called by the client.

**Comment by rahulbhanushali** [comment]
This problem was visible in both redis and mongo. I think this problem would also be happening with other persistence factories.

**Comment by rahulbhanushali** [comment]
@mcollina Have created a pull request: https://github.com/mcollina/mosca/pull/406

**Comment by behrad** [comment]
I'm not seeing this in production on redis, and the topic is about mosquitto backend!

**Comment by rahulbhanushali** [comment]
@behrad Are you using mosquitto as the backend?
I am facing the issue with mosquitto as the backend and mongo/redis for persistence.

**Comment by behrad** [comment]
> Are you using mosquitto as the backend?

No

My reply was about your PR, everything seems to be OK with builtin mongo/redis persistence/backends, and your PR shouldn't affect that.

**Comment by rahulbhanushali** [comment]
@behrad @mcollina What other solution do we have for this solving this issue? Really need to fix this asap.

**Comment by psorowka** [comment]
@rahulbhanushali can you give some more insights on your setup? I really haven't understood how you got to that mix of mosquitto and redis. Why not using mosquitto alone?  Why do you need mosca at all?

**Comment by rahulbhanushali** [comment]
Okay, let me explain.

I am trying to build a application using Mosca as a proxy server where all of my application logic will reside. Mosca has been beautifully written and provides great abstraction and features allowing to override methods and implement the application logic on different events.

So my architecture is something as follows:
	subscriber	->	mosca	->	mosquitto

The reason for using mosquitto and not other backends is the bridge-mode capability so I can connect multiple chat brokers (with mosca tied to each one of them). 

I am using redis for persistence, to store all the offline messages for a subscriber and other application related data.

**Comment by rahulbhanushali** [comment]
@psorowka @mcollina  Anything that we can do about this?

**Comment by psorowka** [comment]
Did you think about skipping moscitto and setting up the bridge directly in your code? I mean basically it's nothing more than a mqtt subscription to a specific topic set on a remote broker and publishing every message on another one.

**Comment by rahulbhanushali** [comment]
But how will that solve the problem of messages not getting deleted?

**Comment by psorowka** [comment]
I thought you could get rid of the mosquitto dep and thus workaround this problem.

**Comment by mcollina** [comment]
This issue have been open for a long time. I don't think it's solved, but there does not seem an interest in sending a PR. Feel free to reopen or open a PR with a fix.
