### ISSUE TITLE
Packet is being stored offline after unsubscribe [redis-persistence]

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#405]
After unsubscribing a topic, subsequent messages are stored offline and will reach the client after they reconnect. However if you restart mosca after unsubscribe, that won't happen.

My previous fix of persistingClient after unsubscribe should have also contained updating internal in memory `_subMatcher` in redis persistence so that messages don't get stored as offline. [see https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L329]

I'm going to create a PR to fix this.

**Comment by mcollina** [comment]
Thanks! :+1:
