### ISSUE TITLE
optimize dependencies?

### ISSUE THREAD

**Issue by gbaumgart** [mcollina/mosca#407]
Hi,
which dependencies are really needed apart from a single storage selection (mongo in my case) ? 

the Path-Length limit of windows makes it just impossible to bundle my app folder for final shipment nor could the user freely move the app folder around.

Should I just trial and error removing folders from mosca/node_modules or does anyone knows a less bloated package.json version? Its really hard job (npm3 is not possible for me). 

Any thoughts welcome.

**Comment by mcollina** [comment]
I would not flag `package.json` as bloated. It's how node and npm works: we use a ton of dependencies as lego bricks.

Anyway, you can kill anything that is on `optionalDependencies`.

But, I would rather fix the problem for all and upgrade to npm3.

**Comment by gbaumgart** [comment]
ok, i moved to npm3 but still, what dependencies are really needed when using Mongo? There are soo many dependencies like i have hairs and I'd love to strip all what is not really needed for a pre-compiled distribution (arm7). Or do you know a more lightweight MQTT server, running with Node.js? 

Sorry for bugging on this. I could so far spot:

zmq,
level-db
hiredis
brfs
ascoltatori

but I didn't try yet without.
