### ISSUE TITLE
multiple topic authorization

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#409]
What is the best way to define multiple topics in authentication json?

```js
"user": {
    "salt": "pass",
    "hash": "hash",
    "authorizePublish": "app/id/*/*/*", 
    "authorizeSubscribe": "app/id/*/*/*" // instead of app/id/*/*/* I want to say app/id/test2/*/* && app/id/test1/*/*
  }
```

**Comment by mcollina** [comment]
I thinks this is way beyond the scope of the authentication json. For complex auth, I think you should write your own.

However, that uses https://github.com/isaacs/minimatch, so you can possibly fit in a regexp `(foo|bar)`.

**Comment by behrad** [comment]
:+1:
