### ISSUE TITLE
certificate based client authentication fails with websocket.

### ISSUE THREAD

**Issue by Ctvidyak** [mcollina/mosca#414]
I m trying to connect to mosca over websocket .With only server certificate it works as expected .But if I try to apply  client certificate  based authentication I am not able to connect to broker . However with TCP connection client certificate based authentication is  working fine.

Here is how I am passing the settings to broker .
**Server.js**

var mosca = require('mosca'),
path = require('path');

if(true){
console.log('Starting websocket server');
var settings = {
  interfaces: [{
       type: "https",
       port: 3000,
       bundle:true,
       static12:'./',
     credentials: {
        keyPath: path.join(__dirname, './certificates/key.pem'),
         certPath: path.join(__dirname,'./certificates/cert.pem' ),
      caPaths:[path.join(__dirname,'./certificates/ca.pem')],
     requestCert:true,
     rejectUnauthorized:true
     }
   }
]
}
}
else{
console.log('Startin tcp server');
var settings ={
interfaces:[
{type: "mqtts",
       port: 1884,
     credentials: {
         keyPath: path.join(__dirname, './certificates/key.pem'),
           certPath: path.join(__dirname,'./certificates/cert.pem' ),
         caPaths:[path.join(__dirname,'./certificates/ca.pem')],
     requestCert:true,
    rejectUnauthorized:true
    }
   }
]
}

}
//here we start mosca
var server = new mosca.Server(settings);

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
And client code which i  m using to connect to broker 
Client.js

var mqtt = require('mqtt'),
     fs =  require('fs');
var SECURE_CERT = './client.pfx';
var config = {};
config.mqtt = {};
config.mqtt.options = {
    username: 'admin',
    password: 'admin',
    keepalive: 20,
   clean: true,
    clientId: 'clientID',
    pfx: fs.readFileSync("client.pfx"),
    rejectUnauthorized: false,
     passphrase:'password'

};
var client;
client = mqtt.connect('wss://localhost:3000', config.mqtt.options);
// client = mqtt.connect('ssl://localhost:1884', config.mqtt.options);
client.on('connect', onConnect);
client.on('message', onMessage);
client.on('close', onClose);
client.on('disconnect', onDisconnect);
client.on('error', onError);

var counter = 0;
var max = 5;
var frequency = 10000;
var io;

function onConnect() {
    console.log('Connected');
    client.subscribe("Topic7Feb2016");
    console.log("Subscribing to the topics");
    io = setInterval(publish, frequency);
}

function onMessage(topic, message, packet) {
console.log('Message received as ' + message + ' from topic ' + topic);
}

function onClose(packet) {
    console.log('Connection closed');
}

function onDisconnect(packet) {
    console.log('Broker disconected');
}

function onError(error) {
    debugger;
    console.log('error!!');
}

function publish() {
setImmediate(function () {
  console.log("Publishing the message to the topic");
client.publish("Topic7Feb2016", "Msh");
});
if (counter >= max) {
clearInterval(io);
}
counter++;
}

**Comment by mcollina** [comment]
This might require a PR, as this was never tested before. However, using certificate devices on wss is discouraged. wss is built for being used via a browser, and because of some limitation on the websocket api, it will perform in a suboptimal way when using from devices.
