### ISSUE TITLE
mosca -v error

### ISSUE THREAD

**Issue by marvic42** [mcollina/mosca#417]
Hello,

installed mosca using "npm install mosca".
Node v0.10.24   and  npm 3.7.2
After installation, checked mosca -v, following error flashed

odroid@odroid:~$ mosca -v
+++.+++:   ,+++    +++;   '+++    +++. 
      ++.+++.++   ++.++  ++,'+  `+',++  ++,++ 
      +`  +,  +: .+  .+  +;  +; '+  '+  +`  +` 
      +`  +.  +: ,+  `+  ++  +; '+  ;+  +   +. 
      +`  +.  +: ,+  `+   +'    '+      +   +. 
      +`  +.  +: ,+  `+   :+.   '+      +++++. 
      +`  +.  +: ,+  `+    ++   '+      +++++. 
      +`  +.  +: ,+  `+     ++  '+      +   +. 
      +`  +.  +: ,+  `+  +:  +: '+  ;+  +   +. 
      +`  +.  +: .+  .+  +;  +; '+  '+  +   +. 
      +`  +.  +:  ++;++  ++'++   ++'+'  +   +. 
      +`  +.  +:   +++    +++.   ,++'   +   +. 

module.js:340
throw err;
^
Error: Cannot find module 'memdown'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/usr/local/lib/node_modules/mosca/lib/persistence/memory.js:29:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)

How to solve this.

Answers Appreciated

**Comment by mcollina** [comment]
This is an issue in the installation phase. Can you please add the npm output as a gist (it can be really long)? I would recommend using npm v2 on node v0.10, and use the latest version of node v0.10 (v0.10.42).

**Comment by johncarpenter281** [comment]
I am seeing this same issue.  I am running Ubuntu 14.04LTS, node v 5.10.1, and npm v 3.8.6. I run npm init, then npm install mosca --save . The output for this command is -
==================================
root@vps74249:/home/john/mqttApp/server# npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (server) 
version: (1.0.0) 
description: 
entry point: (server.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /home/john/mqttApp/server/package.json:

{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes) y
root@vps74249:/home/john/mqttApp/server# npm install mosca --save
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> kerberos@0.0.19 install /home/john/mqttApp/server/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/john/mqttApp/server/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/home/john/mqttApp/server/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/john/mqttApp/server/node_modules/kerberos
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

> hiredis@0.4.1 install /home/john/mqttApp/server/node_modules/hiredis
> node-gyp rebuild

make: Entering directory `/home/john/mqttApp/server/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
make: Leaving directory `/home/john/mqttApp/server/node_modules/hiredis/build'

> fs-ext@0.5.0 install /home/john/mqttApp/server/node_modules/fs-ext
> node-gyp configure build

make: Entering directory `/home/john/mqttApp/server/node_modules/fs-ext/build'
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
../fs-ext.cc: In function ‘void EIO_After(uv_work_t*)’:
../fs-ext.cc:108:20: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     argv[0] = Nan::NanErrnoException(store_data->error);
                    ^
../fs-ext.cc:108:55: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     argv[0] = Nan::NanErrnoException(store_data->error);
                                                       ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flock(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:297:45: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (i != 0) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                             ^
../fs-ext.cc:297:68: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (i != 0) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                    ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Seek(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:339:56: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (offs_result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                        ^
../fs-ext.cc:339:79: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (offs_result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                               ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Fcntl(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:375:51: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                   ^
../fs-ext.cc:375:74: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (result == -1) return Nan::ThrowError(Nan::NanErrnoException(errno));
                                                                          ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE UTime(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:433:47: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "utime", "", *path));
                                               ^
../fs-ext.cc:433:90: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "utime", "", *path));
                                                                                          ^
../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE StatVFS(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:469:47: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "statvfs", "", *path));
                                               ^
../fs-ext.cc:469:92: warning: ‘v8::Local<v8::Value> Nan::NanErrnoException(int, const char*, const char*, const char*)’ is deprecated (declared at ../../nan/nan.h:866) [-Wdeprecated-declarations]
     if (ret != 0) return Nan::ThrowError(Nan::NanErrnoException(errno, "statvfs", "", *path));
                                                                                            ^
  SOLINK_MODULE(target) Release/obj.target/fs-ext.node
  COPY Release/fs-ext.node
make: Leaving directory `/home/john/mqttApp/server/node_modules/fs-ext/build'

> dtrace-provider@0.6.0 install /home/john/mqttApp/server/node_modules/dtrace-provider
> node scripts/install.js


> leveldown@1.4.4 install /home/john/mqttApp/server/node_modules/leveldown
> prebuild --install


> zmq@2.14.0 install /home/john/mqttApp/server/node_modules/zmq
> node-gyp rebuild

make: Entering directory `/home/john/mqttApp/server/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/home/john/mqttApp/server/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/john/mqttApp/server/node_modules/zmq
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:zmq@2.14.0 zmq@2.14.0 install: `node-gyp rebuild`
npm WARN install:zmq@2.14.0 Exit status 1
server@1.0.0 /home/john/mqttApp/server
└─┬ mosca@1.2.0 
  ├─┬ amqp@0.2.4 
  │ └── lodash@1.3.1 
  ├─┬ ascoltatori@2.0.1 
  │ ├─┬ debug@2.2.0 
  │ │ └── ms@0.7.1 
  │ ├── eventemitter2@0.4.14 
  │ ├─┬ kerberos@0.0.19 
  │ │ └── nan@2.0.9 
  │ ├── node-uuid@1.4.7 
  │ ├── qlobber@0.5.3 
  │ └─┬ qlobber-fsq@0.4.1 
  │   ├── fs-ext@0.5.0 
  │   └── qlobber@0.5.3 
  ├── async@1.5.2 
  ├─┬ brfs@1.4.3 
  │ ├─┬ quote-stream@1.0.2 
  │ │ ├── buffer-equal@0.0.1 
  │ │ └─┬ through2@2.0.1 
  │ │   └─┬ readable-stream@2.0.6 
  │ │     └── isarray@1.0.0 
  │ ├── resolve@1.1.7 
  │ ├─┬ static-module@1.3.1 
  │ │ ├─┬ concat-stream@1.4.10 
  │ │ │ └── readable-stream@1.1.14 
  │ │ ├─┬ duplexer2@0.0.2 
  │ │ │ └── readable-stream@1.1.14 
  │ │ ├─┬ escodegen@1.3.3 
  │ │ │ ├── esprima@1.1.1 
  │ │ │ ├── estraverse@1.5.1 
  │ │ │ ├── esutils@1.0.0 
  │ │ │ └─┬ source-map@0.1.43 
  │ │ │   └── amdefine@1.0.0 
  │ │ ├─┬ falafel@1.2.0 
  │ │ │ ├── acorn@1.2.2 
  │ │ │ ├── foreach@2.0.5 
  │ │ │ └── object-keys@1.0.9 
  │ │ ├─┬ has@1.0.1 
  │ │ │ └── function-bind@1.1.0 
  │ │ ├── object-inspect@0.4.0 
  │ │ ├─┬ quote-stream@0.0.0 
  │ │ │ └── minimist@0.0.8 
  │ │ ├── shallow-copy@0.0.1 
  │ │ ├─┬ static-eval@0.2.4 
  │ │ │ └─┬ escodegen@0.0.28 
  │ │ │   ├── esprima@1.0.4 
  │ │ │   ├── estraverse@1.3.2 
  │ │ │   └── source-map@0.5.3 
  │ │ └─┬ through2@0.4.2 
  │ │   └─┬ xtend@2.1.2 
  │ │     └── object-keys@0.4.0 
  │ └─┬ through2@2.0.1 
  │   └─┬ readable-stream@2.0.6 
  │     └── isarray@1.0.0 
  ├─┬ bunyan@1.8.0 
  │ ├── dtrace-provider@0.6.0 
  │ ├─┬ mv@2.1.1 
  │ │ ├─┬ mkdirp@0.5.1 
  │ │ │ └── minimist@0.0.8 
  │ │ ├── ncp@2.0.0 
  │ │ └─┬ rimraf@2.4.5 
  │ │   └─┬ glob@6.0.4 
  │ │     ├── inflight@1.0.4 
  │ │     └── path-is-absolute@1.0.0 
  │ └── safe-json-stringify@1.0.3 
  ├── clone@1.0.2 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├── deepcopy@0.6.1 
  ├── extend@3.0.0 
  ├─┬ hiredis@0.4.1 
  │ ├── bindings@1.2.1 
  │ └── nan@2.2.1 
  ├── json-buffer@2.0.11 
  ├── jsonschema@1.1.0 
  ├─┬ level-sublevel@6.5.4 
  │ ├─┬ bytewise@1.1.0 
  │ │ ├─┬ bytewise-core@1.2.3 
  │ │ │ └── typewise-core@1.2.0 
  │ │ └── typewise@1.0.3 
  │ ├─┬ levelup@0.19.1 
  │ │ ├── bl@0.8.2 
  │ │ ├─┬ deferred-leveldown@0.2.0 
  │ │ │ └─┬ abstract-leveldown@0.12.4 
  │ │ │   └── xtend@3.0.0 
  │ │ ├── errno@0.1.4 
  │ │ ├── prr@0.0.0 
  │ │ └── xtend@3.0.0 
  │ ├── ltgt@2.1.2 
  │ ├─┬ pull-stream@2.21.0 
  │ │ └── pull-core@1.0.0 
  │ ├── typewiselite@1.0.0 
  │ └── xtend@4.0.1 
  ├─┬ leveldown@1.4.4 
  │ ├── abstract-leveldown@2.4.1 
  │ ├── fast-future@1.0.1 
  │ └─┬ prebuild@2.9.2 
  │   ├── expand-template@1.0.2 
  │   ├─┬ ghreleases@1.0.4 
  │   │ ├── after@0.8.1 
  │   │ ├── ghrepos@2.0.0 
  │   │ ├─┬ ghutils@3.2.0 
  │   │ │ └─┬ jsonist@1.2.0 
  │   │ │   ├─┬ bl@1.0.3 
  │   │ │   │ └─┬ readable-stream@2.0.6 
  │   │ │   │   └── isarray@1.0.0 
  │   │ │   └── hyperquest@1.2.0 
  │   │ ├── simple-mime@0.1.0 
  │   │ └── url-template@2.0.6 
  │   ├── github-from-package@0.0.0 
  │   ├─┬ node-gyp@3.3.1 
  │   │ ├── fstream@1.0.8 
  │   │ ├─┬ glob@4.5.3 
  │   │ │ └── minimatch@2.0.10 
  │   │ ├─┬ minimatch@1.0.0 
  │   │ │ ├── lru-cache@2.7.3 
  │   │ │ └── sigmund@1.0.1 
  │   │ ├─┬ nopt@3.0.6 
  │   │ │ └── abbrev@1.0.7 
  │   │ ├─┬ osenv@0.1.3 
  │   │ │ └── os-tmpdir@1.0.1 
  │   │ ├─┬ path-array@1.0.1 
  │   │ │ └─┬ array-index@1.0.0 
  │   │ │   └─┬ es6-symbol@3.0.2 
  │   │ │     ├── d@0.1.1 
  │   │ │     └─┬ es5-ext@0.10.11 
  │   │ │       └── es6-iterator@2.0.0 
  │   │ ├─┬ request@2.72.0 
  │   │ │ ├── aws-sign2@0.6.0 
  │   │ │ ├── aws4@1.3.2 
  │   │ │ ├─┬ bl@1.1.2 
  │   │ │ │ └─┬ readable-stream@2.0.6 
  │   │ │ │   └── isarray@1.0.0 
  │   │ │ ├── caseless@0.11.0 
  │   │ │ ├─┬ combined-stream@1.0.5 
  │   │ │ │ └── delayed-stream@1.0.0 
  │   │ │ ├── forever-agent@0.6.1 
  │   │ │ ├── form-data@1.0.0-rc4 
  │   │ │ ├─┬ har-validator@2.0.6 
  │   │ │ │ ├─┬ chalk@1.1.3 
  │   │ │ │ │ ├── ansi-styles@2.2.1 
  │   │ │ │ │ ├── escape-string-regexp@1.0.5 
  │   │ │ │ │ ├─┬ has-ansi@2.0.0 
  │   │ │ │ │ │ └── ansi-regex@2.0.0 
  │   │ │ │ │ ├── strip-ansi@3.0.1 
  │   │ │ │ │ └── supports-color@2.0.0 
  │   │ │ │ ├─┬ is-my-json-valid@2.13.1 
  │   │ │ │ │ ├── generate-function@2.0.0 
  │   │ │ │ │ ├─┬ generate-object-property@1.2.0 
  │   │ │ │ │ │ └── is-property@1.0.2 
  │   │ │ │ │ └── jsonpointer@2.0.0 
  │   │ │ │ └─┬ pinkie-promise@2.0.1 
  │   │ │ │   └── pinkie@2.0.4 
  │   │ │ ├─┬ hawk@3.1.3 
  │   │ │ │ ├── boom@2.10.1 
  │   │ │ │ ├── cryptiles@2.0.5 
  │   │ │ │ ├── hoek@2.16.3 
  │   │ │ │ └── sntp@1.0.9 
  │   │ │ ├─┬ http-signature@1.1.1 
  │   │ │ │ ├── assert-plus@0.2.0 
  │   │ │ │ ├─┬ jsprim@1.2.2 
  │   │ │ │ │ ├── extsprintf@1.0.2 
  │   │ │ │ │ ├── json-schema@0.2.2 
  │   │ │ │ │ └── verror@1.3.6 
  │   │ │ │ └─┬ sshpk@1.7.4 
  │   │ │ │   ├── asn1@0.2.3 
  │   │ │ │   ├─┬ dashdash@1.13.0 
  │   │ │ │   │ └── assert-plus@1.0.0 
  │   │ │ │   ├── ecc-jsbn@0.1.1 
  │   │ │ │   ├── jodid25519@1.0.2 
  │   │ │ │   ├── jsbn@0.1.0 
  │   │ │ │   └── tweetnacl@0.14.3 
  │   │ │ ├── is-typedarray@1.0.0 
  │   │ │ ├── isstream@0.1.2 
  │   │ │ ├── json-stringify-safe@5.0.1 
  │   │ │ ├─┬ mime-types@2.1.10 
  │   │ │ │ └── mime-db@1.22.0 
  │   │ │ ├── oauth-sign@0.8.1 
  │   │ │ ├── qs@6.1.0 
  │   │ │ ├── stringstream@0.0.5 
  │   │ │ ├── tough-cookie@2.2.2 
  │   │ │ └── tunnel-agent@0.4.2 
  │   │ ├─┬ tar@2.2.1 
  │   │ │ └── block-stream@0.0.8 
  │   │ └─┬ which@1.2.4 
  │   │   ├─┬ is-absolute@0.1.7 
  │   │   │ └── is-relative@0.1.3 
  │   │   └── isexe@1.1.2 
  │   ├── noop-logger@0.1.1 
  │   ├─┬ npmlog@2.0.3 
  │   │ ├── ansi@0.3.1 
  │   │ ├─┬ are-we-there-yet@1.1.2 
  │   │ │ ├── delegates@1.0.0 
  │   │ │ └─┬ readable-stream@2.1.0 
  │   │ │   └── isarray@1.0.0 
  │   │ └─┬ gauge@1.2.7 
  │   │   ├── has-unicode@2.0.0 
  │   │   ├─┬ lodash.pad@4.3.0 
  │   │   │ ├── lodash._baseslice@4.0.0 
  │   │   │ └── lodash.tostring@4.1.2 
  │   │   ├── lodash.padend@4.4.0 
  │   │   └── lodash.padstart@4.4.0 
  │   ├── os-homedir@1.0.1 
  │   ├── pump@1.0.1 
  │   ├─┬ rc@1.1.6 
  │   │ ├── deep-extend@0.4.1 
  │   │ ├── ini@1.3.4 
  │   │ └── strip-json-comments@1.0.4 
  │   ├─┬ simple-get@1.4.3 
  │   │ └── unzip-response@1.0.0 
  │   ├── tar-fs@1.12.0 
  │   └─┬ tar-stream@1.5.1 
  │     ├─┬ bl@1.1.2 
  │     │ └── readable-stream@2.0.6 
  │     └─┬ readable-stream@2.1.0 
  │       └── isarray@1.0.0 
  ├─┬ levelup@1.3.1 
  │ ├─┬ deferred-leveldown@1.2.1 
  │ │ └── abstract-leveldown@2.4.1 
  │ ├── level-codec@6.1.0 
  │ ├── level-errors@1.0.4 
  │ ├─┬ level-iterator-stream@1.3.1 
  │ │ └── readable-stream@1.1.14 
  │ ├── prr@1.0.1 
  │ └── semver@5.1.0 
  ├─┬ lru-cache@4.0.1 
  │ ├── pseudomap@1.0.2 
  │ └── yallist@2.0.0 
  ├─┬ memdown@1.1.2 
  │ ├── abstract-leveldown@2.6.0 
  │ ├── functional-red-black-tree@1.0.1 
  │ ├── inherits@2.0.1 
  │ └── ltgt@1.0.2 
  ├─┬ minimatch@3.0.0 
  │ └─┬ brace-expansion@1.1.3 
  │   ├── balanced-match@0.3.0 
  │   └── concat-map@0.0.1 
  ├── moment@2.12.0 
  ├─┬ mongodb@2.1.16 
  │ ├── es6-promise@3.0.2 
  │ ├─┬ mongodb-core@1.3.16 
  │ │ ├── bson@0.4.23 
  │ │ └─┬ require_optional@1.0.0 
  │ │   └── resolve-from@2.0.0 
  │ └─┬ readable-stream@1.0.31 
  │   ├── core-util-is@1.0.2 
  │   ├── isarray@0.0.1 
  │   └── string_decoder@0.10.31 
  ├── moving-average@0.1.1 
  ├─┬ mqtt@1.8.0 
  │ ├─┬ commist@1.0.0 
  │ │ └── leven@1.0.2 
  │ ├─┬ concat-stream@1.5.1 
  │ │ ├─┬ readable-stream@2.0.6 
  │ │ │ └── isarray@1.0.0 
  │ │ └── typedarray@0.0.6 
  │ ├─┬ end-of-stream@1.1.0 
  │ │ └─┬ once@1.3.3 
  │ │   └── wrappy@1.0.1 
  │ ├─┬ help-me@0.1.0 
  │ │ └── readable-stream@1.1.14 
  │ ├── minimist@1.2.0 
  │ ├─┬ mqtt-packet@3.4.6 
  │ │ └── bl@0.9.5 
  │ └── reinterval@1.0.2 
  ├─┬ mqtt-connection@2.1.1 
  │ ├── reduplexer@1.1.0 
  │ └─┬ through2@0.6.5 
  │   └── readable-stream@1.0.34 
  ├─┬ msgpack5@3.3.0 
  │ ├─┬ bl@1.1.2 
  │ │ └── readable-stream@2.0.6 
  │ └─┬ readable-stream@2.1.0 
  │   ├── inline-process-browser@2.0.1 
  │   ├── isarray@1.0.0 
  │   ├── process-nextick-args@1.0.6 
  │   ├─┬ unreachable-branch-transform@0.5.1 
  │   │ ├── esmangle-evaluator@1.0.0 
  │   │ └─┬ recast@0.11.5 
  │   │   ├── ast-types@0.8.16 
  │   │   ├── esprima@2.7.2 
  │   │   └── private@0.1.6 
  │   └── util-deprecate@1.0.2 
  ├─┬ pbkdf2-password@1.1.0 
  │ └─┬ fastfall@1.5.1 
  │   └── reusify@1.0.1 
  ├── qlobber@0.6.0 
  ├─┬ redis@2.5.3 
  │ ├── double-ended-queue@2.1.0-0 
  │ ├── redis-commands@1.1.0 
  │ └── redis-parser@1.3.0 
  ├── retimer@1.0.1 
  ├── shortid@2.2.6 
  ├─┬ st@1.1.0 
  │ ├─┬ async-cache@1.0.0 
  │ │ └── lru-cache@2.3.1 
  │ ├─┬ bl@1.0.3 
  │ │ └─┬ readable-stream@2.0.6 
  │ │   └── isarray@1.0.0 
  │ ├── fd@0.0.2 
  │ ├── graceful-fs@4.1.3 
  │ ├── mime@1.3.4 
  │ └── negotiator@0.6.0 
  ├── uuid@2.0.2 
  └─┬ websocket-stream@3.1.0 
    ├─┬ duplexify@3.4.3 
    │ ├── end-of-stream@1.0.0 
    │ └─┬ readable-stream@2.1.0 
    │   └── isarray@1.0.0 
    ├─┬ through2@2.0.1 
    │ └─┬ readable-stream@2.0.6 
    │   └── isarray@1.0.0 
    └─┬ ws@1.1.0 
      ├── options@0.0.6 
      └── ultron@1.0.2 

npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.
=================
This results in the node_modules folder being created and populated like so -
root@vps74249:/home/john/mqttApp/server# ls
node_modules  package.json  server.js
root@vps74249:/home/john/mqttApp/server# ls no*
abbrev                     level-codec
abstract-leveldown         leveldown
acorn                      level-errors
after                      level-iterator-stream
amdefine                   level-sublevel
amqp                       levelup
ansi                       leven
ansi-regex                 lodash
ansi-styles                lodash._baseslice
are-we-there-yet           lodash.pad
array-index                lodash.padend
ascoltatori                lodash.padstart
asn1                       lodash.tostring
assert-plus                lru-cache
ast-types                  ltgt
async                      memdown
async-cache                mime
aws4                       mime-db
aws-sign2                  mime-types
balanced-match             minimatch
bindings                   minimist
bl                         mkdirp
block-stream               moment
boom                       mongodb
brace-expansion            mongodb-core
brfs                       mosca
bson                       moving-average
buffer-equal               mqtt
bunyan                     mqtt-connection
bytewise                   mqtt-packet
bytewise-core              ms
caseless                   msgpack5
chalk                      mv
clone                      nan
combined-stream            ncp
commander                  negotiator
commist                    node-gyp
concat-map                 node-uuid
concat-stream              noop-logger
core-util-is               nopt
cryptiles                  npmlog
d                          oauth-sign
dashdash                   object-inspect
debug                      object-keys
deepcopy                   once
deep-extend                options
deferred-leveldown         osenv
delayed-stream             os-homedir
delegates                  os-tmpdir
double-ended-queue         path-array
dtrace-provider            path-is-absolute
duplexer2                  pbkdf2-password
duplexify                  pinkie
ecc-jsbn                   pinkie-promise
end-of-stream              prebuild
errno                      private
es5-ext                    process-nextick-args
es6-iterator               prr
es6-promise                pseudomap
es6-symbol                 pull-core
escape-string-regexp       pull-stream
escodegen                  pump
esmangle-evaluator         qlobber
esprima                    qlobber-fsq
estraverse                 qs
esutils                    quote-stream
eventemitter2              rc
expand-template            readable-stream
extend                     recast
extsprintf                 redis
falafel                    redis-commands
fastfall                   redis-parser
fast-future                reduplexer
fd                         reinterval
foreach                    request
forever-agent              require_optional
form-data                  resolve
fs-ext                     resolve-from
fstream                    retimer
functional-red-black-tree  reusify
function-bind              rimraf
gauge                      safe-json-stringify
generate-function          semver
generate-object-property   shallow-copy
ghreleases                 shortid
ghrepos                    sigmund
ghutils                    simple-get
github-from-package        simple-mime
glob                       sntp
graceful-fs                source-map
graceful-readlink          sshpk
har-validator              st
has                        static-eval
has-ansi                   static-module
has-unicode                string_decoder
hawk                       stringstream
help-me                    strip-ansi
hiredis                    strip-json-comments
hoek                       supports-color
http-signature             tar
hyperquest                 tar-fs
inflight                   tar-stream
inherits                   through2
ini                        tough-cookie
inline-process-browser     tunnel-agent
is-absolute                tweetnacl
isarray                    typedarray
isexe                      typewise
is-my-json-valid           typewise-core
is-property                typewiselite
is-relative                ultron
isstream                   unreachable-branch-transform
is-typedarray              unzip-response
jodid25519                 url-template
jsbn                       util-deprecate
json-buffer                uuid
jsonist                    verror
jsonpointer                websocket-stream
jsonschema                 which
json-schema                wrappy
json-stringify-safe        ws
jsprim                     xtend
kerberos                   yallist
===================================
Then I try running the file and get this error -

root@vps74249:/home/john/mqttApp/server# node server.js
module.js:341
    throw err;
    ^

Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/john/mqttApp/server/node_modules/mosca/lib/persistence/memory.js:29:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
root@vps74249:/home/john/mqttApp/server# 
==================
The file looks like this -

var mosca = require('mosca')
 
var pubsubsettings = {
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'myCollections',
  mongo: {}
};
 
var settings = {
  port: 1883,
  backend: pubsubsettings
};
 
//here we start mosca
var server = new mosca.Server(settings);
...
===========
This works fine on another machine with a different configuration (Ubuntu 15.10, node 5.6.0, npm 3.7.5

Any help would be appreciated!

**Comment by rgstephens** [comment]
Pulling my hair out on this one. I've tried the latest 0.12 release and had this error, saw that @mcollina recommended v4 in Issue https://github.com/mcollina/mosca/issues/413, so I'm now on v4.4.3 and still have this error. I've avoided installing the standard Ubuntu package as recommended. Not sure where to go next.

**Comment by mcollina** [comment]
I can't reproduce, mosca installs fine here. This seems rather a problem on your box or npm itself.
I'm not sure how I can help.

**Comment by dlykissas** [comment]
I too have this issue. My box is a Fedora 23 server (no Desktop, only text), and I'm running node 0.10.42 installed with dnf (not compiled from source). Unfortunately there is no 4.4.5 (or any 4... for that matter) in the official repos, and I don't feel comfortable compiling. Anybody found a workaround?

**Comment by mcollina** [comment]
No, not really. It's a problem on your server.
