### ISSUE TITLE
Docker container size reduction

### ISSUE THREAD

**Issue by seriousme** [mcollina/mosca#418]
Hi,

I noticed it is now also available as a docker container. However its rather heavy at 710 MB. 
Switching to [mhart/alpine-node](https://hub.docker.com/r/mhart/alpine-node/) reduced the footprint of my docker container running Mosca to 49 Mb.

If you'd rather go with a "known brand" there is [risingstack/alpine](https://hub.docker.com/r/risingstack/alpine/) which starts at 80Mb (excluding Mosca)

Kind regards,
Hans

**Comment by mcollina** [comment]
Would you mind sending a PR? I'll review and merge! I'm all in for alpine-node.

**Comment by seriousme** [comment]
Ok, will do. 
Dockerhub is building as we speak ;-)

**Comment by seriousme** [comment]
Thx
