### ISSUE TITLE
Mosca authentication and PubSubClient

### ISSUE THREAD

**Issue by roccomuso** [mcollina/mosca#420]
I'm trying to figure out why the PubSubClient (https://github.com/knolleary/pubsubclient) doesn't work with Mosca Authentication.

Not sure if the issue is related to the client or the broker: https://github.com/knolleary/pubsubclient/issues/130

**Comment by mcollina** [comment]
Can you please publish a snippet of infringing code?

Also, does authentication works with MQTT.js or mosquitto_pub?

**Comment by roccomuso** [comment]
I've found the issue. Seems to be related to the publish authorization.
If I try to publish in a topic I'm not authorized to publish, the client gets disconnected, the broker doesn't return the code <code>5 - "Connection Refused, not authorized"</code> expected and the connection is lost.

Have you ever tried to publish in a topic with no authorization? Is it normal that the connection gets closed and no "5- connection refused" error pops out?

The HiveMQ web client gets disconnected, and the PubSubClient for embedded device too. Could be a Mosca issue.

**Comment by knolleary** [comment]
That return code is only used in the CONNACK packet.

There is no mechanism in MQTT for the broker to reject a publish other than to close the connection. This is something we're looking at for future versions of the protocol, but today, closing the connection is the only option available.

**Comment by roccomuso** [comment]
@knolleary glad we came to the solution. Thanks guys.

**Comment by mcollina** [comment]
Awesome! :)
