### ISSUE TITLE
Getting a server working with TLS throws bad password error

### ISSUE THREAD

**Issue by AcuarioCat** [mcollina/mosca#421]
Hi,
I've followed the instructions for setting up Mosca with TLS but on startup I'm getting an error.
From a clean Debian Jessie build I've:
1. Installed node v5.7.0 (apt-get install --yes nodejs)
2. Installed mosca (npm install mosca --save)
3. Installed mongodb (sudo apt-get install mongodb)
 I then created the keys (openssl req -x509 -newkey rsa:1024 -keyout key.pem -out cert.pem -days XXX)
It asked for a PEM pass phrase which I set as 12345
4. I copied the sample TLS SSL code from the wiki into a file and changed the paths and names to the certificates:
var SECURE_KEY = __dirname + '/key.pem';
var SECURE_CERT = __dirname + '/cert.pem';
5. I saved the file as moscas.js
6. I attempted to start mosca with the command node moscas.js
I get an error:-(
_tls_common.js:87
 c.context.setKey(options.key);

Error: error: 0907B068:PEM routines:PEM_READ_BIO_PRIVATEKEY:bad password read

What is wrong? What do I need to do to fix this? I'm not a Linux person so simple steps please!

Commenting out the secure:{...} section and the server starts ok.

**Comment by mcollina** [comment]
It seems a node issue. Have your key a password?

Also, try it with just plain node: https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

**Comment by AcuarioCat** [comment]
I did exactly what is above, if this implicates that the key has a password, then yes - if not then no. The only thing I entered was 12345 when prompted for a pass phrase.

Like I said, I'm not a Linux expert or anything close. To use just plain node what do I need to do? 
Please be patient with me! 
Thanks for your help.

**Comment by mcollina** [comment]
> I did exactly what is above, if this implicates that the key has a password, then yes - if not then no.

You probably know better than me what you have done.

>  The only thing I entered was 12345 when prompted for a pass phrase.

So, you entered a pass phrase (or password), so you know what you have done :).

Easy step: regenerate your key without a pass phrase.

**Comment by AcuarioCat** [comment]
When I run 'openssl req -x509 -newkey rsa:1024 -keyout key.pem -out cert.pem -days XXX' as instructed it says:
Enter PEM pass phrase:
 If I don't enter one it gives an error saying I have to provide one between 4 and 1024 characters. How can I not enter a pass phrase/password?

**Comment by mcollina** [comment]
Follows the instructions here: https://nodejs.org/api/tls.html

**Comment by AcuarioCat** [comment]
Ok, looks like I found a solution - the key is generated with pass phrase - this seems impossible to avoid. But then it can be removed...
..Keep a copy of the key just in case
cp key.pem key.old.pem
openssl rsa -in key.pem -out newkey.pem
..You need to enter the pass phrase
..then you have a key that will work. 
Replace the key.pem with newkey.pem and success. The server starts.

**Comment by freesoft** [comment]
@AcuarioCat I know it's more than a year old, but can you explain why this work? ( I solved my problem with your workaround though.. I want to know why)

**Comment by vsveyko** [comment]
for key generation without passphrase see https://gist.github.com/ArnaudValensi/6e23027bd361c58a68040f80e9d6f5ab
