### ISSUE TITLE
Subscribe "\" 

### ISSUE THREAD

**Issue by sachinra** [mcollina/mosca#422]
When a client tries to subscribe to "\" mosca server crashes.

`D:\Enide\ws\MQTT\node_modules\mosca\lib\persistence\mongo.js:269
  var regexp = new RegExp(pattern.replace(/(#|\+)/, ".+"));
               ^
SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (native)
    at MongoPersistence.lookupRetained (D:\Enide\ws\MQTT\node_modules\mosca\lib\persistence\mongo.js:269:16)
    at EventEmitter.server.forwardRetained (D:\Enide\ws\MQTT\node_modules\mosca\lib\persistence\abstract.js:87:10)
    at D:\Enide\ws\MQTT\node_modules\mosca\lib\client.js:484:21
    at Array.forEach (native)
    at D:\Enide\ws\MQTT\node_modules\mosca\lib\client.js:482:26
    at D:\Enide\ws\MQTT\node_modules\mosca\node_modules\async\lib\async.js:52:16
    at D:\Enide\ws\MQTT\node_modules\mosca\node_modules\async\lib\async.js:361:13
    at D:\Enide\ws\MQTT\node_modules\mosca\node_modules\async\lib\async.js:52:16
    at done (D:\Enide\ws\MQTT\node_modules\mosca\node_modules\async\lib\async.js:246:17)`

**Comment by sachinra** [comment]
This has temporarily solved the issue.
 
MongoPersistence.prototype.lookupRetained = function(pattern, cb) {
	if (pattern == '\\')
		pattern = pattern+'#';
  var regexp = new RegExp(pattern.replace(/(#|\+)/, ".+"));

**Comment by psorowka** [comment]
wow :) @mcollina seems like we need a random topic brute force test for mosca, just as we did it for the messages in the mqtt packet parser :)

two solutions come to my mind:

- either try/catch around the regex builder
- build a regex that checks if the regex string is valid :)

**Comment by mcollina** [comment]
Yes a try-catch is the way to go Peter, would you mind sending in a PR?

Il giorno ven 26 feb 2016 alle ore 13:10 Peter Sorowka <
notifications@github.com> ha scritto:

**Comment by psorowka** [comment]
I can give it a try on the weekend, today no spare time
