### ISSUE TITLE
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

### ISSUE THREAD

**Issue by mmick66** [mcollina/mosca#427]
I get the message above every time I start Mosca. I am running a minimal example as copied from this repository's Wiki. 

From my little research it might have something to do with the **bunyan** module that is included in the dependencies.

I am running:

**Mac OS X El Capitan (Version 10.11.3)
Node v4.2.6**
(and the latest checkout from Mosca)

**Comment by behrad** [comment]
same for me :) I don't think dtrace is Mac OSX compatible, and since it is not installed on your system, you are getting the error. You can ignore this, a PR for a more user friendly log entry is welcome :+1:

**Comment by mmick66** [comment]
I do not think it is a general Mac OS problem, since I did not have it before. It could be more relating to the specific version of the OS. In any case I am ignoring it but it is annoying. How can we find a solution?

**Comment by mcollina** [comment]
if you run npm rebuild, does it complete correctly?
Il giorno gio 3 mar 2016 alle 15:50 Michael Michailidis <
notifications@github.com> ha scritto:

**Comment by mcollina** [comment]
Have you changed your node.js version recently? This is what happens when
you forget to run an npm build or whiping out node_modules.
Il giorno gio 3 mar 2016 alle 16:42 Michael Michailidis <
notifications@github.com> ha scritto:

**Comment by mmick66** [comment]
I get:

`Building dtrace-provider failed with exit code 1 and signal 0`

and the error persists.

**Comment by mcollina** [comment]
I do not think you have your OS set up to compile native modules: follow https://github.com/nodejs/node-gyp#installation.

**Comment by mmick66** [comment]
I am trying to run 

`node-gyp rebuild`

inside of the mosca module but I get an error

`gyp: binding.gyp not found (cwd: /Users/mmichailidis/Programs/enview/enview-mqtt-broker/node_modules/mosca) while trying to load binding.gyp`

**Comment by mcollina** [comment]
Once you have configured your machine correctly, just remove the node_modules folder and reinstall everything.

**Comment by gochinj** [comment]
The solution is actually simple on OSx. You need to install Xcode. After installing it make sure you open Xcode once so it completes its installation.  Then delete your node_modules folder, and do an `npm install`.
