### ISSUE TITLE
Performance Issue in loading subscriptions [in qlobber.js via redis persistence]

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#428]
I have 67K subscribers with 5 topics subscribed each (around 335K subscriptions), when starting Mosca it takes minutes for it to start persistence on redis (to load subscriptions) and CPU is 100%

I traced the code and found this line https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L108 is producing all the trouble. commenting it lets mosca to start in few seconds iterating all the keys via `keys ...*` command.
So it seems qlobber trie implementation is not scalable to many hundred thousands of additions.

Asking @davedoesdev to think about performance improvements?

Change qlobber with may be another trie/qlobber impl? I found some but not dig into them yet:
https://github.com/isaacs/node-glob
https://github.com/jeresig/trie-js
https://github.com/rbranson/glob-trie.js?utm_source=javascriptweekly&utm_medium=email
http://ejohn.org/blog/javascript-trie-performance-analysis/

Writing a custom one?

What do you suggest @mcollina ?

**Comment by davedoesdev** [comment]
@behrad  qlobber has focused on matching performance - once the subscriptions are added, are you getting a problem?
That said, it seems we need to optimise adding patterns, I'll have a think. Any suggestions welcome.
I wonder what happens if you rate limit the subscriptions? Is there a dogpiling effect here?

**Comment by davedoesdev** [comment]
@behrad you could profile/trace qlobber to see where it's spending it's time (start from https://github.com/davedoesdev/qlobber/blob/master/lib/qlobber.js#L300). It could be the string split or some place in `_add`. If I get time I'll write a test to add that number of subscriptions (btw, how long are the topics?) but it may not be for a few days. If you've got the profiling set up already, it should be easy.

**Comment by davedoesdev** [comment]
Might be interesting to write a quick test to compare string split performance against just iterating through the string with indexOf and substr.
Also, there may be something which is preventing _add being compiled.

**Comment by behrad** [comment]
> qlobber has focused on matching performance - once the subscriptions are added, are you getting a problem?

Matching is great on my data (300K subs from 67K clients), I haven't read your trie code however I see there may be a tradeoff between insertion and super fast matching.

However in a real world case, there will be even more clients (millions) and multiple millions of subscriptions. Not tested matching in that scale yet... Currently high ratio insertion is bottleneck.

This problem shows up in two cases:
1) when broker needs to be restarted in production environment. and it takes minutes for the broker to start up.

2) when system grows to multi million clients, you will get a high rate of connect requests on the broker (may be around multi hundreds/sec for a million clients) and mobile clients (sleeps, mobile data lags,...) make it worst.

and client connects are online type of requests. Rate limiting seems not rational to me.

**Comment by behrad** [comment]
> you could profile/trace qlobber to see where it's spending it's time (start from https://github.com/davedoesdev/qlobber/blob/master/lib/qlobber.js#L300). It could be the string split or some place in _add. If I get time I'll write a test to add that number of subscriptions (btw, how long are the topics?) but it may not be for a few days. If you've got the profiling set up already, it should be easy

will let you know. Is there any profiling module on npm you prefer that I use on qlobber?

**Comment by mcollina** [comment]
0x, a new thing we are building at nearForm.
BTW, last year I fixed a deopt in the match method.
Il giorno gio 3 mar 2016 alle 20:57 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
@mcollina How dya think about this problem? May it be an architecture flaw?
What if every instance didn't need all subs in memory? and it could be done in a clustered, sharded fashion, in between broker instances in the cluster?

It doesn't feel scalable this way around.

**Comment by behrad** [comment]
https://github.com/emqtt/emqttd/issues/461#issuecomment-191950489

**Comment by behrad** [comment]
> how long are the topics?

They are in 5 levels: `app/appName/user/userId/alert`

**Comment by davedoesdev** [comment]
0x looks cool - care to give it a try?

**Comment by davedoesdev** [comment]
Yes, sharded/clustered may help but I think it's worth doing some profiling and checking for deopt.

**Comment by mcollina** [comment]
I'm actually fine in using a patrica trie vs a normal trie. It does not
change much, and it can improve Qlobber perf :).

Regarding the approach, it is scalable within a limit: without the
in-memory cache it would be massively slower.
Il giorno gio 3 mar 2016 alle 21:46 David Halls <notifications@github.com>
ha scritto:

**Comment by behrad** [comment]
I changed `async.each` in https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L156 to `async.eachSeries` and traced the code, it is all about https://github.com/davedoesdev/qlobber/blob/master/lib/qlobber.js#L123-L152 @davedoesdev 
and it takes 12 minutes for my data 335K * 5(levels of topics) on a Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz server!

I'm not a V8 expert and don't know about tail-recursion optimizations in node.js, but when I commented all assignments in https://github.com/davedoesdev/qlobber/blob/master/lib/qlobber.js#L123-L152 to let the code only recurse, it only took 30 Seconds!

**Comment by davedoesdev** [comment]
@behrad thanks for doing that. I'm keen to profile this myself (0x will be useful). I'm going to do this here: https://github.com/davedoesdev/qlobber/issues/8
However, I have a couple of other things to finish up first so it may be a few days.

**Comment by behrad** [comment]
Found effective line:
https://github.com/davedoesdev/qlobber/blob/master/lib/qlobber.js#L144

only commenting `st = sub_trie[word];` reduces 12 minutes to 30 seconds!!!
Can it be related to memory copy or argument passing to the later recursive all at the end the function? @davedoesdev

**Comment by behrad** [comment]
:+1: @davedoesdev eager to this :)
Didn't heart about Ox, looks promising, thank you

**Comment by davedoesdev** [comment]
That should just be a hash table lookup, weird.

**Comment by davedoesdev** [comment]
Btw which version of Node are you using?

**Comment by davedoesdev** [comment]
Also, what if you change https://github.com/davedoesdev/qlobber/blob/master/lib/qlobber.js#L151 to

```javascript
return this._add(val, i + 1, words, st);
```

?

**Comment by davedoesdev** [comment]
I think TCO is coming in ES6. Not read the spec fully myself - may have to do something to support it? Also not sure that is the problem, just a guess.

**Comment by davedoesdev** [comment]
According to this, TCO not yet in Node: https://kangax.github.io/compat-table/es6/

Am thinking if it will be difficult to write this iteratively.

**Comment by behrad** [comment]
On Node 4.3.1, will test with `return` added and let you know.



> Am thinking if it will be difficult to write this iteratively.

That'd be great, I was thinking about asking you for an iterative version so that I can test against recursive one :+1:

**Comment by behrad** [comment]
> Also, what if you change https://github.com/davedoesdev/qlobber/blob/master/lib/qlobber.js#L151 to
> 
> return this._add(val, i + 1, words, st);
> ?

No, it took 14 minutes, but I think I got it.

Changing the line to  `return this._add(val, i + 1, words, {});` reduced it to 30seconds again, So as I guessed it is the argument passing to recursive calls while forth argument i.e. `subtree` is growing and getting a bigger object. 
However since I don't know details about V8's argument passing, I can't explain why? 
Is node passing parameters by value? :)

I believe an iterative version with an internal global object for the trie state, inside qlobber object, should enhance this much.

**Comment by davedoesdev** [comment]
@behrad how strange! I'd assumed V8 would just pass a pointer to the object!
I'll have a think.

**Comment by davedoesdev** [comment]
Btw- could you let me have your test script please?

**Comment by davedoesdev** [comment]
(or maybe it's lazy and it doesn't do the hash table lookup if it thinks it isn't needed - could try just accessing `st` to see if that makes a difference).
Also, I think there's some way of getting logging as to what optimisations V8 is doing. @mcollina might know.

**Comment by psorowka** [comment]
wouldn't it be feasible to wrap the recursion in an outer function and
accessing `st` via closure? The whole algorithm isn't async anyway, is it?

2016-03-05 13:29 GMT+01:00 David Halls <notifications@github.com>:

**Comment by behrad** [comment]
> Btw- could you let me have your test script please?

I have none, it is my application code in my stress testing environment.

You can easily reproduce this by subscribing 60K clientIds each subscribing to 5 topics with 5levels (`app/test/user/behrad/testTopic`) and `qos=1` via mqttjs :) and then restarting mosca

**Comment by behrad** [comment]
And how much dya think reducing topic levels will help? I haven't tested with 3levels topic names, since my app is designed to work on a 5 level convention in production, can't change this that simple

**Comment by davedoesdev** [comment]
Don't think we should reduce topic levels yet - there's obviously something going on.

I was going to write a test for qlobber outside mosca. I'll try 60k subscriptions each to the same 5 topics first.

**Comment by davedoesdev** [comment]
@psorowka yes something like that could work. I'm rather curious as to why passing it down is making such a difference.
Hopefully I can grab an hour or two to write the test and play around.
match and remove are recursive too, perhaps they're suffering too. Interesting investigation - @behrad thanks for the heads up.

**Comment by davedoesdev** [comment]
I can't get round to this until later.
I do have another question: how does it perform under Node 0.12 - the same?

**Comment by behrad** [comment]
> how does it perform under Node 0.12 - the same?

not tested 

> I was going to write a test for qlobber outside mosca. I'll try 60k subscriptions each to the same 5 topics first.

waiting for this

**Comment by davedoesdev** [comment]
@behrad  do you mean something like this?

```javascript
    var matcher = new Qlobber(), i, j;

    for (i = 0; i < 60000; i += 1)
    {
        for (j = 0; j < 5; j += 1)
        {
            matcher.add('app/test/user/behrad/testTopic' + i, i);
        }
    }
```

**Comment by davedoesdev** [comment]
For that it's super quick:

```
add_many.js x1
  ┌──────────┬────────────┬──────────────┬──────────┐
  │          │ total (ms) │ average (ns) │ diff (%) │
  ├──────────┼────────────┼──────────────┼──────────┤
  │ add_many │        162 │  162,219,215 │        - │
  └──────────┴────────────┴──────────────┴──────────┘
```

**Comment by davedoesdev** [comment]
Ah wrong separator!

**Comment by davedoesdev** [comment]
So this:

```javascript
    var matcher = new Qlobber(
    {
        separator: '/',
        wildcard_one: '+',
        wildcard_some: '#'
    }), i, j;

    for (i = 0; i < 60000; i += 1)
    {
        for (j = 0; j < 5; j += 1)
        {
            matcher.add('app/test/user/behrad/testTopic-' + j, i);
        }
    }
```

is still super quick:

```
  add_many.js x1
  ┌──────────┬────────────┬──────────────┬──────────┐
  │          │ total (ms) │ average (ns) │ diff (%) │
  ├──────────┼────────────┼──────────────┼──────────┤
  │ add_many │        330 │  329,752,543 │        - │
  └──────────┴────────────┴──────────────┴──────────┘
```

**Comment by davedoesdev** [comment]
I stringified out the matcher object and the structure is built as expected so it's a correct test.
@behrad what timings are you getting from the above standalone test?
It would help to get these in order to determine whether the problem lies with qlobber or in the way mosca is using it.

**Comment by behrad** [comment]
> what timings are you getting from the above standalone test?

I ran the above snippet both standalone (in 1689ms, without console.log), and inside mosca (took 16seconds) with console.log




> in the way mosca is using it

Results now show that this has more possibility, since a qlobber object of the same size is constructed inside broker easily

**Comment by davedoesdev** [comment]
How did you run it inside mosca?

**Comment by davedoesdev** [comment]
Probably we need a test which models what the mosca redis driver is doing. I'll see if I can figure it out.

**Comment by davedoesdev** [comment]
Looks like the redis driver just has a single `Matcher` and `add`s to that.
I tried changing my test to define and use `Matcher` (as in `matcher.js`) but that made no difference.

**Comment by davedoesdev** [comment]
@behrad if you mean inside mosca by making network requests for each client then I guess that would take 16s for 60k of them.

**Comment by behrad** [comment]
Finally found it! 

if you use a combination of `.match` and `.add` this will happen.

You can easily reproduce this by changing your example to

```js
for (i = 0; i < 60000; i += 1)
    {
        for (j = 0; j < 5; j += 1)
        {
            if( matcher.match('app/test/user/behrad/testTopic-' + j).indexOf(i) < 0 ) 
            {
                matcher.add('app/test/user/behrad/testTopic-' + j, i);
            }
        }
    }
```

Can you explain this @davedoesdev ?

**Comment by behrad** [comment]
Mosca needs that `if` so it don't add duplicate entries in subscriptions list here https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L107

**Comment by behrad** [comment]
since topics are not the same, we can't say return object of `matcher.match('app/test/user/behrad/testTopic-' + j)` is growing... so it should not be the `indexOf` at all.

above code takes long on my server and reproducing the issue, however if we want to go further we can also add a unique topic name for each client, I mean

```js
for (i = 0; i < 60000; i += 1)
    {
        for (j = 0; j < 3; j += 1)
        {
            if( matcher.match('app/test/user/behrad/testTopic-' + j).indexOf(i) < 0 ) 
            {
                matcher.add('app/test/user/behrad/testTopic-' + j, i);
            }
        }
        if( matcher.match('app/test/user/behrad/allTopic').indexOf(i) < 0 ) 
            {
                matcher.add('app/test/user/behrad/allTopic', i);
            }
        if( matcher.match('app/test/user/behrad/allTopic2' ).indexOf(i) < 0 ) 
            {
                matcher.add('app/test/user/behrad/allTopic2', i);
            }
    }
```

this will also make growing object to be returned from `.match`

**Comment by behrad** [comment]
An Idea: it was nice Qlobber's trie could natively also support unique insertions of values

**Comment by davedoesdev** [comment]
Indeed- just thinking that way. Won't get round to that until later but can think of best way in the meantime.

**Comment by behrad** [comment]
I tested combination of `.remove + .add` and it takes 7seconds (.match+.add takes 78seconds) What about changing https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L107-L109 to
```js
that._subMatcher.remove(sub, id);
that._subMatcher.add(sub, id);
```

This will also ensure uniqueness and takes 10 times less time, Are you ok if I create a PR @mcollina ?

**Comment by behrad** [comment]
> This will also ensure uniqueness and takes 10 times less time, Are you ok if I create a PR @mcollina ?

No, it seems sequentially calling two `qlobber` methods in a large iteration is producing this anyway.
1) When loading mosca to restore subscriptions in memory
2) When rushing clients to connect to mosca on >100 client/sec connection rates

We can solve first case by recognizing newSub is called on startup and don't call `if .match`, Don't think we need that check when starting up and memory is clean.

Second case still exists.

**Comment by davedoesdev** [comment]
Calling `remove` then `add` is a lot quicker (avoid matching). Would you still like me to add an option to add unique insertion?

**Comment by mcollina** [comment]
I've not followed this much, I will catch up in the next few days.

Unique insertion will be great. However allow to pass a function to test
for uniqueness.
Il giorno dom 6 mar 2016 alle 09:46 David Halls <notifications@github.com>
ha scritto:

**Comment by davedoesdev** [comment]
@mcollina agreed

**Comment by davedoesdev** [comment]
I've found an optimisation for `match`!
If you add these lines to the start of `addAll` then matching is greatly quicker if you've not got multiple matches to append:

```javascript
  if (dest.length === 0) {
    return origin.slice(0);
  }
```

**Comment by behrad** [comment]
> Unique insertion will be great. However allow to pass a function to test
> for uniqueness.

:+1: 




> If you add these lines to the start of addAll then matching is greatly quicker if you've not got multiple matches to append:

Will test if it works...

**Comment by davedoesdev** [comment]
The problem with unique insertion is how to do it without slowing down non-unique insertion.
Note also that duplicate results will still be possible from `match` even if non-unique insertion is implemented.

**Comment by davedoesdev** [comment]
Regarding https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L107

Is this actually correct? What if there is a wildcard rule in `that._subMatcher` which matches? Then the rule won't be added.

**Comment by psorowka** [comment]
wow i am getting curious whether all of this is related to #426 ..

2016-03-06 14:36 GMT+01:00 David Halls <notifications@github.com>:

**Comment by behrad** [comment]
> Is this actually correct? What if there is a wildcard rule in that._subMatcher which matches? Then the rule won't be added.

This is Ok, since if multiple subscriptions of a clientId match, only a single message should be delivered I think :) @mcollina can approve this.



> The problem with unique insertion is how to do it without slowing down non-unique insertion

Mosca's all usage is unique insertion I believe, However this can be configured as a qlobber constructor option.

**Comment by psorowka** [comment]
>> Is this actually correct? What if there is a wildcard rule in that._subMatcher which matches? Then the rule won't be added.
> This is Ok, since if multiple subscriptions of a clientId match, only a single message should be delivered I think :) @mcollina can approve this.

Agreed, this is *expected* behavior, but have a look at #426 this does not currently work with redis

**Comment by davedoesdev** [comment]
@behrad but what if the wildcard subscription is removed? Remove and add won't be balanced.

Anyway, best way is to add uniqueness into qlobber. Ideally it would be able to use a list (as now) or a set on each leaf. ES6 has sets.

**Comment by behrad** [comment]
> @behrad but what if the wildcard subscription is removed? Remove and add won't be balanced

yes, and remove/add won't work yes!



> Anyway, best way is to add uniqueness into qlobber. Ideally it would be able to use a list (as now) or a set on each leaf. ES6 has sets.

Is it going to happen any soon? so that I can test against my current setup?

**Comment by behrad** [comment]
> if (dest.length === 0) {
>     return origin.slice(0);
>   }

this reduce 78seconds to 17seconds for the above sample code

**Comment by davedoesdev** [comment]
@behrad is that good enough?
The sets stuff is going to need some thinking/learning.

**Comment by davedoesdev** [comment]
Have done some prep work on qlobber's master branch (not on npm). I've pulled out the list-specific handling into separate methods.
Hopefully soonish I'll be able to have a derived class from `Qlobber` which overrides these methods to use `Set`.

**Comment by davedoesdev** [comment]
@behrad qlobber 0.6.0 is now published, which includes QlobberDedup: https://github.com/davedoesdev/qlobber#qlobberdedupoptions

API is the same except for `match`, which now returns an ES6 `Set`. Internally it uses `Set`s to dedup values too.

It'd be good to know if it helps your use case any. You'll have to modify mosca to use it.

**Comment by behrad** [comment]
I found currently Mosca is forwarding duplicate messages to client if overlapping topics are subscribed even now! It may be related to https://github.com/mcollina/mosca/issues/428#issuecomment-192926999

I think this may be a better Idea not to handle duplication on `add`ing side, but at `forwardPacket` time. Eager to here @mcollina view on this, both semantic & performance wise :)

**Comment by behrad** [comment]
> @behrad is that good enough?

Was not good enough in mosca's case in my tests



> It'd be good to know if it helps your use case any. You'll have to modify mosca to use it.

I'll give it a try :+1:

**Comment by psorowka** [comment]
@behrad Let's sort this:

- *exact* duplicates of subscriptions must be checked when subscribing. Otherwise Mosca we'll have a lot of garbage when clients don't handle their clean session well
- *matching* duplicates may occur in practice and should be deduped at forwarding. As far as I understood, mosca does this correctly in all other backends, but their seems to be a dedup bug with redis. 

The latter is what #426 is about; I have not found time to dig into this deeper yet.

**Comment by behrad** [comment]
> exact duplicates

what do you mean by exact? If got it right, it's more performant to do it as a simple stringish validation at very start of subscribe method. This is heavy to pass this to an internal huge data structure like Qlobbers trie

**Comment by psorowka** [comment]
I mean:

```
some/specific/topic <-> some/specific/topic  # exact duplicate
some/specific/topic <-> some/+/topic            # matching duplicate             
```

**Comment by behrad** [comment]
right then it's more cheap to do it as a validation in subscribe before sending it down inside

**Comment by davedoesdev** [comment]
Btw the benchmark results for `QlobberDedup` on the add-many are:

```
  ┌─────────┬────────────┬───────────────┬──────────┐
  │         │ total (ms) │  average (ns) │ diff (%) │
  ├─────────┼────────────┼───────────────┼──────────┤
  │ dedup   │        742 │   742,395,946 │        - │
  │ default │      6,299 │ 6,298,590,019 │      748 │
  └─────────┴────────────┴───────────────┴──────────┘
```

You may be able to get quicker by using a separate hashtable-based structure for checking added duplicates.

Pure matching is about the same as the normal (non-deduplicating) `Qlobber`.

**Comment by davedoesdev** [comment]
@behrad what did you decide to do (if anything)?

**Comment by behrad** [comment]
Sorry for my late answer @davedoesdev Was our busy days and we are in Norouz holidays now :)
I should test `QlobberDedup` inside mosca and let you know, However I believe it should be used aside with other optimizations inside mosca as I mentioned above.

**Comment by behrad** [comment]
Finally I'm going to catch some time to spend on this guys.
I want to also hear your points on this http://250bpm.com/blog:19 @mcollina & @davedoesdev 
Seems the same challenge  ;)

**Comment by davedoesdev** [comment]
Regarding http://250bpm.com/blog:19, qlobber already stores strings on nodes in the trie.

**Comment by mcollina** [comment]
Fixed in v2.
