### ISSUE TITLE
MQTT plugin for Reveal.js presentations

### ISSUE THREAD

**Issue by roccomuso** [mcollina/mosca#429]
Hi guys,

I Just want to show you this new reveal.js plugin:
https://github.com/roccomuso/reveal.js-mqtt-plugin

It's useful to make reveal.js-based presentations showing real-time data from the MQTT network in your slides.

:)

**Comment by mcollina** [comment]
I use [bespoke](http://npm.im/bespoke), and there is no plugin, just use [MQTT.js](http://npm.im/mqtt) with browserify and connect to a websocket-enabled MQTT broker (such as test.mosca.io).
