### ISSUE TITLE
how to maintain the clients connection

### ISSUE THREAD

**Issue by mudassir-ngineous** [mcollina/mosca#430]
How can I keep the client's expiration time(disconnection time) to 15mins on mosca-broker side so that mosca should not close the socket until the client is idle for 15mins, by default this time is 01min on broker side. I know there is an option of setting 'checkFrequency' to the required time under LevelUp description but not sure if it works similarly also I could not find any example of its usage, so have little confusion. It will be great if you help me out.
Thanks.

**Comment by mcollina** [comment]
This timeout is configured on the client, setting the keepalive field in the CONNECT packet.

**Comment by mudassir-ngineous** [comment]
in my case its set to around 08 hours but still mqtt broker is closing socket in juz 5mins and client needs to reinitialize the connections. Can you tell me what could be the problem? And this is happening at exactly for 5mins if client remains idle for 5mins.

I also run some test cases on my own system by creating test client and server with following description:

1. i kept keepalive time=1000 and made communication with mqtt broker every second. this case has no question of exceptions.

3. then i kept keepalive time = 30000(thats big time) and made communication at different intervals viz. 01sec, 05mins, 06mins and 10mins, mqtt broker did not break connection with client but on LIVE environment when client is actually some remote device, the connection breaks

4. finally i kept keepalive time = 10(very small time) and tried connecting at again different intervals viz 01sec, 05mins, 06mins and 10mins, locally the connection was still alive which was, actually, supposed to be broken in case of 5/6/10 mins because of keepalive time.

**Comment by mcollina** [comment]
In 2. the socket can be closed for a lot of different reasons. Check also your server network config, your 3G/wifi connections, also VPNs, ...

I don't understand 3.

**Comment by mudassir-ngineous** [comment]
in 3, even keepalive time was set to 10sec the connection was persistent between mqtt-client and broker even after client being idle for more than 10sec ... so whats the significance of keepalive option if its not making any difference on connection. So i think there is somewhere some bug because of which keepalive parameter is not getting considered. (being a student i might even get wrong)
thanking you for your cooperation.

**Comment by psorowka** [comment]
Your MQTT client will usually send ping packets at regular intervals to keep the connection alive. The broker will only assume the connection to be lost of it does not receive a packet within the keepalive interval.

MQTT is meant to have a long-running connection so this behavior is intended.

**Comment by mudassir-ngineous** [comment]
Agree..
Is there a way where I can capture these ping packets and monitor them so
then it may give me more clear idea on behavior.

**Comment by psorowka** [comment]
If you start mosca in verbose mode it will log the ping packets

**Comment by mudassir-ngineous** [comment]
and is there any callback for this particular event in node's "mosca" library??/
