### ISSUE TITLE
How to bind mosca to an address

### ISSUE THREAD

**Issue by vallettea** [mcollina/mosca#432]
Hello,

I would like to have my client (mqttjs) to connect to an address like "http://example.com" instead of the ip address of my server. Is there a option in mosca settings to do this ? I think the option is `bind_address` in mosquito.

thanks

**Comment by mcollina** [comment]
I'm not sure what you mean. You don't bind to an URL. You bind to an host/port combination. From the man page, it seems you can pass an ip address (or localhost): http://mosquitto.org/man/mosquitto-conf-5.html
Maybe @ralight can clarify (to me `bind_address` binds to an ip).

**Comment by vallettea** [comment]
Forget mosquito, how to have a mosca instance that mqttjs can connect via a readable url instead of an ip address

**Comment by mcollina** [comment]
Here it is: https://github.com/mcollina/mosca/blob/master/examples/Server_Wtih_All%20Interfaces-Settings.js#L18-L19

**Comment by vallettea** [comment]
thanks

**Comment by ralight** [comment]
For the sake of clarity for anybody else reading, `bind_address` is for listening sockets and allows you to restrict which IP address a broker socket listens on.

**Comment by mcollina** [comment]
Thanks @ralight!
