### ISSUE TITLE
':' in a client id raises exception

### ISSUE THREAD

**Issue by cfchou** [mcollina/mosca#439]
Hi,

We found that Mosca crashes when an offline message is being delivered to a client with the id containing ':'.

Steps to reproduce the problem:
1. mosquitto_sub -h 127.0.0.1 -p 1883 -d -v -t 'test' -i '14:e6:76:46:93:31' -k 600 -q 1 -c
2. ctrl-c
3. mosquitto_pub -h 127.0.0.1 -p 1883 -q 1 -t 'test' -m 'hello'
4. mosquitto_sub -h 127.0.0.1 -p 1883 -d -v -t 'test' -i '14:e6:76:46:93:31' -k 600 -q 1 -c

The problem seems to be that in
[lib/persistence/redis.js](https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L376)
keyRegexp /^([^:]+):([^:]+):([^:]+)$/ fails to match and throws exception.

We propose to change keyRegexp to /^([^:]+):([^:]+):(.+)/.
Is there any concern regarding to this proposal?

Thank you.

**Comment by mcollina** [comment]
Yes. Please send a PR with a unit test.
Il giorno ven 1 apr 2016 alle 07:39 cfchou <notifications@github.com> ha
scritto:

**Comment by mcollina** [comment]
Fixed in v1.1.3.
