### ISSUE TITLE
server.publish not working

### ISSUE THREAD

**Issue by hptphuong** [mcollina/mosca#443]
I try to "publish a message to client", but i have met this problem:
```
 this.collection.insert(messageObj, { w: 1 }, done);
             ^

TypeError: Cannot read property 'insert' of undefined
    at EventEmitter.MongoAscoltatore.publish 
```
But when new client connect, or one client publish/subscribe anything, I still store it to my mongodb.
There is my code:

 ```
var settings = {
    port: config.mqtt.port || 1883,
    backend : {
    type: 'mongo',
    url: config.mqtt.databaseUrl,
    pubsubCollection: 'ascoltatori',
    mongo: {}
    }

  };
server = new mosca.Server(settings);
var message = {
  topic: '/hello/world',
  payload: 'abcde', // or a Buffer
  qos: 0, // 0, 1, or 2
  retain: false // or true
};

server.publish(message, function() {
  console.log('done!');
});
```

Please help me fix this issue.

**Comment by mcollina** [comment]
you need to wait that the server is up and running. You can do that passing a callback, or waiting for a `'ready'` event.

**Comment by hptphuong** [comment]
Could you give me a simple example to run this script after server "ready"?
Thank a lot.

**Comment by mcollina** [comment]
https://github.com/mcollina/mosca/blob/master/examples/Server_Wtih_All%20Interfaces-Settings.js#L47

**Comment by johnnyBira** [comment]
@mcollina can you please update the above example?
I'm running into the same issue

**Comment by jayaruvan** [comment]
@mcollina : I have copy and pasted 'https://github.com/mcollina/mosca/wiki/Mosca-basic-usage' , example (mongodb one) . I am getting the same issue.

**Comment by jayaruvan** [comment]
resolved,
// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running');

  server.publish(message, function() {
    console.log('done!');
  });
   
}
