### ISSUE TITLE
pub-acks not coming even qos=1

### ISSUE THREAD

**Issue by mudassir-ngineous** [mcollina/mosca#447]
I have set qos=1, now when mqtt-client starts publishing data to broker, client receives pub-ack for just first message sent, pub-acks do not come for rest of the message there after. Now this problem especially happens in case when my data chunk is big in size. But as far as mqtt is concerned, it takes care of big data chunks as well while publishing. So, what could be the issue???

**Comment by mcollina** [comment]
You should probably upload some code example to reproduce.
