### ISSUE TITLE
[Redis persistence] Getting away from `JSON.parse`

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#452]
I'm thinking to change subscription serialization format [in Redis] from JSON to a more performant one, That way we omit https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L98 & https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L143 & https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L339 in environments where heavy `clean: false` clients with high connect/disconnect ratios.

@mcollina  Do you think changing `JSON.parse` with comma separated `join/split` will help?

**Comment by mcollina** [comment]
@behrad no. I guess a lot of the work is wasted on serializing/deserializing buffers (for payloads), which are currently encoded in base64. I would suggest msgpack-lite or protobuf.

**Comment by behrad** [comment]
we can close this if you think not worth it,


> are currently encoded in base64

Can you point me to the related code in mosca?

**Comment by mcollina** [comment]
Actually, not base64, but as array of numbers stringified.
https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L215-L216

**Comment by mcollina** [comment]
It needs fixing, if you want to.

**Comment by behrad** [comment]
> Actually, not base64, but as array of numbers stringified.
> https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L215-L216

But this is true for retain messages, When not using them, this code is not involved...

**Comment by mcollina** [comment]
You can probably find the same logic in other places as well. Messages are
moves as JSON, and you can't send binary data in JSON..
Il giorno ven 15 apr 2016 alle 13:41 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
Both Redis mqEmitter & aedes persistence are using `msgpack-lite` instead of JSON serialization :+1:

**Comment by mcollina** [comment]
This is probably too much of a fix, and we should probably focus on shipping Aedes now.
