### ISSUE TITLE
Performance of qos=1 publishes with a high fan out

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#453]
When publishing a qos=1 message on a topic with multiple hundred thousands of subscribers, `publish` callback is called with latency.

One of area's I found in persistence is https://github.com/mcollina/mosca/blob/master/lib/persistence/redis.js#L355-L358, where storePacket is called for each subscriber, all on a single node.

**Comment by mcollina** [comment]
@behrad this is expected and designed this way, and the price you pay for offline messages. Each device has its own queue, and the sender process needs to write there.
It's probably possible to optimize that behavior, so the price is reduced, but the design of this is highly scalable, see http://highscalability.com/blog/2013/7/8/the-architecture-twitter-uses-to-deal-with-150m-active-users.html.

For high fanout topics, I highly suggest to publish them as QoS 0.

**Comment by behrad** [comment]
> For high fanout topics, I highly suggest to publish them as QoS 0

Everybody should receive the message.
One way is sending two messages: one qos=0 for online list, then a qos=1 for offline list. this method has serious problems, one of which is, fake online users may not receive any messages and works no good for real-world keepalives.

I am thinking of a customization/parametrization inside broker, which you can some how change the broker behavior by an option, for example telling broker to store offline messages with lower priority, and in batch... but without ruining actual MQTT semantics.

**Comment by mcollina** [comment]
The reason why QoS 1 messages needs to be written _before_ delivering is because of MQTT semantics, which is necessary to avoid race conditions. I don't think it's possible to achieve "prioritization", without dramatically changing the way Mosca works. However, I think we can make storing large quantities of offline messages faster.

**Comment by behrad** [comment]
> The reason why QoS 1 messages needs to be written before delivering is because of MQTT semantics, which is necessary to avoid race conditions

I see, this is (= storing & deleting each message for connected clients) a trade off we pay to avoid races.



> However, I think we can make storing large quantities of offline messages faster.

Yes, we should optimize the internals persistence to also support these scenarios, for the redis case, we can think to bulk write them... or we can even change some key structures, however this latter is a dramatic change.

**Comment by mcollina** [comment]
Is this fixed in v2.0.0? Feel free to reopen in case.
