### ISSUE TITLE
expose server pingreq event

### ISSUE THREAD

**Issue by jingwang** [mcollina/mosca#454]
It would be nice to be able to catch the pingreq event on the server, which can be used to implement the application level heartbeat, something like:

`moscaServer.on('pingreq', function(client) {
    // do something
});`

**Comment by mcollina** [comment]
Good idea, how about a PR?

**Comment by ccravens** [comment]
We are running into this issue now of heartbeat and maintaining an open connection for extended periods of time. We currently just publish a blank message to a topic called "PINGREQ" every 30 seconds to keep the connection alive. Is that best practice? Is there a Mosca server setting that we need to be cognizant of when dealing with heartbeats and keeping the connection alive for hours, days or even weeks at a time?

**Comment by mcollina** [comment]
@ccravens you should be able to achieve the same effect using MQTT own keepalive mechanism, triggered from the client (in the CONNECT packet).

**Comment by mcollina** [comment]
Closing now, feel free to reopen.
