### ISSUE TITLE
add error event for server???

### ISSUE THREAD

**Issue by stableShip** [mcollina/mosca#458]
using mosca-v1.2.0, when I start a mosca server with mongodb as persistence,rabbitmq as backend, my mongodb did not start , I started my mosca server , it did't show any error and the ready message.  I try to listen "error" event, nothing log.How can I get the error when I start the server??

```
server.on('error', function(err){
    console.log(err);
});

server.on('ready', function(){
    console.log('Mosca server is up and running');
});
```

my settting:
```
var pubsubsettings = {
    type: 'amqp',
    json: false,
    amqp: require('amqp'),
    exchange: 'ascolatore5672'
};

var moscaSettings = {
    port: 1883,
    backend: pubsubsettings,
    persistence: {
        factory: mosca.persistence.Mongo,
        url: "mongodb://localhost:27017/mosca"
    }
};
```

**Comment by mcollina** [comment]
I'm sorry but I don't understand what your issue is.

**Comment by stableShip** [comment]
![image](https://cloud.githubusercontent.com/assets/2979404/14768286/d7815e2c-0a70-11e6-9c2a-1a78c406b663.png)
![image](https://cloud.githubusercontent.com/assets/2979404/14768290/e3a830c2-0a70-11e6-88ba-8f6da851b3f9.png)
when my persistence config seted, but it can not connect to the mongodb.I hope the server will show me the connnect error message ，but there is nothing show

**Comment by mcollina** [comment]
You are right, currently Mosca is swallowing the error at startup, a callback when [this](https://github.com/mcollina/mosca/blob/master/lib/server.js#L166-L232) `async.series` completes is missing.

Would you like to send a PR?

**Comment by stableShip** [comment]
I will try , this is my first to make a PR to a project like this, please don't bet on me, but I will try my best.
