### ISSUE TITLE
Subscription and packet collection always empty (Mongo)?

### ISSUE THREAD

**Issue by remiphilippe** [mcollina/mosca#462]
Hello,
I've enabled persistence and created a subscription. 

From mosca's logs I see this:
{"name":"mosca","hostname":"surfer-10-0-0-13","pid":43757,"client":"remi_154110158","level":20,"msg":"Storing offline subscriptions","time":"2016-04-25T11:13:42.294Z","v":0}

No errors, but subscription and packet collections are always empty (but the collections themselves exist). Is this a normal behavior?

Here is the configuration:
```
var backendSettings = {
    type: 'mongo',
    //connection: db,
    pubsubCollection: config.mosca.pubsubCollection,
    url: config.db.uri,
    mongo: {}
  };

  var moscaSettings = {
    port: config.mosca.port,
    backend: backendSettings,
    persistence: {
      factory: mosca.persistence.Mongo,
      url: config.db.uri,
      ttl: {
        subscriptions: 1000 * 60 * 10,
        packets: 1000 * 60 * 10
      }
      //connection: db
    },
    logger: {
      level: 'debug'
    }
  };
  var server = new mosca.Server(moscaSettings);
```

Thanks,
Remi

**Comment by mcollina** [comment]
The log line is emitted when it checks if it needs to store any subscriptions. You are probably not setting the `clean: false` flag in your client.
