### ISSUE TITLE
Using certificate chains with broker

### ISSUE THREAD

**Issue by chakri1vr1** [mcollina/mosca#467]
Here is the current settings I am using for mosca.

```
var SECURE_KEY = '/path/to/server.key';
var SECURE_CERT = '/path/to/server.crt';
var settings = {
	port: 15873,
	publishNewClient:false,
	publishClientDisconnect:false,
	secure : {
		port: 15873,
		keyPath: SECURE_KEY,
		certPath: SECURE_CERT
	}/*,
	logger: {
        name: "TLS Server",
        level: 0,
    }*/
};
```
This was working fine when I was using self signed certificates with a single key and certificate. Now, I have got a signed certificate from GoDaddy, and they provided a chain of certificates(2 to be precise). 
http://stackoverflow.com/a/13450299 - This link gives a better understanding of the scenario
How would it be possible to add a chain of certificates? Is there a option already to use such certificates?

**Comment by mcollina** [comment]
I think you can pass a `ca` property to secure, similar to what you would do use node tls api. Have you tried that?

**Comment by chakri1vr1** [comment]
I have tried that in fact. Like this 
```
var SECURE_KEY = '/path/to/server.key';
var SECURE_CERT = '/path/to/server.crt';
var SECURE_CA = '/path/to/bundle_ga.crt';
var settings = {
    port: 15873,
    publishNewClient:false,
    publishClientDisconnect:false,
    secure : {
        port: 15873,
        keyPath: SECURE_KEY,
        certPath: SECURE_CERT
        caPaths: [SECURE_CA]
    }/*,
    logger: {
        name: "TLS Server",
        level: 0,
    }*/
};
```
It seems to be not working. Also I have tried varying that parameter name to `ca`,`caPath` while also varying the parameter value as the string path to the file vs output from `fs.readFileSync(path)`. None of them seem to work. I got confused after looking at the `interfaces.js` in the library - specially this part of the file

```
function mqttsFactory(iface, fallback, mosca) {
  var credentials = iface.credentials || fallback.credentials;
  if (credentials === undefined) {
    throw new Error("missing credentials for mqtts server");
  }

  if (credentials.keyPath) {
    credentials.key = fs.readFileSync(credentials.keyPath);
  }

  if (credentials.certPath) {
    credentials.cert = fs.readFileSync(credentials.certPath);
  }

  if (credentials.caPaths) {
    credentials.ca = [];
    credentials.caPaths.forEach(function (caPath) {
    	credentials.ca.push(fs.readFileSync(caPath));
    });
  }

  return tls.createServer(credentials, buildWrap(mosca));
}
```
whereas in server.js its mentioned that `*, additional properties are passed as options to tls.createServer (see https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener)`. Since tls originally doesn't accept path directly, I tried that `fs.readFileSync(path)`. But as I mentioned, none of them seem to work. Also one more doubt that whether it should be `secure` or `credentials` ?

**Comment by mcollina** [comment]
So, the whole options and bootstrapping is really messy, and it should definitely have a big cleanup. If you want to contribute, it would be amazing. 

In the meanwhile, try using tls directly and find out which options works. Then we'll dig into https://github.com/mcollina/mosca/blob/master/lib/options.js and https://github.com/mcollina/mosca/blob/master/lib/interfaces.js to see what's going on in there.

**Comment by chakri1vr1** [comment]
So, I tried simply creating a tls server and these options worked for me. Below is the exact code which worked. 
```
var tls = require('tls'),
fs = require('fs'),
msg ="Hello TLS World";

var options = {
	key: fs.readFileSync('/path/to/server.key'),
	cert: fs.readFileSync('/path/to/server.crt'),
	ca: fs.readFileSync('/path/to/ca-bundle.crt')
};

tls.createServer(options, function (socket) {
	console.log('server connected',socket.authorized ? 'authorized' : 'unauthorized');
	socket.write('Welcome to TLS server!\n');
	socket.setEncoding('utf8');
	socket.pipe(socket);
}).listen(15874);
```
Verified its working using a sample tls client
```

var tls = require('tls'),
    fs = require('fs');

var options = {
	host : "XXXX",
	port : XXXXX
};

var conn = tls.connect(options, function() {
  if (conn.authorized) {
    console.log("Connection authorized by a Certificate Authority.");
  } else {
    console.log("Connection not authorized: " + conn.authorizationError)
  }
    console.log();
});

conn.on("data", function (data) {
  console.log(data.toString());
  conn.end();
});
```

And it's giving correct log reply that `Connection authorized by a Certificate Authority.`.

**Comment by mcollina** [comment]
try something like this: https://github.com/mcollina/mosca/blob/master/examples/Server_Wtih_All%20Interfaces-Settings.js#L17

**Comment by chakri1vr1** [comment]
And it works like a charm :) Than you so much for the help. Just for reference, here is the final code which worked.
```
var SECURE_KEY = '/path/to/server.key';
var SECURE_CERT = '/path/to/server.crt';
var SECURE_CA = '/path/to/ca_bundle.crt';
var settings = {
	port: 15874,
	publishNewClient:false,
	publishClientDisconnect:false,
	interfaces: [
        { type: "mqtts", port: 15874, credentials: { keyPath: SECURE_KEY, certPath: SECURE_CERT, caPaths: [SECURE_CA] } }
    ]/*,
	logger: {
        name: "TLS Server",
        level: 0,
    }*/
};

```
