### ISSUE TITLE
UpdateOfflinePacket is called on all forwards

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#469]
Why are we updating all offline packets? https://github.com/mcollina/mosca/blob/master/lib/client.js#L267

This would be a huge waste in high qos>0 publish/forward rates.

Isn't better to pass the knowledge of if it should be updated to `client#forward` to only update needed packets.

**Comment by mcollina** [comment]
I'm not understading what you propose, and what is the issue here.
Il giorno dom 8 mag 2016 alle 09:31 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
Why is `UpdateOfflinePacket` called in client#forward? Do we need to update stored packet before forwarding to client?

**Comment by mcollina** [comment]
Yes, it needs to, as the messageId needs to be persisted (for offline).

**Comment by mcollina** [comment]
Closing, feel free to reopen.
