### ISSUE TITLE
Run test has error

### ISSUE THREAD

**Issue by powpi2000** [mcollina/mosca#471]
I try to commit ,but has pre-commit testing,as below is error message
  mosca.cli
    ✓ must be a function
    ✓ should start a mosca.Server
    ✓ should create a bunyan logger
    ✓ should set the logging level to 40
    ✓ should support a verbose option by setting the bunyan level to 30
    ✓ should support a very verbose option by setting the bunyan level to 20
    ✓ should support a port flag
    ✓ should support a port flag (bis)
    1) should support a parent port
  36 passing (8s)
  1 failing

  1) mosca.cli should support a parent port:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
  

What kind problem it is?

**Comment by mcollina** [comment]
It has a pre-commit check because it needs tests to pass (otherwise I will not merge it). You can skip them `git commit -n`.

You probably have another broker (mosquitto, rabbit-mq) running on your host.

**Comment by powpi2000** [comment]
Thank you reply.
If I keep test in pre-commit
I have another issue 
  1) mosca.persistence.Redis "before each" hook: build:
     Uncaught Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
      at errnoException (net.js:905:11)
      at Object.afterConnect [as oncomplete] (net.js:896:19)

  2) mosca.persistence.Redis "after each" hook: afterEachPersistenceAbstract:
     Uncaught TypeError: Cannot call method 'close' of undefined
      at Object._onImmediate (test/persistence/abstract.js:38:21)
I think I need to change redis host not to localhost (I use docker in Mac,that's a virtual machine)
How should I change redis host?

**Comment by mcollina** [comment]
In order to run the test, you need to have Redis and MongoDB running on the same host.
