### ISSUE TITLE
mqtt over websocket fail.

### ISSUE THREAD

**Issue by LanceCong** [mcollina/mosca#475]
I build a mqtt server by mosca,and it work well,thanks.
But I fail to make a javascript client by MQTT.js in this way :[https://github.com/mqttjs/MQTT.js#browserify](url) .
And I visit the website below it show the same reason.
[http://mcollina.github.io/mqtt_and_nodejs/](url)
`Firefox 无法建立到 ws://test.mosca.io/ 服务器的连接。 scripts.js:10:30683
Firefox 无法建立到 ws://test.mosca.io/ 服务器的连接。 scripts.js:10:30683
Firefox 无法建立到 ws://test.mosca.io/ 服务器的连接。 scripts.js:10:30683
Firefox 无法建立到 ws://test.mosca.io/ 服务器的连接。 scripts.js:10:30683
`
It means the firefox can't build a connection to the server of ws://test.mosca.io/
Does it(http://mcollina.github.io/mqtt_and_nodejs/) still working?

**Comment by mcollina** [comment]
Sorry, the test instance was down due to disk space exahusted (my fault! :())
