### ISSUE TITLE
About handling topics

### ISSUE THREAD

**Issue by anhldbk** [mcollina/mosca#477]
I'm gonna make `RPC calls` using `Mosca`. The pattern is:
- Subscribe to the topic which name is a generated `uuid`
- Publish a message to a service subscribing solely to `/service/check`.
- When the service finishes its job, it publishes the result to topic  `uuid`

So, for every call, we will use `one-time` topics. How will Mosca handle such topics? If there's a large number of such topics, what consequences may be?

**Comment by mcollina** [comment]
I don't think it's a good idea to use MQTT for RPC. However, Mosca can deal
with any number of topics
Il giorno mer 18 mag 2016 alle 10:07 Anh Le <notifications@github.com> ha
scritto:

**Comment by anhldbk** [comment]
@mcollina Thank you for your advice.
