### ISSUE TITLE
No return in Authorizer.js

### ISSUE THREAD

**Issue by benu2016** [mcollina/mosca#481]
Hello,

I have some trouble with Authorizer. When adding a new user, the callback function never gets a user. After some debugging, the failure seems to be in the addUser function in Authorizer.
In http://www.mosca.io/docs/lib/authorizer.js.html the description for addUser is:
```
addUser
methodAuthorizer.prototype.addUser()

@param: {String}userThe username
@param: {String}passThe password
@param: {String}authorizePublishThe authorizePublish pattern
@: (optional)
@param: {String}authorizeSubscribeThe authorizeSubscribe pattern
@: (optional)
@param: {Function}cbThe callback that will be called after the
@: insertion.
```

After a look in Authorizer.js, you will see in the add function following lines:
`Authorizer.prototype.addUser = function(user, pass, authorizePublish,
                                        authorizeSubscribe, cb) {
  var that = this;`

 ` if (typeof authorizePublish === "function") {
    cb = authorizePublish;
    authorizePublish = "\*\*";
    authorizeSubscribe = "\*\*";
  } else if (typeof authorizeSubscribe == "function") {
    cb = authorizeSubscribe;
    authorizeSubscribe = "\*\*";
  }`

 ` hasher({
    password: pass.toString()
  }, function(err, pass, salt, hash) {
    if (!err) {
      that.users[user] = {
        salt: salt,
        hash: hash,
        authorizePublish: authorizePublish,
        authorizeSubscribe: authorizeSubscribe
      };
    }
    cb(err);
  });
  return this;
}; `

The callback in the hasher function only gets the `err` parameter, instead of `that.users`.
And because hasher is a async function, `return this` always returns
first: nothing
second: the last added user

So is my thought right ?

**Comment by mcollina** [comment]
I'm not getting what is your issue

**Comment by benu2016** [comment]
According to the the description in Authorizer.js, the callback should get a user as return value, right ?
With this lines I get nothing:
`server.on('published', function(packet, client) {
    if(packet.topic == '/registration'){
        console.log('Registration request!!!');
        console.log(JSON.stringify(authorizer.addUser('testUser','123456', '/World', '/World', cb)));
    }
        
  console.log('Published', packet.payload);
});

function cb(user){
    console.log('CB:',user);
}
`

**Comment by mcollina** [comment]
No it should not.

**Comment by benu2016** [comment]
But how can I get then the user Object ?

**Comment by mcollina** [comment]
via the callback.

**Comment by benu2016** [comment]
But callback is undefined

**Comment by benu2016** [comment]
Could you please try. I only get undefined back in callback.

**Comment by mcollina** [comment]
Sorry, you don't need a user. if you dont' get an error, the thing was saved correctly.

**Comment by mcollina** [comment]
you just need to persist the authorizer.

**Comment by benu2016** [comment]
How can I persist the authorizer ?
Do you have an example ?

**Comment by mcollina** [comment]
https://github.com/mcollina/mosca/blob/master/lib/cli.js#L271-L284
