### ISSUE TITLE
client.emit is not a function

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#483]
In some cases I have

```
TypeError: client.emit is not a function
    at /root/chabok/source/node_modules/mosca/lib/persistence/abstract.js:89:16
    at /root/chabok/source/node_modules/mosca/lib/persistence/redis.js:216:7
```

Shouldn't `client.emit('error')` have been `client.connection.emit('error')`?

**Comment by mcollina** [comment]
Yes, good catch! PR?

**Comment by behrad** [comment]
sure 👍

**Comment by behrad** [comment]
Before creating PR, after checking out my upstream/master (which is mosca's master) I see tests are failing!?

`mosca server should fail if persistence can not connect`

**Comment by mcollina** [comment]
Not sure, things are passing here

**Comment by behrad** [comment]
Not on my side!

**Comment by mcollina** [comment]
tests are passing on the cloud.

**Comment by behrad** [comment]
Strange! I did it with `commit -n` !!!

**Comment by mcollina** [comment]
You might had some spurious/unwanted dependency on node_modules

**Comment by behrad** [comment]
don't know! did a clean fresh npm install
