### ISSUE TITLE
Invalid this access

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#484]
`this.clients` in https://github.com/mcollina/mosca/blob/master/lib/server.js#L247 & https://github.com/mcollina/mosca/blob/master/lib/server.js#L299 shouldn't be `that.clients`?

**Comment by mcollina** [comment]
that and this are the same there, it's set to the EE instance, feel free to send a pr to make it more readable if you like.

**Comment by behrad** [comment]
> it's set to the EE instance

So is this happening by the runtime for callbacks passed to EE#on ?

**Comment by mcollina** [comment]
yes, it's part of the EE interface.
Il giorno dom 29 mag 2016 alle 14:09 Behrad <notifications@github.com> ha
scritto:
