### ISSUE TITLE
MOSCA to Mosquitto Timeout Issue

### ISSUE THREAD

**Issue by ywadi** [mcollina/mosca#487]
There seems to be an issue when using MQTT (Vernemq or Mosquitto) as a broker backend. 
The timeout 0 should be no timeout (Stay Alive) but it disconnects after a while and does not connect again.

**Comment by mcollina** [comment]
What is your Mosca configuration and setup?

**Comment by ywadi** [comment]
Hi, Here it is 

var ascoltatore = {
  type: 'mqtt',
  mqtt: require('mqtt'),
  host: configs.mqtt.host,
  port: configs.mqtt.port,
  username: configs.mqtt.username,
  password: configs.mqtt.password,
  return_buffers: false,
  keepalive: 0
};

var moscaSettings = {
  http:{
    port: configs.websocket.port,
    bundle: true
  },
  port: program.port,
  backend: ascoltatore
};

**Comment by mcollina** [comment]
Mosca does nothing special with keepalive. You would probably want to test this against MQTT.js, and report it there.

**Comment by ywadi** [comment]
I have been debugging here and I dont really know if it is related to keep alive. 
The MQTT.JS is working perfectly fine and stays connected. Once used as per configuration the communication breaks and I have to restart the server to regain connection. 

I can not tell what is happening different in Mosca vs MQTT.JS even though they rely on each other the behavior is different.
