### ISSUE TITLE
pubsubCollection retention period 

### ISSUE THREAD

**Issue by just4give** [mcollina/mosca#488]
pubsubCollection  keeps growing as new messages are posted to the topics. I am concerned about the data volume. Is there anyway to clean up pubsubCollection  data after specified time period ?

**Comment by mcollina** [comment]
That should be a capped collection, so at some point (depending on the number of docs and size) it will stop growing.

**Comment by mcollina** [comment]
These are the defaults: https://github.com/mcollina/ascoltatori/blob/master/lib/mongo_ascoltatore.js#L53-L57.

You might want to increase them.
