### ISSUE TITLE
nedb persistence support

### ISSUE THREAD

**Issue by roccomuso** [mcollina/mosca#502]
Any plan to support also nedb for persistence?

**Comment by mcollina** [comment]
No plan. In aedes you can write your own really easily https://github.com/mcollina/aedes.

See https://github.com/mcollina/aedes-persistence-redis or https://github.com/mcollina/aedes-persistence-level as a template. Open an issue there when you are done :D, I'll add link somewhere

**Comment by ovhemert** [comment]
Hi @roccomuso 

I also needed nedb persistence and decided to write it myself.
Please check [https://github.com/ovhemert/aedes-persistence-nedb](https://github.com/ovhemert/aedes-persistence-nedb).
Or get it from npm: `npm install aedes-persistence-nedb`

**Comment by mcollina** [comment]
@ovhemert would you mind sending a PR to the Aedes README to add your persistence?
