### ISSUE TITLE
v2.0.1 - Can't Connect to Mongo

### ISSUE THREAD

**Issue by ccravens** [mcollina/mosca#503]
I've upgraded from 1.2.0 to the newest release v2.0.1

I can't connect to Mongo and can only start the Mosca server when using Memory. I have verified that when I downgrade from 2.0.1 to 1.2.0, Mongo connection works without changing the code. This is my connection code:

```
    var pubsubsettings = {
        type: 'mongo',
        url: process.env.MONGOLAB_URI || 'mongodb://localhost:27017/app',
        pubsubCollection: 'mqtt',
        mongo: {}
    };

    var server = new mosca.Server({
        persistence: {
            // factory: mosca.persistence.Memory,
            factory: mosca.persistence.Mongo,
            url: process.env.MONGOLAB_URI || 'mongodb://localhost:27017/app' 
        },
        backend: pubsubsettings
    }, function(err) {
        console.error('ERROR: ');
        console.error(err);
        server.attachHttpServer(app);
    });
```

There is no error object returned in the callback (console.error(err) does not output anything). In fact, the callback is never called at all when using factory: Mongo... However, when I comment-out Mongo and un-comment Memory, Mosca starts.

Is anyone else able to reproduce?

**Comment by mcollina** [comment]
Can you please upload a full example (including package.json) that it is exhibiting the issue? (maybe set up a new repo or a gist).
