### ISSUE TITLE
How do two mosca brokers communicate?

### ISSUE THREAD

**Issue by linyanwen** [mcollina/mosca#505]
Suppose there are two clients called ClientA and ClientB, and there are two mosca brokers called brokerA and brokerB. 
And suppose brokerA is deployed on machine_A, and brokerB is deployed on machine_B.
ClientA and ClientB use the same topic.
ClientA publish message to the brokerA.
ClientB subscribe  topic from brokerB.
My Question is:
If ClientA publish a message to brokerA, how can ClientB get the message from brokerB?
Should we establish a tcp connection between brokerA and brokerB?

If I want to deploy many brokers on different machines for the disaster recovery,
what am I supposed to do?

Thank you

**Comment by behrad** [comment]
> If ClientA publish a message to brokerA, how can ClientB get the message from brokerB?
> Should we establish a tcp connection between brokerA and brokerB?

it depends to the backend and persistence you choose. With Redis you can achieve this, you only need to configure mosca to run with redis backend & redis persistence.

Things go this way: 
A publishes to moscaA, mosca publishes A's publish to all mosca instances (including moscaB) using redis PUB/SUB, moscaB receives the publish, matches B, and forwards the message to B :) 

For offline messages when QOS>0 there's a bit more to it.

**Comment by ruizeng** [comment]
@behrad If this works when using rabbitmq backend?

**Comment by behrad** [comment]
I haven't used mosca with rabbitmq, but it uses AMQP to sit on top of RabbitMQ, and https://github.com/mcollina/ascoltatori/blob/master/lib/amqp_ascoltatore.js shows that YES, it should work :)

**Comment by ruizeng** [comment]
@behrad thanks. I'll make a test to verify that.

**Comment by linyanwen** [comment]
@behrad thanks
