### ISSUE TITLE
offline message not delivering 

### ISSUE THREAD

**Issue by anishmenon** [mcollina/mosca#506]
mosca server is running in 1882

**server.js**

```
var mosca = require('mosca');

var ascoltatore = {
  //using ascoltatore
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};

var settings = {
  port: 1883,
  backend: ascoltatore
};

var server = new mosca.Server(settings);

server.on('clientConnected', function(client) {
    console.log('client connected', client.id);
});

// fired when a message is received
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});

server.on('ready', setup);

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running');
}
```

and mqtt client side . **mqttclient.js** 

```

var mqtt    = require('mqtt');
var client  = mqtt.connect('mqtt://localhost');
 
client.on('connect', function () {
  client.subscribe('presence');
});
 
client.on('message', function (topic, message) {
  // message is Buffer 
  console.log(message.toString());
});

```

i sent a message through CLI
`mqtt pub -t 'presence' -h 'localhost' -m 'from MQTT.js' -q 2
`

but its not showing out put of previous message which sent when mqttclient.js is offline or not running. ?

**Comment by mcollina** [comment]
qos 2 is not currently supported.

**Comment by anishmenon** [comment]
So how can i get the offline messages ? please support .

**Comment by mcollina** [comment]
You should use qos 1.

**Comment by anishmenon** [comment]
@mcollina . Its not working 

consider that i'm not running  **mqttclient.js**

Then i run 

`mqtt pub -t 'presence' -h 'localhost' -m 'from MQTT.js' -q 1
`
After this i run 

`node mqttclient.js
`
no message displayed . its sowing message only when its (**mqttclient.js**) running

**Comment by mcollina** [comment]
You need to connect with clean: false, and set a clientId.

**Comment by anishmenon** [comment]
@mcollina  . 

`mqtt pub -t 'presence' -h 'localhost' -m 'from MQTT.js' -q 1 
`
after some time i run --no-clean  and client id  anishmenon

`mqtt sub -t 'presence' -h 'localhost' -q 1  --no-clean  -i anishmenon
`

again no message

**Comment by mcollina** [comment]
the offline subscription is created after the first subscription.

**Comment by anishmenon** [comment]
@mcollina  that means . can you please reply me what to do next step or what i have done wrong .

**Comment by mcollina** [comment]
First do the subscribe, then the publish, then the subscribe again.

**Comment by anishmenon** [comment]
Yes done as per u said . But no offline messages on second subscription

**Comment by mcollina** [comment]
you need to add a persistence in the Mosca configuration

**Comment by anishmenon** [comment]
@mcollina . can you please show me an example in this example i'm using mongodb

**Comment by mcollina** [comment]
https://github.com/mcollina/mosca/blob/master/examples/mongodb/config.js

**Comment by anishmenon** [comment]
```
var mosca = require('mosca');

var ascoltatore = {
  //using ascoltatore
  type: 'mongo',
  url: 'mongodb://localhost:27017/mqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};



var settings = {
  port: 1883,
  backend: ascoltatore
};


module.exports = {

  persistence: {
    factory: mosca.persistence.Mongo,
    url: "mongodb://localhost:27017/mosca",
  }
};

var server = new mosca.Server(settings);

server.on('clientConnected', function(client) {
    console.log('client connected', client.id);
});

// fired when a message is received
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});

server.on('ready', setup);

// fired when the mqtt server is ready
function setup() {
  console.log('Mosca server is up and running');
}

```

@ Still its not working

**Comment by anishmenon** [comment]
@mcollina  it work now


i've added it inside settings


```


var settings = {
port: 1883,
persistence: {
factory: mosca.persistence.Mongo,
url: 'mongodb://localhost:27017/mqttpres',
},
backend: ascoltatore
};
```
