### ISSUE TITLE
How to map with publishers and subscribers

### ISSUE THREAD

**Issue by prayagvakharia** [mcollina/mosca#508]
I am using mosca broker.
There are 10 device who publish data and each publisher have 10 subscribers client.
Subscriber how to map with their publisher?

ex:
pub1 ---- Mosca Broker --- sub1
pub2 ---- Mosca Broker --- sub2
pub3 ---- Mosca Broker --- sub3
...
...
pub10 --- Mosca Broker --- sub10

I have 10 devices which is work as publihser and i have used same topic name for all devices and each publisher have unique client for subscribe message. For all i have single Mosca Broker server.

**Comment by mcollina** [comment]
Sorry I don't understand your use case.

**Comment by prayagvakharia** [comment]
I have 10 device (which is publish data) for heart pulse sensor.
now 10 device are used by 10 people and they have there unique 10 client application (which is subscribe data).

For all these devices and client application i have used single mosca server.

So how i can map device 1 with client application 1, device 2 with client application 2 and so on.

**Comment by mcollina** [comment]
client and application needs to be agree on which topic to use. Usually the uuid/serial of the client?

**Comment by prayagvakharia** [comment]
Got it. Thanks.
First I need to sync with client and application via uniqe id either uuid/serial can be right choice. which wil be use in topic.
