### ISSUE TITLE
Query for IOT framework using mosca broker.

### ISSUE THREAD

**Issue by prayagvakharia** [mcollina/mosca#515]
I have couple of query to develop IOT framework using mosca broker.

1. Can i use kafka without docker in mosca broker?

2. How much max topic mosca can support? or what are the limitation? my use case is human-IOT system.

3. I want to use Apache storm with mosca broker is it possible.. if possible then any document or help/guide to enhance mosca broker i am ready to work on that. we have "node-storm" module available.

-  One workaround i have found using mosca broker use kafka as it supported and from kafka we can easily pass message to storm. But again if mosca and kafak's role is like broker so is it good way to use both together?

4. If future if i need to add Casandra to enhance mosca then how can I add? -- low priority

Thanks,
Prayag

**Comment by mcollina** [comment]
> Can i use kafka without docker in mosca broker?

Yes

> How much max topic mosca can support? or what are the limitation? my use case is human-IOT system.

Most of the limitation is on the number of subscriptions, not topics.

> I want to use Apache storm with mosca broker is it possible.. if possible then any document or help/guide to enhance mosca broker i am ready to work on that. we have "node-storm" module available.

It depends on your application, it's hard to discuss without knowing your specific use case.

> One workaround i have found using mosca broker use kafka as it supported and from kafka we can easily pass message to storm. But again if mosca and kafak's role is like broker so is it good way to use both together?

I do not understand this question.

> If future if i need to add Casandra to enhance mosca then how can I add? -- low priority

It depends how and what you want to achieve.

**Comment by mcollina** [comment]
You should probably contact him via email if you want to discuss your specific use case.
