### ISSUE TITLE
Install Complains With Errors

### ISSUE THREAD

**Issue by japita-se** [mcollina/mosca#523]
`npm intall mosca -g`

In file included from ../src/reader.h:1:0,
                 from ../src/hiredis.cc:1:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
make: *** [Release/obj.target/hiredis/src/hiredis.o] Error 1
make: Leaving directory `/usr/lib/node_modules/mosca/node_modules/hiredis/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.19.8-100.fc20.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/mosca/node_modules/hiredis
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
......
npm http 200 https://registry.npmjs.org/fs-ext/-/fs-ext-0.5.0.tgz
make: Entering directory `/usr/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>

**Comment by mcollina** [comment]
you should install node v4, v0.10 is not supported anymore.

**Comment by japita-se** [comment]
Thank you.

**Comment by japita-se** [comment]
I think the right version is v6 not v4 because with v4 I still get errors.
make: Entering directory `/usr/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/usr/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.19.8-100.fc20.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/mosca/node_modules/ascoltatori/node_modules/zmq
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
