### ISSUE TITLE
Can't deploy app with version 2.0.2

### ISSUE THREAD

**Issue by marcoschwartz** [mcollina/mosca#528]
Hi, I am currently using Mosca along with a Meteor app (Meteor 1.4, so using Node.js 4.4.7). Since the update I got the following messages when trying to deploy my app:

	bash: line 46: [: ./Server_Wtih_All: binary operator expected
	bash: line 50: [: ./Server_Wtih_All: binary operator expected
	bash: line 54: [: ./Server_Wtih_All: binary operator expected
	bash: line 5: cd: ./*: No such file or directory

Any idea of how to solve this? Thanks!

**Comment by mcollina** [comment]
I have zero experience in meteor, and little time to dig into it :/. I'm happy to review any PR that might address this issue.

**Comment by mcollina** [comment]
Did you fix it? Can we close?

**Comment by marcoschwartz** [comment]
Seems like a Meteor-only issue, so sure you can close it :)
