### ISSUE TITLE
Can't install on raspberry pi

### ISSUE THREAD

**Issue by Roaders** [mcollina/mosca#529]
Hi All

I am trying to install on my raspberry Pi (I have 2 and have tried both) and am having some issues. I have tried both with and without the `-g` flag.

I am simply using 

`npm install mosca`

but this seems to kill my raspberry pi. The terminal window locks up and other terminal windows stop responding. I have to restart the pi by pulling the power out.

I imagine that the npm install command is doing a make that swamps the cpu.

Is this expected? Do I just have to wait longer?

This is on a Raspberry Pi 3 with Raspbian Jesse.

Thanks

**Comment by mcollina** [comment]
I have used Mosca on raspberry pi and it works good.
Maybe that's something weird on your box.
Do you have some logs? Have you tried to keep your pi running, if it freezes? It needs to do some compilation.

If you can't get around this, try using https://github.com/mcollina/aedes.
It's lighter and has very few dependencies.
