### ISSUE TITLE
How is Redis memory used?

### ISSUE THREAD

**Issue by bobvanluijt** [mcollina/mosca#530]
Hi all,

I am experimenting with Mosca and Redis. This all works great. But I would like to understand how Mosca uses Redis. Will it clean up the keyspace after it is used? Can I set up a relatively small Redis server and still process large amounts of messages?

Thanks

**Comment by mcollina** [comment]
I think so. I don't have time to explain it in detail, the big guide is the code :(.

**Comment by bobvanluijt** [comment]
Cool, thx ;-)
