### ISSUE TITLE
Shared Subscriptions with Mosca?

### ISSUE THREAD

**Issue by mharizanov** [mcollina/mosca#537]
I'm looking at the shared subscriptions that hivemq has and wondering if anything similar is possible? My goal is to have multiple node.js workers load balance and handle same topic.

http://www.hivemq.com/blog/mqtt-client-load-balancing-with-shared-subscriptions/

Any pointers?

**Comment by mcollina** [comment]
I recommend sticking that logic in the broker in those cases. Listen to the published event. The end result will be faster.
