### ISSUE TITLE
why remove retransmissions on qos 1

### ISSUE THREAD

**Issue by moria** [mcollina/mosca#539]
hi mcollina thank you for your great work, 
i have read the code and find that the inflight messages just publish to client but without retry.
in the code history i found that [on 13 Apr 2014](https://github.com/mcollina/mosca/commit/f4beee3191f90d23db16de08e13cc4395f16f41f#diff-50cfa59973c04321b5da0c6da0fdf4fe) you have remove the retransmissions and resend the offline message by client reconnction (probably when the inflight message number increase to 1024 then server will close the connection) 

i want to know why you replace the retransmissions with resend on connect because i am thinking add retransmissions on the first time.

**Comment by mcollina** [comment]
The answer is.. it was 2014. I do not remember, and I would have to dig.

Why this is problematic for you? Can please attach some code that reproduce the issue? What is the correct behavior in yoiur opinion?

You can also issue a PR and we'll discuss there.

**Comment by moria** [comment]
@mcollina 
sorry i put the link into "on 13 Apr 2014"
the history link is below:
https://github.com/mcollina/mosca/commit/f4beee3191f90d23db16de08e13cc4395f16f41f#diff-50cfa59973c04321b5da0c6da0fdf4fe

**Comment by mcollina** [comment]
Is this still a problem? Closing for now, but feel free to reopen.
