### ISSUE TITLE
MessageId in mosca is different from the messageId in mqtt.js client

### ISSUE THREAD

**Issue by sn0opr** [mcollina/mosca#542]
I would like to thank you for this huge work. 
When I publish a message from mqtt.js client, and console.log the sent packet, I get a messageId as a number example: `54110` (which it's generated randomly, if I understood the code), but in the server I see it in this format: `BJLC51Dn`.

**Comment by mcollina** [comment]
It is overridden here https://github.com/mcollina/mosca/blob/master/lib/server.js#L351 to have a unique id.

**Comment by sn0opr** [comment]
@mcollina what is the reason to override it ?
If I disable this override and get the default messageId from the received packet, will it cause any conflict or something ?

**Comment by mcollina** [comment]
@sn0opr exactly. https://github.com/mcollina/aedes uses a different design that does not suffer from this issue.
