### ISSUE TITLE
Fatal errors when building the Dockerfile

### ISSUE THREAD

**Issue by brett--anderson** [mcollina/mosca#546]
I just cloned the repo and then built the Dockerfile with the command

```
docker build -t mosca .
```

Two fatal errors were thrown. One was:

```
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
```

which I was able to solve by adding `apk add krb5-dev` to the Dockerfile.

The other error was:

```
make: Entering directory '/usr/src/app/node_modules/ascoltatori/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
```

I haven't had any luck solving this second error. The install continues to run to completion after these errors. Will these errors impact Mosca (specifically as a Kafka-MQTT bridge)? Is there a way to solve this second error?

**Comment by mcollina** [comment]
I think this was fixed, feel free to reopen.

**Comment by matthewberryman** [comment]
Have fixed kerberos and zeromq build errors for all docker files, in https://github.com/mcollina/mosca/pull/666
