### ISSUE TITLE
Catch Mongo - DB connect error

### ISSUE THREAD

**Issue by gbaumgart** [mcollina/mosca#548]
Hi,
how would would catch a connection error 'ECONNREFUSED' when using MongoDB ? 

I saw some issue and pull request about this and so I tried all latest versions on Node-v4.4.7 but its still crashing my whole application. 

is this a bug ?

i tried this and also within a try clause 
var server = new mosca.Server(moscaSettings,function(err){
 console.error('error starting Mosca',err);
});

**Comment by mcollina** [comment]
Some notes:

a) why do you need to catch this error? You are try to connect to Mongo, and mongo is not there.
b) can you please upload the full stacktrace?
c) you should be able to catch this

**Comment by gbaumgart** [comment]
here the code: 

a) as in any end-user application which enables user input for connectivity, we need to be able to catch this just. nothing special, or? apart from user wrong input, i think its a good idea to process the mongo client connect errors and forward to the user. 

```
try {

                var server = new mosca.Server(moscaSettings);
                server.on('error', function(err) { console.log('maeh' + err.message); });
                server.on('ready', setup);
                server.on('clientConnected', function () {
                    debug && console.log('MQTTManager :: mqtt client connected');
                });

                server.on('clientDisconnected', function () {
                    debug && console.log('MQTTManager :: mqtt client disconnected');
                });
                thiz.server = server;
            }catch(e){
                console.error('error starting mosca ',e);
            }
```
b) ```

/PMaster/projects/x4mm/server/nodejs/node_modules/mongodb/lib/mongo_client.js:225
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at null.<anonymous> (/PMaster/projects/x4mm/server/nodejs/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/PMaster/projects/x4mm/server/nodejs/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/PMaster/projects/x4mm/server/nodejs/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

c) yes, that's what i expected, as for any other client library. so i tried all sort of things, but no matter what i do, its crashing my whole back-end. 

thanks a lot , thanks for the heads up!

**Comment by mcollina** [comment]
Can you please upload a full example that shows the problem?

**Comment by gbaumgart** [comment]
sure,
```
....
try {
                var server = new mosca.Server(
                    {
                        "port": "1883",
                        "persistence": {
                            "url": "mongodb://localhost:27017/mqtt"
                        }
                    }
                );
                
            }catch(e){
                console.error('error starting mosca ',e);
            }
     ....
```

at the end you can reproduce this easily by having Mongodb just down.

"mosca": "^2.1.0",
"mongodb": "^2.2.10"

**Comment by mcollina** [comment]
Can you please upload a full project, with clear steps?

**Comment by gbaumgart** [comment]
i must add that i had at least an ERR_CONNECTION_REFUSED (uncatchable) before updating to latest mosca/mongodb.

**Comment by gbaumgart** [comment]
a full project ? its 4.5 mio lines of code, at least,....

can't you just test one of your examples with an offline Mongo-DB? Or are you suggesting it should be catchable and I am doing it wrong? 

will try against one of your examples now

**Comment by gbaumgart** [comment]
here, from your 'embedded' example, same output: 

```


var mosca = require('mosca');

var ascoltatore = {
    //using ascoltatore
    type: 'mongo',
    url: 'mongodb://localhost:27017/mqtt',
    pubsubCollection: 'ascoltatori',
    mongo: {}
};

var moscaSettings = {
    port: 1883,
    backend: ascoltatore,
    persistence: {
        factory: mosca.persistence.Mongo,
        url: 'mongodb://localhost:27017/mqtt'
    }
};

try {
    //tried with and without callback
    var server = new mosca.Server(moscaSettings, function (err) {
        console.log('something');
    });
    server.on('ready', setup);

    server.on('clientConnected', function (client) {
        console.log('client connected', client.id);
    });

// fired when a message is received
    server.on('published', function (packet, client) {
        console.log('Published', packet.payload);
    });

// fired when the mqtt server is ready
    function setup() {
        console.log('Mosca server is up and running')
    }
}catch(e){
    console.error(e);
}
```

**Comment by mcollina** [comment]
I'm still not getting what you are trying to achieve. Something I can `git clone` and be sure that it shows the issue.

The try-catch of course does not work, we are in Node.js and errors are asynchronous.
You will have to listen to the `'error'` event.

**Comment by gbaumgart** [comment]
you just need to paste the example in a js file and run it. you will see that you cant catch the connection error. it will just crash with no error callback or whatsover called.

so its very simple: don't crash, just call something so the consumer has chance to go on and tell the user that his settings didnt work or mongo is offline, especially in a single thread world. otherwise we would be in a world of blue screens or kernel panics just because some nodes went down :-)

if that is too difficult, i could introduce a simple tcp port check on my side and keep moving,...

**Comment by gbaumgart** [comment]
as said, it seems that mongo-client kinda queues the connection job and picks it up on a "next tick" and so possibly the originating caller is lost. 

so i was even digging in your code and your error callback (second ctr. arg) isnt even called.

**Comment by gbaumgart** [comment]
ups: i tried the server.on(error), it never gets there

**Comment by mcollina** [comment]
@gbaumgart now it is (on master), releasing soon.

**Comment by gbaumgart** [comment]
very well, thanks so much !
