### ISSUE TITLE
Loadbalancing Mosca server using HAProxy

### ISSUE THREAD

**Issue by Urmik** [mcollina/mosca#550]
Hello,

I have successfully implemented Mosca server with RabbitMQ as a backend on single server.
Now i am planning to use HAProxy for loadbalancing in two Mosca Server.
Please find my below flow diagram
![mosca_haproxy](https://cloud.githubusercontent.com/assets/7677861/19110951/98208426-8b1a-11e6-9632-2b11a477e2bc.jpg)

I have few questions regarding that
1) Which is the better way
     - Clustering RabbiMQ of two different servers ? or
     -  Both servers accessing same RabbitMQ ?

2) What should be HAProxy server hardware configuration? 
    It should be same as Mosca server? (My Mosca server config : 32 GB RAM, 8 Core CPU)

3) What if HAProxy server itself goes down?

Regards,
Urmik

**Comment by cendrizzi** [comment]
1. This is tough to ask. If you cluster you can potentially have more availability at the expense of more complexity. It's really down to your orgs needs.

2. Any answer might be a guess. HAProxy scales quite well, but depending on how many messages you are sending over mqtt etc everything changes. The best you can do is load test to see where your bottlenecks are.

3. A lot of people use pacemaker to cluster haproxy: http://clusterlabs.org/pacemaker.html. There are various tutorials out there on this.

**Comment by mcollina** [comment]
@cendrizzi thanks for the answer. Great job!
