### ISSUE TITLE
Shared Subscriptions

### ISSUE THREAD

**Issue by behrad** [mcollina/mosca#551]
How easy can we support `$shared:my-topic` subscriptions for subscriber load balancing @mcollina ?
http://www.hivemq.com/blog/mqtt-client-load-balancing-with-shared-subscriptions/

**Comment by mcollina** [comment]
It would be extremely hard and off standard.
You can achieve much better reliability by using the `published` handler and QoS 1.

I think it might feasible in Aedes, if you want to give it a stab. In mosca it might be extremely hard.

**Comment by Llorx** [comment]
Since SEP 2016 is an accepted standard: https://issues.oasis-open.org/browse/MQTT-234

**Comment by mcollina** [comment]
MQTT 3.1.1 does not include that. Ideally it will be in MQTT 5. As I said before, I'm happy to receive new features in Aedes. https://www.npmjs.com/package/aedes

**Comment by Llorx** [comment]
Oh yeah, `Affects Version/s: 5`. Silly me. Don't noticed.
