### ISSUE TITLE
Retain message delivered with empty payload upon client subscribtion

### ISSUE THREAD

**Issue by liorshalev01** [mcollina/mosca#558]
Using Mongo persistence, retained messages delivered with empty payload.

It looks like the problem in with the line `data.payload = data.payload.buffer`
([lib/persistence/mongo.js#282](https://github.com/mcollina/mosca/blob/master/lib/persistence/mongo.js#L282)), `data.payload.buffer` is undefined. 
Might be a problem Mongo driver version mismatch?

Regards,
Lior

**Comment by mcollina** [comment]
Probably, what's the problem? can you send me some example? Or a PR?

**Comment by liorshalev01** [comment]
Hi Matteo,
We farther investigated the problem, and it's origin was when we used Mosca to publish a message. We had to first convert string payload into a buffer before handing them over to Mosca internal publish.

Thanks,
Lior
