### ISSUE TITLE
I need to use Mosca in another Express application and need to deploy on Heroku

### ISSUE THREAD

**Issue by usmantahirr** [mcollina/mosca#561]
I am using Mosca in a node express app and I want to assign it to a route, lets say its urk/mqtt and deploy it on heroku. Lets say our URL is https://url.herokuapp.com/mqtt and I must be able to utilize all its features on this endpoint.

**Comment by mcollina** [comment]
You will need to use websocket and http. Standard MQTT will not work, as Heroku does not offer TCP load balancing.

See examples.
