### ISSUE TITLE
mosca -v | bunyan on startup Raspberry PI

### ISSUE THREAD

**Issue by Maxmudjon** [mcollina/mosca#567]
after reboot raspberry pi 3 does not start mosca. In the /etc/init.d script he added
sctipt

cd /home/pi
sudo /home/node_modules/mosca/bin/mosca -v | bunyan
echo "Mosca MQTT run"

**Comment by mcollina** [comment]
That `/etc/init.d` script was not bundled with mosca, so I do not think it's a bug here.

**Comment by Maxmudjon** [comment]
please help

**Comment by mcollina** [comment]
Closing for low activity
