### ISSUE TITLE
Support for redis:url configuration

### ISSUE THREAD

**Issue by oncletom** [mcollina/mosca#571]
Hello and thanks for your project :-)

I see in the [advanced usage](https://github.com/mcollina/mosca/wiki/Mosca-advanced-usage) there is no way to connect to redis via the `url` option. Likewise `mongo` driver, it is very handy to configure everything at once, like `redis://user@host:port/db`.
Cf. [redis options](https://www.npmjs.com/package/redis#options-object-properties)

Is there any chance to support this form?

It would make the settings look like this:

```js
var pubsubsettings = {
    type: 'redis',
    redis: require('redis'),
    url: process.env.REDIS_URL,
    return_buffers: true
};
```

**Comment by mcollina** [comment]
> Is there any chance to support this form?

Yes, send a pull request! :)
