### ISSUE TITLE
Using mosca with emqtt

### ISSUE THREAD

**Issue by helpme1** [mcollina/mosca#575]
Is it possible to use mosca with emqtt as the primary broker?
http://emqtt.io/
emqtt is known for its scalability.

Under the link below, it seems that emqtt is not supported. Is it possible to add emqtt to this list of supported brokers?
https://github.com/mcollina/mosca/wiki/Mosca-advanced-usage

**Comment by mcollina** [comment]
At the moment no, I have no bandwidth. I do not think it will be possible.
