### ISSUE TITLE
Mosquitto and mosca: differences?

### ISSUE THREAD

**Issue by rokka-n** [mcollina/mosca#576]
Hi,

Are there any advantages of implementation for the broken in node? 
I'm pondering about performance and architectural differences between mosca and mosquitto.

Thanks!

**Comment by mcollina** [comment]
Mosquitto is written in C++. Mosca is written on top of Node.js.
Mosquitto uses less resources, but Mosca can scale on multiple hosts.

**Comment by mcollina** [comment]
To know if you are using Mosquitto as a service, check if Mosquitto is receiving your messages.
You do not need to do this to use Mosca.
