### ISSUE TITLE
Message write EPIPE in multiple conections

### ISSUE THREAD

**Issue by frsisalima** [mcollina/mosca#579]
It appears in the following message when I generate multiple connections, is it normal?
How many connections can I keep with fly server, thanks.

MESSAGE IN CONSOLE:

{"pid":17339,"hostname":"mi-ip","name":"mosca","level":40,"time":1481647873900,"msg":"write EPIPE","type":"Error","stack":"Error: write EPIPE\n    at exports._errnoException (util.js:1036:11)\n    at WriteWrap.afterWrite (net.js:794:14)","client":"cliente-1365","v":1}

**Comment by mcollina** [comment]
That's ok. a connection with a client broke.

How many connections is limited by your OS configuration, your RAM, and the overall message throughput. It's hard to predict, you will have to benchmark.

You can configure the server using https://gist.github.com/mcollina/23c788bf2f7e8da10b9c

**Comment by frsisalima** [comment]
Thanks matteo I will be on the penny I think the message is shown with more
than 5000 connections, because if then it can be a server configuration, I
will follow your recommendations to check what happens, thank you.
Greetings.

2016-12-14 6:50 GMT-05:00 Matteo Collina <notifications@github.com>:
