### ISSUE TITLE
Dockerfile-rpi not working

### ISSUE THREAD

**Issue by jcsogo** [mcollina/mosca#582]
I have tried first running the image of mosca from docker hub, but that one is compiled for amd64, not rpi (it would be a good idea to add a rpi version)

Then I have tried to compile my own one using Dockerfile-rpi. It was giving me several problems, until I decide to upgrade the rpi-node image from version 4 to version 6. This made everything compile and work.
 
-FROM hypriot/rpi-node:4
+FROM hypriot/rpi-node:6

**Comment by mcollina** [comment]
I've just triggered a build for dev-rpi. let me know if pulling that works.

**Comment by mcollina** [comment]
Hint, probably not. https://hub.docker.com/r/matteocollina/mosca/builds/bfzxinntndkq6zpbtdzoygm/

Docker Hub autobuild is not ARM.

**Comment by mcollina** [comment]
I've removed the autobuild for the rpi version, and updated the Dockerfile-rpi script.

**Comment by jcsogo** [comment]
You right and Docker Hub is not running arm builds, so all the rpi images
are built elsewhere and pushed.

For reference, a solution to automate it
https://forums.docker.com/t/automated-build-raspberry-pi-based-image-on-docker-hub/4155

Thanks for your help and for the piece of software itself.
