### ISSUE TITLE
Track active subscriptions

### ISSUE THREAD

**Issue by oss-ian** [mcollina/mosca#585]
Hey, I was wondering if there was a way to see how many devices/clients are currently subscribed to a topic. This would be useful to keep track of how many devices/clients are online and listening. Also, being able to get a list of all the devices/clients names would be useful.

For this feature to be useful, only some logged in clients could see this data, as it could be seen as sensitive information.

**Comment by mcollina** [comment]
You would have to do it yourself, and use the events that are emitted by the broker.
See https://github.com/mcollina/mosca/blob/master/lib/server.js#L82-L94.

**Comment by oss-ian** [comment]
@mcollina So have nodejs count clients as they join?

**Comment by mcollina** [comment]
The total number is provided in https://github.com/mcollina/mosca/blob/master/lib/stats.js.
