### ISSUE TITLE
Historical Data & Persistence

### ISSUE THREAD

**Issue by diginfo** [mcollina/mosca#595]
I guess I am a bit confused over the persistence setup, initially I thought that it allowed received data to be saved so that you could view historical data as well as now data.

But now I think it is probably just to allow resuming in the case of a crash, or engine restart etc ?

Can you clarify this and also let me know how I can store / retrieve historical data.

Many Thanks

**Comment by mcollina** [comment]
Persistence is for storing retained messages, and provide offline capabilities for the devices.
If you need to integrate a time series tracker, it is possible via the `'publish'` but you will have to provide your own logic. Let me know if you need help with that.

**Comment by diginfo** [comment]
Thanks so much for replying, appreciate that.

But could you explain how I can access historical data, as at the moment all I am able to see is the live data.

Many Thanks
