### ISSUE TITLE
Historical Data & REDIS

### ISSUE THREAD

**Issue by diginfo** [mcollina/mosca#597]
My apologies for partially repeating this question, but I have looked thru the wiki and I cannot find an answer to this issue.

I have setup mosca using the REDIS config here: https://github.com/mcollina/mosca/wiki/Mosca-basic-usage

But when I check the /var/log/redis.redis.log file all I see is the engine starting up and no evidence of any data being received.

When I login to redis client & issue **KEYS *** I see no evidence of any data being sent to redis ?

Everything works fine with subscriptions and live connections, but I don't know how I can connect to mosca and retrieve subscription data from some time in the past ?

Maybe I am missing something as I am quite new to mqtt, but I would really appreciate some guidance on how to retrieve historical data for a subscribed topic.

Many Thanks

**Comment by mcollina** [comment]
@diginfo you cannot do that, it's not part of Mosca. If you need any help in adding historical capabilities, you need to store it into something like https://www.influxdata.com/. I would be very happy to help you develop that as part of a support or professional services contract.
