### ISSUE TITLE
Implement authentication and authorization on separate threads

### ISSUE THREAD

**Issue by manikawnth** [mcollina/mosca#600]
Since authentication happens on every connect and auth Pub/Sub happens on every message of a topic, is it possible to **optionally** implement those functionalities on a separate threads. It would be helpful to implement strong CPU intensive hashing mechanisms while authenticating.

1.  Offload the auth logic on to a separate thread
2.  Use web-worker threads instead of separate node processes (Ref: https://github.com/audreyt/node-webworker-threads)
3. Once the web-worker returns, call the callback with true/false.

**Comment by mcollina** [comment]
@manikawnth nothing prevent you to do any of that. Have you tried benchmarking it?

**Comment by manikawnth** [comment]
Hi Matteo, you can ignore the request. It's not giving enough benefits. Threading / separate process have their own communication overheads. Hashing is just a 1 second blip which happens only during authentication. So this is not a big issue.
