### ISSUE TITLE
Client connect/disconnect events also triggering 'published' events

### ISSUE THREAD

**Issue by manikawnth** [mcollina/mosca#601]
Hi,

When a client publishes a messages, the connect and disconnect events are also emitting `published` events.
Is this a design necessity? Or can we just emit `published` event only for message topics and not client topics ?

This is the line I'm referring
https://github.com/mcollina/mosca/blob/master/lib/server.js#L383

**Comment by mcollina** [comment]
It is a necessity. You should filter based on topic.
