### ISSUE TITLE
amqp exchange setting

### ISSUE THREAD

**Issue by buff** [mcollina/mosca#610]
Hi,
I understand the client is to be used to setup non default host, port info.
When I use it the exchange parameter does not seem to have any effect.
If I don't use the client the exchange is created.
I have tried using the defaultExchangeName property as well as the exchange property but none of these seem to have any effect. The broker does seem to be working but with a default exchange... possibly amq.topic

**Comment by mcollina** [comment]
You should probably check the internals in https://github.com/mcollina/ascoltatori.

**Comment by buff** [comment]
Seems to also imply that using the property 'exchange' is all that is required. My settings are:
var pubsubSettings = {
    json: false,
    client: client,
    exchange: config.EXCHANGE_RABBIT,
    amqp: require('amqp')
};
Where config.EXCHANGE_RABBIT is the exchange name... If I have the same properties without the client property I see the exchange is created.

**Comment by buff** [comment]
This can be closed... I found another reference to the settings. I misread the definition for the client. It is actually the options for the amqp.createConnection method. I was trying to pass the result of the method. Maybe an example with client should be added to the wiki?

**Comment by mcollina** [comment]
@buff would you like to add one?

**Comment by buff** [comment]
@mcollina No problem. I have not actually ever done so... What would I have to do?

**Comment by mcollina** [comment]
there is an edit button in the wiki page

**Comment by buff** [comment]
@mcollina done... I thought there was some more convoluted process...
