### ISSUE TITLE
Redis backend password provided deadlocks the new mosca.Server

### ISSUE THREAD

**Issue by tdeleanu** [mcollina/mosca#618]
Using Redis backend with auth mode enabled deadlocks server.

Fix is simple:
mosca/lib/server.js
Line 197
Move the: done(); after the if+else statements are finished

**Comment by mcollina** [comment]
can you send a PR?

**Comment by tdeleanu** [comment]
From what branch? I can't publish a new branch :D

**Comment by tdeleanu** [comment]
https://github.com/mcollina/mosca/pull/619

**Comment by tdeleanu** [comment]
invalid error, usage
