### ISSUE TITLE
User Isolation?

### ISSUE THREAD

**Issue by niklaswall** [mcollina/mosca#621]
Hi,

Is it possible to do "user isolation" by rewriting (prefixing) the topic based on user information?

To clarify:
a) User A issues pub/sub to the topic "sensors/123".
b) The topic is rewritten on ingress/egress so that the "internal topic" is user specific "userA/sensors/123".

This should of course be combined with pub/sub authorization, but will have the benefit of leaving the users free to choose their own topic without interfering with the rest of the users on the same server.

Cheers!

/NW

**Comment by mcollina** [comment]
@niklaswall it's probably possible, but definitely not documented. I think you should look to through the codebase and see. Also check out https://github.com/mcollina/aedes.

Let us know about your findings!

**Comment by niklaswall** [comment]
@mcollina Thank you for the quick answer, will probably look att aedes instead, will probably be a better fit :-)
