### ISSUE TITLE
send notification from server side to android client using web browser

### ISSUE THREAD

**Issue by YasserTahri** [mcollina/mosca#623]
Hi guys, 

i need help, i faced a problem to send notification from my web browser to android client !

can you explain with simple method for sending a notification message from web client 

thank you in advance

**Comment by mcollina** [comment]
How does that fits into Mosca? Can you explain your architecture a bit more?

**Comment by YasserTahri** [comment]
first , i have installed mosca on my windows server and after i added my broker in mosca and i'm trying to send notification message from my web client interface to ANDROID APP CLIENT

my architecture is : Browser chrome or fire (UI) == send message===> mosca ===> android application
My Broker : 

var mosca = require('mosca')

var ascoltatore = {
  //using ascoltatore
  type: 'mongo',        
  url: 'mongodb://localhost:27017/agg_mqtt',
  pubsubCollection: 'ascoltatori',
  mongo: {}
};

var moscaSettings = {
  backend: ascoltatore,
  http: {
    port: 3000,
    bundle: true,
    //static: './'
  },
  persistence: {
    factory: mosca.persistence.Mongo,
    url: 'mongodb://localhost:27017/agg_mqtt'
  }
};
var server = new mosca.Server(moscaSettings);
server.on('clientConnected', function(client) {
    console.log('client connected', client.id);
});
server.on('subscribed', (topic, client) => {
  server.publish(message, client)
})
 
// fired when a message is received 
server.on('published', function(packet, client) {
  console.log('Published', packet.payload);
});
 
server.on('ready', setup);
 
// fired when the mqtt server is ready 
function setup() {
  console.log('Mosca server is up and running');
}

Part web Client : 

<script>
	function getMessageval(){
	var mess = $( "#message option:selected" ).text();
		return mess;
		//alert(message);	
	} 
   var messageSelected = getMessageval();
	messageSelected = "myTest";
	console.log(message);
    var client = mqtt.connect();
	var sub = client.subscribe("/OK");
	
	client.on("message", function(topic, payload) {
	alert([topic, payload].join(": "));
	client.end();
	});
	client.publish("/OK",messageSelected);
</script>

can you help me how i can use the best solution to send message from my web client to android app 

thank you

**Comment by mcollina** [comment]
what's not working?

**Comment by YasserTahri** [comment]
when i tryto select message and clic into button to send my selected message to android app , in other word no notification is happened in android app also in my broker

**Comment by mcollina** [comment]
Does it work with a standard MQTT client?
Have you tried putting a full URL inside `mqtt.connect()`?

**Comment by YasserTahri** [comment]
already i have used this MQTT client : https://github.com/mqttjs/MQTT.js

and about mqtt.connect() already i made full URL of my server

**Comment by YasserTahri** [comment]
Code in my html page : 

<script>
	function getMessageval(){
	var mess = $( "#message option:selected" ).text();
		return mess;
		//alert(message);	
	} 
   var messageSelected = getMessageval();
	messageSelected = "myTest";
	console.log(message);
    var client = mqtt.connect();
	var sub = client.subscribe("/OK");
	
	client.on("message", function(topic, payload) {
	alert([topic, payload].join(": "));
	client.end();
	});
	client.publish("/OK",messageSelected);
</script>

also when i make full URL always i see this error message :

' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by mcollina** [comment]
In your script, you are not passing a full URL to `mqtt.connet()`. It should be something like `mqtt.connect('ws://{YOURDOMAIN/IP}')`,

**Comment by YasserTahri** [comment]
<script>
	function getMessageval(){
	var mess = $( "#message option:selected" ).text();
		return mess;
		//alert(message);	
	} 
   var messageSelected = getMessageval();
	messageSelected = "myTest";
	console.log(message);
    var client = mqtt.connect("ws://46.21.205.50");
	var sub = client.subscribe("/OK");
	
	client.on("message", function(topic, payload) {
	alert([topic, payload].join(": "));
	client.end();
	});
	client.publish("/OK",messageSelected);
</script>

message in console : 
WebSocket connection to 'ws://46.21.205.50/' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by mcollina** [comment]
from your example, you are running Mosca on port 3000, not 80.

**Comment by YasserTahri** [comment]
i changed port 3000 to 80 but same problem : 

WebSocket connection to 'ws://46.21.205.50/' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by YasserTahri** [comment]
yes i have done mqtt.connect('ws://46.21.205.50:3000') but unfortunetely the same problem

**Comment by YasserTahri** [comment]
message error : 
WebSocket connection to 'ws://46.21.205.50:3000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by mcollina** [comment]
you Mosca instance is not really running and/or exposed at that port.

**Comment by YasserTahri** [comment]
when i run subscribe and publish  on server by command it works but the problem when i run it on web client

**Comment by mcollina** [comment]
those are served on two separate ports. What is serving your web client?

**Comment by YasserTahri** [comment]
mosca port http : 3000
web client 80
MQTT port :1883

**Comment by mcollina** [comment]
so, you need to connect to port 3000 with `mqtt.connect()`.

**Comment by YasserTahri** [comment]
<script>

	function getMessageval(){
	var mess = $( "#message option:selected" ).text();
		return mess;	
	} 
	var client = mqtt.connect({ host: '46.21.205.50', port: 3000});

	client.subscribe('presence');

	console.log('Client publishing.. ');
	client.publish('/test12', 'Client 1 is alive.. Test Ping! ' + Date());
</script>

WebSocket connection to 'ws://46.21.205.50:3000/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by mcollina** [comment]
are you sure that port 3000 is open on that host? Is that host a server?

**Comment by YasserTahri** [comment]
port 3000 opened and IP is the adress of my server

**Comment by YasserTahri** [comment]
@mcollina can you tell me about the best  architecture and tools that i can use 

because i think it's a problem in my architecture 

thank you

**Comment by mcollina** [comment]
very likely, but I have little time, and this is Mosca issue tracker.

**Comment by YasserTahri** [comment]
already port is verified that it's opened
