### ISSUE TITLE
Store messages published on a specific topic

### ISSUE THREAD

**Issue by zairiedu** [mcollina/mosca#624]
Hi, 
I have multiple sensors, and i want the broker to store messages coming from these sensor on certain topic "?/data".
```
`server.on('published', function(packet, client) {
	if(packet.topic == '?/data'){
// how i can store packet.payload in mongo as a time series.
	}else{
		console.log('Just another message');
	} 
});`

```
thank you in advance.

**Comment by mcollina** [comment]
@zairiedu you need to use https://www.npmjs.com/package/mongodb to store the value.

**Comment by zairiedu** [comment]
Thank you @mcollina for your answer.
I've already installed mongodb, and the broker is working very well with publishing and subscribing.
the problem i'm having is whether do i require(mosca), and require(mongodb) to store time series , or just mosca have built functions to store messages, so i don't need to require(mongodb).
I've tried to understand the code on the persistence folder, but at certain point i miss something.

**Comment by psorowka** [comment]
@zairiedu this is a popular misconception. An MQTT broker is meant to route messages between publishers and subscribers and should be kept clean from business logic. In your case, sensors are publishers. When you want to store data permanently, I advise you to create a separate client that subscribes to the respective topics and stores data wherever you want it (be it mongodb or anything else).

As a hint: NodeRed is an easy starting point to try out different routes for your data. Simply hook it up with an MQTT node and subscribe to your Mosca Broker. From there you can easily connect different storages like MongoDb, SQL database or InfluxDb

**Comment by zairiedu** [comment]
Thank you very much @psorowka, your answer was right on the point.
I like the idea of another client subscribing to a particular topic then storing data on a database. (storage client) 
Thank you very much again.
