### ISSUE TITLE
Changing fields of Data that is saved in MongoDB 

### ISSUE THREAD

**Issue by duythang** [mcollina/mosca#625]
Hello community
I am using MongoDB as Backend of Mosca.
I saw that Mosca Log info is saved in MongoDB with fixed data fields (i.e. value, topic, options).
So, is there any solution if i want to add more data fields or edit these fields for a specific purpose ?

Thank you for your help.

**Comment by mcollina** [comment]
No, you should not do that. That storage is done for Mosca metadata, not for user data.

**Comment by duythang** [comment]
@mcollina: thank you for your rep. I saw that when i use mongoDB with mosca for sensing/ controling devices. There is a importance parameter that is time. I think that you shoud add time field inside stored data. Thank you
