### ISSUE TITLE
Can offline packages taken by the clients that is connected to server first time ?

### ISSUE THREAD

**Issue by barisvelioglu** [mcollina/mosca#634]
1) There are 2 clients but one has no internet connection at the beginning
2) Mosca server starts running
3) Client A connected to server
4) Client B is still no internet connection
5) Client A sends a few messages that can be taken by Client B, if the Client B is online
6) Then Client B connected to server

So I can understand that if Mosca knows there are two clients, it can send all offline messages to Client B when it is online with a persistence storage and QOS1. But what if Client B is never connected to mosca when it started. How can I tell mosca that there is also a Client B when the server started even if the Client B never connects to it ? So that I can have a chance to send offline message to Client B ?

**Comment by mcollina** [comment]
You cannot. You need a live offline subscription. If you need to set some messages that will be sent to every new subscriber, you can use retained messages.
