### ISSUE TITLE
How to install mosca to run as Embedding Mosca

### ISSUE THREAD

**Issue by duythang** [mcollina/mosca#641]
Dear community
i saw in the Wiki Tutorial. Authors mentioned only 2 ways to install to run Mosca as a Standalone.

1. Install the library using npm.
$ npm install mosca bunyan -g

2. Install the library using git
$ git clone git://github.com/mcollina/mosca.git
$ cd mosca
$ npm install

So how can i install to run Mosca as Embedding App of Node ?

Thank you so much for your help

**Comment by mcollina** [comment]
you need to run

npm install mosca --save

in your node.js project
