### ISSUE TITLE
how to get Client Object by client id?

### ISSUE THREAD

**Issue by maxingchi** [mcollina/mosca#648]
my situation is:

all device's clientId is recoreded in DB,  I need to publish message to some client filter by id. Is there any method to get the `client object` by id? or should I just use:

    server.publish(packer, {
        id: 'clientId'
    })

**Comment by mcollina** [comment]
Try `server.clients[id]`, however this will return the client connected to that specific broker.

The best approach is for each client to have its own topic, and publish messages there.

**Comment by maxingchi** [comment]
thank you，solved my problem
