### ISSUE TITLE
Topics are limited to: 10,000  (never more then 10k documents inside 'pubsub' collection)

### ISSUE THREAD

**Issue by syberkitten** [mcollina/mosca#653]
Trying to create many topics the limit observed inside the mongodb
'pubsub' collection is 10k.

Perhaps it could do with the following code,
but changing to higher value did not affect the limitation.
https://github.com/mcollina/mosca/blob/d284a971e5e714ed1876a37ae4525138d8d2d5fe/lib/persistence/utils.js

```

var LRU = require("lru-cache");
var cache = LRU({
  max: **10000**,  
  maxAge: 1000 * 60 * 60
});

```

**Comment by mcollina** [comment]
The two things are completely unrelated.  The settings you are looking for are in Ascoltatori. https://github.com/mcollina/ascoltatori/blob/master/lib/mongo_ascoltatore.js#L54-L56

**Comment by syberkitten** [comment]
Thanks for clearing this up.

So I understand that Mosca Uses Ascoltatori
as dependency, and i should configure it and pass a custom object ?

Will give it a try.

**Comment by mcollina** [comment]
As an example: https://github.com/mcollina/mosca/blob/master/examples/mongodb/config.js
