### ISSUE TITLE
Problem install raspbian raspberry pi

### ISSUE THREAD

**Issue by micheltlutz** [mcollina/mosca#659]
Trying to install on my raspberry pi I get the following error.

Versions described in the image.

I tried installing the dependencies manually but without success.

![erro_mosca](https://user-images.githubusercontent.com/536630/28078229-8fdaf2aa-663a-11e7-94a4-36174ef9ad4e.png)

**Comment by mcollina** [comment]
If you don't need those, you can safely ignore them.
