### ISSUE TITLE
How to keep me in the subscribed topics without subscribing again after logout or login on a new device?

### ISSUE THREAD

**Issue by harakuru99** [mcollina/mosca#667]
How to keep me in the subscribed topics without subscribing again after logout or login with the same account on a new device? This question for a mobile app?

What is your solution for this case?

Thank you & Best regards,

**Comment by mcollina** [comment]
The subscriptions are specific to a clientId. if the clientId stay the same, the subscriptions will stay the same. However, you should not issue a DISCONNECT. With this approach, only one of those devices would be connected at any given time.

**Comment by harakuru99** [comment]
Thank you. In this case, we want to allow one user to use many devices at the same time with their log-in (ex, a FB account in use on Android device, iOS device at the same time). So, is there any way for us to avoid subscribing all relevant topics again when they log-in on a new device with the same user account? Can we use the same clientID for many devices?
