### ISSUE TITLE
Problem with offline clients getting messages

### ISSUE THREAD

**Issue by scramble45** [mcollina/mosca#671]
mosca@2.5.2 running w/ Redis - Clients using mqtt.js

webclient : [http://www.hivemq.com/demos/websocket-client/js/mqttws31.js](http://www.hivemq.com/demos/websocket-client/js/mqttws31.js)

**Problem:**
When I subscribe and publish a message over websockets to mosca it's received by the listening client that's subscribed to those topics. However if the client is offline the message is never received when they come back online and subscribe again to those topics.

**How id like this to work:**
a webclient connects over websockets to mosca and a message goes out on a specific topic this message should go out to all clients that are subscribed to this topic. But if a client is offline and they reconnect to those topics I want to make sure they got the last message that we sent out.

I am using the following in mosca for options:
````
/*********************************************************
* Mosca
**********************************************************/

var dbSettings = {
  type: 'redis',
  redis: require('redis'),
  db: 12,
  port: 6379,
  return_buffers: true, // to handle binary payloads
  host: "localhost"
};

var serverSettings = {
  port: 1883,                  //default port is 1883 for mqtt
  backend: dbSettings,         //database sttings we have created earlier
  http: {
  port: 3000,
  bundle: true,
  static: './public',
  stats: true
  },
  persistence: {
        factory: mosca.persistence.Redis,
        host: 'localhost',
        port: 6379,
        db: 2
  }
}

var server = new mosca.Server(serverSettings);
````

**Comment by mcollina** [comment]
Are you using QoS 1, clean=false and unique clientId?

**Comment by scramble45** [comment]
Yes QoS 1 and clean = false and a unique clientId for each client.


**From the client:**
````
var options = {
    keepalive: 10,
    clientId: client_Id,
    protocolId: 'MQTT',
    protocolVersion: 4,
    clean: false, // set to false to receive QoS 1 and 2 messages while offline
    reconnectPeriod: 1000,
    connectTimeout: 30 * 1000,
    will: { // in case of any abnormal client close this message will be fired
        topic: 'ErrorMsg',
        payload: 'Connection was closed abnormally..!',
        qos: 1,
        retain: true
    },
    username: 'mqtt_client',
    password: 'somepassword',
    rejectUnauthorized: true, // message should be authorized
    resubscribe: true // if connection is broken and reconnects, subscribed topics are automatically subscribed again
}
````

**Comment by scramble45** [comment]
@mcollina may I get some clarification on this issue?

**Comment by scramble45** [comment]
So I guess I wasn't passing:
````
retained: true
````
in the webclient. The offline client now gets the message.
