### ISSUE TITLE
Could mosca publish files to client?

### ISSUE THREAD

**Issue by PinkGabriel** [mcollina/mosca#676]
I want to add a simple OTA function to the client system, could mosca transfer files to client?
Thanks very much!

**Comment by mcollina** [comment]
I would recommend against sending big files (1 MB+) over MQTT. Download them via HTTP.

**Comment by PinkGabriel** [comment]
Sorry for the delay, didn't get the notification email...
Thanks for the reply!
Ok I get it, I'll use HTTP.
Thanks!
