### ISSUE TITLE
help wanted How to enable log4j logs for mosca server.

### ISSUE THREAD

**Issue by sunny1974** [mcollina/mosca#690]
I want know how to enable log4j logs for mosca server.

**Comment by mcollina** [comment]
log4j? That's a Java logging library.

**Comment by sunny1974** [comment]
My question is i want to write mosca server logs like info,debug and error to a file path. How can i do it?Using bunyan or anything else?

**Comment by mcollina** [comment]
Mosca uses pino: http://getpino.io/#/.

You can pass all the options of tipo to the `logger` property of Mosca.

**Comment by sunny1974** [comment]
I'm very new to nodejs and mosca may be my question is wrong:

Question: Mosca is not using bunyan? 

logger, the options for Bunyan. (Example: {level: 'debug'} )
logger.childOf, the parent Bunyan logger.

Based on above lines i thought mosca used bunyan to write logs.

And can you please share me working example of logger implementation for mosca

**Comment by mcollina** [comment]
Mosca is currently using pino: https://github.com/mcollina/mosca/blob/master/package.json#L91.

Pino is API compatible with Bunyan.

https://github.com/mcollina/mosca/blob/master/examples/Server_With_All_Interfaces-Settings.js#L24

**Comment by sunny1974** [comment]
If i use below setting, Where logs should be logged(log folder path)?

logger: { name: 'MoscaServer', level: 'debug' },

**Comment by mcollina** [comment]
you can pass down `logger: { stream: fs.createWriteStream('dest') }` to store the log in a file.

**Comment by sunny1974** [comment]
Thanks @mcollina 

I tried same thing but no success. log file is created with 0kb and not writing any logs. Below is my configuration trails.

1) logger:{ name: "SunilServer", level: "debug",stream: fs.createWriteStream("/apps/mosca/logs/server.log") },

2) logger:{stream: fs.createWriteStream("/apps/mosca/logs/server.log") }

3)
var pinoms = require('pino-multi-stream');
var streams = [
  {stream: fs.createWriteStream('/apps/logs/rtmott/mosca/mosca.log')},
  {level: 'debug', stream: fs.createWriteStream('/apps/mosca/logs/mosca.log')}
]
var log = pinoms({streams: streams})

logger:log,

**Comment by sunny1974** [comment]
reply please

**Comment by sunny1974** [comment]
@mcollina 

I have changed this line https://github.com/mcollina/mosca/blob/master/lib/server.js#L152 below. So logs are writing to specified file path

this.logger = pino(this.modernOpts.logger,this.modernOpts.logger.stream);

**Comment by mcollina** [comment]
@sunny1974 can you send a PR?
