### ISSUE TITLE
[Question] Documentation for options out of date?

### ISSUE THREAD

**Issue by hardeep** [mcollina/mosca#697]
Hi I was just going through the documentation for constructing the server. Looks like options are passed through a [`modernize()`](https://github.com/mcollina/mosca/blob/master/lib/options.js#L51) method.

The documentation on the README.md, generated documentation, and wiki still refer to the [legacy options](https://github.com/mcollina/mosca/blob/master/lib/options.js#L320) structure.

As I'm writing a TypeScript declaration file, I'd like to follow recommended way instantiate a new server options object.

**Comment by mcollina** [comment]
I would highly recommend doing this for https://github.com/mcollina/aedes instead.

**Comment by hardeep** [comment]
@mcollina, thanks! I will definitely start there. I honestly had no idea Aedes existed. Much appreciated.
