### ISSUE TITLE
Mosca over Primus

### ISSUE THREAD

**Issue by matijagaspar** [mcollina/mosca#705]
So I stumbled upon this https://github.com/primus/primus/issues/48 and I was wondering if you managed to make it work @mcollina?

Reason I am asking is that I wanted to use uws as my web-socket implementation. And since the the current mqtt-connection requires a stream I can not make it work directly and Primus seemed like a good way around it. 

Another way I guess would be to create ws=>mqtt the wrapper myself?

**Comment by mcollina** [comment]
You should be able to do something with http://npm.im/aedes. It works on top of any Node stream.
