### ISSUE TITLE
How to enable only http port?

### ISSUE THREAD

**Issue by tsaiyl** [mcollina/mosca#709]
Hi,

I want to disable the default mqtt port, and enable only http port. Is this possible?

**Comment by mcollina** [comment]
There is the httpOnly option

**Comment by tsaiyl** [comment]
Sorry for re-opening. How do I use this option?

Wiki does not mention anything about this option,
searching `httpOnly`  in source code found only [a comment](https://github.com/mcollina/mosca/blob/19b6d25306dc4cf1f69dcc921947468348f53f37/lib/options.js#L188) about this option, but no code actually parses it.

I tried this:
```js
var moscaSettings = {
  httpOnly: true,
  http: {
    port: process.env.VCAP_APP_PORT || 8080
  },
  ...
}
```

and it doesn't seem to do anything : port 1883 is still enabled.
