### ISSUE TITLE
load banlancer 

### ISSUE THREAD

**Issue by willin** [mcollina/mosca#719]
i have several servers 

their config file are the same, all connect to a same redis server: 

```js
const moscaSettings = {
  host: 'same_server_ip'
  port: 1883,
  backend: {
    host: 'same_server_ip'
  },
  persistence: {
    factory: mosca.persistence.Redis,
    host: 'same_server_ip'
  }
};
```

and what the mosca server do is receive messages and insert them to mysql server.

the situation now is: when a message was sent to a specific/single server, all servers get the message and then this message was inserted duplicate times.

**Comment by mcollina** [comment]
How do you do this insertion? the published event should happen only in the originating server.

**Comment by willin** [comment]
```js
const messageHandler = async (topic, payload) => {
  const decodedMessage = Message.decode(payload);
  await mysqlInsert(decodedMessage);
};

server.subscribe('device/+/pubmessage', messageHandler);
```

**Comment by mcollina** [comment]
You should use the published event then, not subscribing. That is equivalent to a client subscription.

**Comment by willin** [comment]
```js
server.on('published', (packet, client) => {
 
});
```

do you mean this? 

we tried this before, but it receives too many unused sys messages.

**Comment by mcollina** [comment]
That’s what you should use. You can filter using mqemitter if you need to.

**Comment by willin** [comment]
oic
