### ISSUE TITLE
Move optional deps to peer deps

### ISSUE THREAD

**Issue by lightsofapollo** [mcollina/mosca#755]
Mosca is awesome but it takes forever to install due to all the optional deps (many of which fail without very specific native dependencies). I think it would be a major improvement to move all the optional deps to peer dependencies so people can include only what they would need.

Happy to submit a PR.

**Comment by mcollina** [comment]
I'm not necessarily ok with this. Currently Mosca is not being updated to newer Node versions due to failing tests.
Doing this would require dropping support for old version of NPM, as peerDependencies changed meaning (and that's why those are installed as optionalDependencies now).

**Comment by jhalag** [comment]
I actually ended up needing to use a (private) fork exactly for that purpose, stripping out all the unused dependencies. I have a hard time using a package for clients when the install fails with many (scary looking) errors that actually mean nothing.
