### ISSUE TITLE
[question]I cannot get more than 200 connections

### ISSUE THREAD

**Issue by Pakkes** [mcollina/mosca#813]
Hi. 
I cannot get more than 200 connections. I use the MQTT server (most recent version) on Windows environments, I've tried on Windows 10 and Windows 2012 server R2, both updated. I run client instances on machines different from the server.
By supposing the limit could be on the machine where I run the clients, I've used several machines for clients. With no success: after the 200th connection the server starts disconnecting further connections.
Is there something I need to tune on satellite modules? On 'ascoltatori', for example.  
I'm sure this is something related to a simple parameter to enlarge, however I cannot find it.
May you please help me?

**Comment by robertsLando** [comment]
@Pakkes please switch to [ades](https://github.com/moscajs/aedes)
